### ISSUE TITLE
Can't clone in Windows 10

### ISSUE THREAD

**Issue by hearnsj** [cormullion/juliamono#1]
Oooh.... this looks nice. I like FiraCode but wnat to give JuliaMono a try
When cloning in Windows Powershell it look slike the filename for specimen.pdf is fouled up.

rror: invalid path 'specimen (> 30MB!).pdf'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by cormullion** [comment]
Haha - perhaps my attempt at warning people it was big was a mistake.... Oh well. 

Anyway - you're too early - see you Friday! :) 

although I'll fix this now... :)
