### ISSUE TITLE
Backticks are aligned too high

### ISSUE THREAD

**Issue by simeonschaub** [cormullion/juliamono#10]
It looks like the normal large and the small backticks for multiple backticks are aligned along a too high baseline above. It's very subtle, but `"` and `'` seem to be aligned just a smidgen lower. This has the effect that ` ``` ` after a doctest, for example, looks a bit too close to the text above:

![Screenshot from 2020-08-02 23-43-11](https://user-images.githubusercontent.com/5220528/89133137-f2a4b280-d519-11ea-9e54-4e559f540e4f.png)

**Comment by cormullion** [comment]
Interesting, not sure what's happening here. If I type this (Atom/MacOS)

```
1g, 2g, 3g, 4g
" ``` '` "
```

I see this:
 
<img width="300" alt="Screenshot 2020-08-03 at 09 23 40 copy" src="https://user-images.githubusercontent.com/52289/89161939-32e05100-d56b-11ea-97c5-704635794d6c.png">

In the Terminal (MacOS, line spacing 1.0) I can type something similar to get it onto two lines, and I see this:

<img width="319" alt="Screenshot 2020-08-03 at 09 31 55" src="https://user-images.githubusercontent.com/52289/89162647-49d37300-d56c-11ea-937b-60b6f9cb7e0b.png">

There are many variables, I suppose, such as OS, editor, line spacing, etc. making it hard to reproduce here. It might be that some more hinting (#7) would eventually improve it for your setup.

**Comment by simeonschaub** [comment]
Hmm, interesting! If I make my font larger, this also mostly goes away, so it does seem related to hinting.
