### ISSUE TITLE
Question: Can I rely on the latest release always having the file `Juliamono.zip`?

### ISSUE THREAD

**Issue by heetbeet** [cormullion/juliamono#100]
Hi, I want to add Juliamono to Juliawin: https://github.com/heetbeet/juliawin/issues/50

Would it be future proof to automatically download `JuliaMono.zip` from https://github.com/cormullion/juliamono/releases/latest or will the filename change in the future? Or does the artifacts only get uploaded after a while after the release is made?

**Comment by cormullion** [comment]
Hello! Nothing is forever 😂  but I don't _currently_ have any plans to change the process of uploading the files and making a release from what happens at the moment. Of course, sometimes things change that aren't expected (github can change anything they like).

**Comment by heetbeet** [comment]
Thanks, that's good to know! So I'm gonna use this pipeline then for now. If in the future you change the filename of `JuliaMono.zip` just let me know (if you remember; if you forget, no worries I'll find it out easily enough).
