### ISSUE TITLE
Possible CDN issues

### ISSUE THREAD

**Issue by cormullion** [cormullion/juliamono#101]
I noticed today that there are some issues with downloading the font in certain circumstances.

[https://juliadiff.org/ChainRulesCore.jl/dev/autodiff/operator_overloading.html](https://juliadiff.org/ChainRulesCore.jl/dev/autodiff/operator_overloading.html)

<img width="1691" alt="Screenshot 2021-04-13 at 13 48 58" src="https://user-images.githubusercontent.com/52289/114554948-261a0e00-9c5f-11eb-8810-a50a56963749.png">

On the left - MacOS Catalina 10.15/Safari 13.1.3; on the right Firefox 87.0. The webconsole error message in Safari is a 403, which is the error "Package size exceeded the configured limit of 50 MB. " 

(Odd - the complete web fonts folder is 5,831,200 bytes (5.8 MB))

No problems on Firefox.

**Comment by knuesel** [comment]
For me it fails in Firefox and Chrome, and indeed visiting https://cdn.jsdelivr.net/gh/cormullion/juliamono/webfonts/JuliaMono-Regular.woff2 or doing `wget https://cdn.jsdelivr.net/gh/cormullion/juliamono/webfonts/JuliaMono-Regular.woff2` returns the same error.

It's strange that it works in your Firefox. Maybe it has cached the file from an earlier time when it was working?

I think this service is meant for npm packages? Looking at https://github.com/ipfs/js-ipfs/issues/1510 and the fix in https://github.com/ipfs/js-ipfs/pull/1513/files, my guess is that it counts the whole repository for the 50Mb limit. Maybe adding and `.npmignore` file to ignore all non-webfonts would fix it?

**Comment by cormullion** [comment]
Thanks for checking this out. It's been fine for months, so it's odd it's just started appearing - jolly good cacheing perhaps!

I started using jsdelivr at the suggestion of @fonsp the Pluto creator - perhaps there may be better places...

**Comment by fonsp** [comment]
The 50MB limit is for the entire github repository, and it looks like the total size is now 76MB.

Unless there large size increase was accidental, here are some possible solutions:
- Register as an npm package, jsdelivr has higher limits and generally better availability for npm packages.
- Split out the `webfonts` folder into its own repository.
- Place the `webfonts` in a separate branch, which does not contain the source files, register versions on that branch.

We @JuliaPluto can help you with either solution if you like! All three options can be automated. @pankgeorg

**Comment by cormullion** [comment]
@fonsp Thanks (as always)! I'll start off by having a spring clean, and moving all the artistic nonsense to another repo... I'm assuming they don't include the `.git` files, as that's > 500 MB.

**Comment by fonsp** [comment]
Ah and a fourth option:
- Create a separate repository to host the _specimens_, together they take up 48MB. Then 8MB is for the ttf.zip, the `.woff2` and `ttf` files combined only add up to 22MB.

**Comment by cormullion** [comment]
I just deleted those (perhaps they'll return someday)... :)

**Comment by fonsp** [comment]
I hope they will return! You can also upload them as extra files when you tag a release with the github web interface.

Can you tag a release?

**Comment by cormullion** [comment]
Yes, just got a cup of tea, ready for some github action :)

**Comment by cormullion** [comment]
I don't think there's any way to check the current status, behind the cacheing.... Will wait and see if it's resolved...

**Comment by cormullion** [comment]
I'm guessing (hoping) that this is no longer a problem. Cacheing for fonts is very aggressive at all levels of the system - sometimes it seems that even restarting my computer isn't guaranteed to clear all the possible cached versions of a font. (Restarting *twice* is [recommended](https://glyphsapp.com/learn/eliminating-font-cache-problems) by font experts. 😱 )

**Comment by knuesel** [comment]
I can confirm it's fixed: visiting https://cdn.jsdelivr.net/gh/cormullion/juliamono/webfonts/JuliaMono-Regular.woff2 I still got the error message, but after requesting a hard refresh I got the file to download. Also looking at the developer tools while loading https://juliadiff.org/ChainRulesCore.jl/dev/autodiff/operator_overloading.html , I see JuliaMono being downloaded as expected.

**Comment by cormullion** [comment]
Thanks!
