### ISSUE TITLE
Alternate superscript and subscript zeros?

### ISSUE THREAD

**Issue by anderslundstedt** [cormullion/juliamono#105]
As always, thanks for the great font!

I use the stylistic set `ss04`, making the zero look almost like an uppercase 'o' (this is suitable for "typesetting" mathematics). Would it not make sense if this stylistic set similarly changed the appearance of subscript 0 (`₀`) and superscript 0 (`⁰`) as well? (Perhaps there are more zeros that then also deserves corresponding changes.)

**Comment by cormullion** [comment]
Yes, I think it's possible - I'm getting a bit confused by all the zeros floating around 😄, but it's mostly working:

<img width="910" alt="Screenshot 2021-05-11 at 12 50 15" src="https://user-images.githubusercontent.com/52289/117810600-864ca180-b257-11eb-8661-4c37143393f8.png">

I can't get some of the rarer ones working (U2189, U277F), might be something fixable, not sure yet.

**Comment by anderslundstedt** [comment]
Looks good in the latest release!
