### ISSUE TITLE
Unable to use JuliaMono with paps (Cairo) under OS X

### ISSUE THREAD

**Issue by arbenede** [cormullion/juliamono#106]
I am trying to print some Julia code using [paps](https://github.com/dov/paps): 
`paps --output=a.pdf --format=pdf --font="JuliaMono-Regular 9" some_code.jl`
however the default font is used. I can see JuliaMono in the OS X Font Book. paps uses the Cairo/Pango library for text rendering. Any ideas? Thanks!

**Comment by cormullion** [comment]
I've never heard of `paps` and it's not easy to install, but I know that finding fonts can be a tricky process for most software.

Judging from the documentation, the example it gives is:

```
"Courier,Monospace Bold Italic 10"
```

so I'd try some permutations leaving out "-Regular" or leaving out the dash, and see what happens. I can't see any obvious reasons why some fonts wouldn't work though...

**Comment by arbenede** [comment]
Thanks @cormullion for the quick reply, indeed it seems that `--font="JuliaMono 9" ` did the trick!

**Comment by cormullion** [comment]
Cool! I don't understand font naming and finding, and I'm not convinced that many other people do... :)

**Comment by arbenede** [comment]
Closing the issue.
