### ISSUE TITLE
Slightly unmatched operators

### ISSUE THREAD

**Issue by knuesel** [cormullion/juliamono#107]
I was going to report unmatched operators for `≦` and `≧` but it seems you have fixed it already :) But while preparing the issue report, I found these other unmatched operators in the latest version (0.039):

```
⋚ ⋛  ⋜ ⋝  ⩽ ⩾  ⪉ ⪊  ⪍ ⪎  ⪓ ⪔  ⪝ ⪞  ⪳ ⪴  ⫅ ⫆ ⫋ ⫌   ⪕ ⪖  ⊴ ⊵
```

On my system at least each pair has some unevenness in size, weight or vertical alignment:

![image](https://user-images.githubusercontent.com/2412819/121340055-704a0380-c91f-11eb-92c0-8c491ce8baf4.png)

**Comment by cormullion** [comment]
Thanks! Fortunately few people probably use them in pairs... 😄 I'll fix these soon.

**Comment by cormullion** [comment]
There are many "axes of consistency" - it's hard to make all the various components match across the whole range of glyphs. But at the moment I've got this:

<img width="1188" alt="Screenshot 2021-06-13 at 10 48 25" src="https://user-images.githubusercontent.com/52289/121802592-11dd9780-cc35-11eb-91b0-965af362d4f6.png">

which is slightly better!

**Comment by knuesel** [comment]
To me it looks perfect!
