### ISSUE TITLE
Hi, how to active ligatures?

### ISSUE THREAD

**Issue by kifzuka** [cormullion/juliamono#108]

**Comment by cormullion** [comment]
Hello! You can delete the placeholder text for a new issue... 😀

There are thousands of possible combinations of operating system, hardware, editor, and so on, so it helps to know which particular combination you're using. 

And, by the way, JuliaMono doesn't have too many ligatures...

**Comment by kifzuka** [comment]
![image](https://user-images.githubusercontent.com/28493109/121786671-2769a780-cbca-11eb-8b67-b1f7ac664ea1.png)

i just want to active ligature of <= >= == ===

**Comment by cormullion** [comment]
Those ligatures aren't provided.

See https://juliamono.netlify.app/#contextual_and_stylistic_alternates

**Comment by kifzuka** [comment]
thank you, best font ever, <3
it would be great if you can make a special coding font with all ligatures

**Comment by cormullion** [comment]
You could try FiraCode, that has lots.

**Comment by kifzuka** [comment]
I prefered Julia

**Comment by cormullion** [comment]
The HTML opening comment will be in the SS14 stylistic option, it will look like this:

<img width="573" alt="Screenshot 2021-06-13 at 08 18 10" src="https://user-images.githubusercontent.com/52289/121798746-ef8d4f00-cc1f-11eb-8429-f3b918758ca4.png">

Ideally `<=` and `>=` should be replaced with the Unicode `≤` and `≥` . And the double and triple equal signs look better (and are more legible) with gaps in.

**Comment by waldyrious** [comment]
Woohoo, thanks for implementing ss13! For the record, this issue had been previously raised [here](https://github.com/cormullion/juliamono/issues/93#issuecomment-791649552):

> Not sure if it's appropriate to add this in this thread (happy to move it to a separate issue) — for HTML comments, the closing "arrow" is merged with a ligature, but the opening isn't:
>
> <img alt="Screenshot 2021-03-05 at 19 56 38" src="https://user-images.githubusercontent.com/478237/110167032-118b6000-7ded-11eb-88af-8de0461dcf28.png">
>
> For comparison, here's what Fira Code does:
>
> <img alt="Screenshot 2021-03-05 at 19 59 48" src="https://user-images.githubusercontent.com/478237/110167260-6a5af880-7ded-11eb-9015-8f77689a4222.png">

**Comment by kifzuka** [comment]
> The HTML opening comment will be in the SS13 stylistic option, it will look like this:
> 
> <img alt="Screenshot 2021-06-13 at 08 18 10" width="573" src="https://user-images.githubusercontent.com/52289/121798746-ef8d4f00-cc1f-11eb-8429-f3b918758ca4.png">
> 
> Ideally `<=` and `>=` should be replaced with the Unicode `≤` and `≥` . And the double and triple equal signs look better (and are more legible) with gaps in.

thank you

**Comment by xgdgsc** [comment]
Could there be a JuliaMono Lig font that make most of ligatures on by default?

**Comment by xgdgsc** [comment]
Either way is fine for me for less configuration needed.

**Comment by cormullion** [comment]
The first you can do now - https://juliamono.netlify.app/#opentype_feature_freezer - should be quite easy. And you'd only have to run it occasionally, since there aren't too many releases. 😀

The second requires significant time and energy to implement, so it won't be happening any time soon. But if there's one particular ligature that you want, you could open an issue and see if anyone else thinks it's worth adding.
