### ISSUE TITLE
Broken box-drawing characters

### ISSUE THREAD

**Issue by tk-nguyen** [cormullion/juliamono#109]
Hi, I'm running into a problem with the box-drawing characters, like some images below:
![screenshot_2021-06-22_15-16-45_333506693](https://user-images.githubusercontent.com/80101641/122889290-dcd7f000-d36c-11eb-8482-5348fb915395.png) ![screenshot_2021-06-22_15-19-15_972247391](https://user-images.githubusercontent.com/80101641/122889668-304a3e00-d36d-11eb-9d5f-7cba484d2b5d.png)
When I use other fonts, such as `FiraCode`, it works as expected:
![screenshot_2021-06-22_15-20-23_812281495](https://user-images.githubusercontent.com/80101641/122889848-5a9bfb80-d36d-11eb-9a2a-5456e5f9f945.png) ![screenshot_2021-06-22_15-20-57_118347795](https://user-images.githubusercontent.com/80101641/122889908-6be50800-d36d-11eb-88ba-30fbd7b9579b.png)
I'm currently using `v0.039` of the font.

**Comment by cormullion** [comment]
Can you provide an ASCII sample of text - it's easier to find the characters that are having problems...

**Comment by tk-nguyen** [comment]
Hi, I'm indeed on linux. Here's the broken character: ├ . I think it might be a problem with my terminal, since changing to another one the character appears as usual. Sorry for the trouble!

**Comment by cormullion** [comment]
It's certainly a very odd problem - if you track down the cause, let me know!

**Comment by tk-nguyen** [comment]
I changed the font from `JuliaMono` to `JuliaMono Regular` and it appeared as expected (well, kinda unaligned):
![screenshot_2021-06-23_18-56-55_917886847](https://user-images.githubusercontent.com/39090621/123092514-c0af7e00-d454-11eb-9367-ab278fb4ca6f.png)
Here's the font list:
```bash
~ ➜  fc-list | grep Julia
/home/thainguyen/.local/share/fonts/JuliaMono-RegularLatin.ttf: JuliaMono,JuliaMono Latin:style=RegularLatin,Regular
/home/thainguyen/.local/share/fonts/JuliaMono-SemiBold.ttf: JuliaMono,JuliaMono SemiBold:style=SemiBold,Regular
/home/thainguyen/.local/share/fonts/JuliaMono-Bold.ttf: JuliaMono:style=Bold
/home/thainguyen/.local/share/fonts/JuliaMono-BoldLatin.ttf: JuliaMono,JuliaMono Latin:style=BoldLatin,Bold
/home/thainguyen/.local/share/fonts/JuliaMono-ExtraBold.ttf: JuliaMono,JuliaMono ExtraBold:style=ExtraBold,Regular
/home/thainguyen/.local/share/fonts/JuliaMono-Medium.ttf: JuliaMono,JuliaMono Medium:style=Medium,Regular
/home/thainguyen/.local/share/fonts/JuliaMono-Black.ttf: JuliaMono,JuliaMono Black:style=Black,Regular
/home/thainguyen/.local/share/fonts/JuliaMono-Regular.ttf: JuliaMono:style=Regular
/home/thainguyen/.local/share/fonts/JuliaMono-Light.ttf: JuliaMono,JuliaMono Light:style=Light,Regular
```
I will try filing an issue with my terminal (`wezterm`)

**Comment by cormullion** [comment]
One thing occurred to me seeing that list - you could try deleting "JuliaMono-RegularLatin.ttf" and "JuliaMono-BoldLatin.ttf" - these are subsets designed to be quick to load. They do contain the box-drawing characters, but it's possible that something else about them is triggering a different behaviour. Fonts can be tricky little blighters.

**Comment by tk-nguyen** [comment]
I tried deleting those fonts you mentioned, and box-drawing characters appeared to be rendered fine (still kinda unaligned):
![screenshot_2021-06-23_19-59-12_822740954](https://user-images.githubusercontent.com/39090621/123100714-8b5b5e00-d45d-11eb-9f5a-baf9c3f4aeb5.png).

**Comment by cormullion** [comment]
Looks like @wez [knows a lot](https://github.com/wez/wezterm/issues/849) about fonts and font-fallbacks, so they'll be able to suggest more tests...

**Comment by cormullion** [comment]
Another point that occurs to me: some terminals might take on the task of drawing box characters themselves, ignoring what glyphs the font might provide...

The box drawing characters in JuliaMono vary in weight (so boxes are slightly thinner in JuliaMono-Light than in JuliaMono-ExtraBold. On terminals I have access to, boxes are drawn in different weights depending on the weight of the font. Eg Alacritty (macOS)

<img width="1174" alt="Screenshot 2021-06-23 at 15 16 14" src="https://user-images.githubusercontent.com/52289/123112867-fee97500-d435-11eb-8561-9f82c8f4aa5d.png">

That might not be the case with all terminals.

**Comment by tpoisot** [comment]
Using the font on Alacritty, I get this weird behavior of the progress bar block, which is overlapping with the previous line - is this related?

![2021-06-23-111711_881x91_scrot](https://user-images.githubusercontent.com/579329/123123433-d1d89a80-d414-11eb-9161-da78fbf93a34.png)

**Comment by tk-nguyen** [comment]
> 
> 
> Another point that occurs to me: some terminals might take on the task of drawing box characters themselves, ignoring what glyphs the font might provide...
> 
> The box drawing characters in JuliaMono vary in weight (so boxes are slightly thinner in JuliaMono-Light than in JuliaMono-ExtraBold. On terminals I have access to, boxes are drawn in different weights depending on the weight of the font. Eg Alacritty (macOS)
> 
> <img alt="Screenshot 2021-06-23 at 15 16 14" width="1174" src="https://user-images.githubusercontent.com/52289/123112867-fee97500-d435-11eb-8561-9f82c8f4aa5d.png">
> 
> That might not be the case with all terminals.

Yeah, they mentioned `kitty` does this, so my comparison in the original issue may not apply

**Comment by tk-nguyen** [comment]
> One thing occurred to me seeing that list - you could try deleting "JuliaMono-RegularLatin.ttf" and "JuliaMono-BoldLatin.ttf" - these are subsets designed to be quick to load. They do contain the box-drawing characters, but it's possible that something else about them is triggering a different behaviour. Fonts can be tricky little blighters.

As per the instructions on the `wezterm` issue, the terminal is loading `JuliaMono-RegularLatin.ttf`, which causes the broken box-drawing characters. Deleting them kinda fixes the problem.

**Comment by cormullion** [comment]
Good to know. You can see why fonts are frustrating to work with... :)
