### ISSUE TITLE
Distinguish between Chinese comma and English comma

### ISSUE THREAD

**Issue by Kinmfer** [cormullion/juliamono#112]
Could you distinguish between Chinese comma and English comma ? 
Thank you very much!

**Comment by Kinmfer** [comment]
![image](https://user-images.githubusercontent.com/47661687/126580724-16571a2c-121c-4946-b32d-5bce6cddf362.png)

**Comment by cormullion** [comment]
Hi! Interesting suggestion. What's the Unicode value for that? Also, what would be the use case for this - since there are no other Chinese characters provided...
