### ISSUE TITLE
Flat tilde above certain letters

### ISSUE THREAD

**Issue by DNF2** [cormullion/juliamono#116]
There is something odd about the rendering of tilde above certain lowercase letters. Notice the tilde above `i`, `u`, `v` and `y`, it is flat instead of 'wavy':
![tilde](https://user-images.githubusercontent.com/7106412/132520362-ec29f20b-b5a8-43ab-9767-f61507732ee8.PNG)

This happens for me for fontsizes up to 20, and goes away for size 21 and above.

Setup:
Windows 10, but running the Julia plugin under WSL2/Ubuntu
Julia plugin: v.1.3.34
JuliaMono version: v.0.042
VS Code version: 1.60.0

**Comment by cormullion** [comment]
What Unicode values are you seeing there? If it's just the combining tilde (`0x0303`):

```julia
for c in 0x41:0x7e
    print(Char(c), Char(0x0303))
end
```

the it may just be Windows (or the `xterm.js` terminal emulator)  being goofy... They look OK here (VS Code: 1.60.0, JuliaMono v0.042):

<img width="829" alt="Screenshot 2021-09-08 at 15 02 59" src="https://user-images.githubusercontent.com/52289/132524159-2158f347-3d93-431a-9bd0-7a139c20de93.png">

although some of these probably shouldn't exist at all (tilde-brackets?) ... :)

**Comment by DNF2** [comment]
This is odd. After pasting your code, the tildes look fine, both in the terminal and in the code pane. _Except_ for over the lowercase `a`, where it is now flat, like it was over `i`, `u`, `v` and `y` previously.

So that maybe indicates a Windows issue? But what do you think is happening, and is `0x0303` different from the character that `\tilde<TAB>` produces?

**Comment by cormullion** [comment]
Yes it's hard to pin down cross-platform font rendering issues...  

Julia's `\tilde` always produces `U+0303`, the combining tilde. There are other characters with tildes:

```
"˜ÃÑÕãñõĨĩŨũṼṽẪẫẴẵẼẽỄễỖỗỠỡỮữỸỹ"
```

I had a quick look in the github issues for [xterm.js](https://github.com/xtermjs/xterm.js/issues) and  [vscode](https://github.com/microsoft/vscode/issues) for related rendering problems, didn't see anything...  

I'd distinguish between the display in a VS Code code window and a xterm.js terminal emulator window - the former is often more reliable and better quality than the latter, but occasionally xterm does things that the browser doesn't - such as box drawing. You might also find that various line-height settings can affect the display of characters with additional diacritics.

I hope you find some settings that work!
