### ISSUE TITLE
Distinguishing the Fullwidth ASCII Variants from ASCII characters

### ISSUE THREAD

**Issue by kimikage** [cormullion/juliamono#117]
The range `U+FF01`–`U+FF5E` are the Fullwidth ASCII Variants, and currently (JuliaMono v0.042), they have the same glyphs as regular ASCII characters. (cf. https://en.wikipedia.org/wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block))
![fullwidth](https://user-images.githubusercontent.com/12679384/133064232-e28773b7-7a94-4c85-9faf-6665b49cceda.png)

For general graphics applications, that is not a problem. However, the fact that they are visually indistinguishable is annoying because in many programming languages, including Julia, they are distinct.

Of course, the problem of similar glyphs can be seen in many places in the Unicode (e.g. `U+0391` Greek Capital letter Alpha and `U+0041` Latin Capital letter A). I don't think it is possible to solve all of these problems.  However, the problem of Fullwidth ASCII Variants has a slightly different aspect, mainly due to the history of East Asian computer character sets.

The important thing here is to be able to notice if we have entered the Fullwidth ASCII Variants by mistake. In other words, whether they are "wide" or not is essentially unimportant. For example, shifting of the baseline may be a possible solution. In an extreme case, the Fullwidth ASCII Variants may not need any glyphs, just as JuliaMono does not contain glyphs for the ideographic (CJK) characters.

**Comment by cormullion** [comment]
Yes, these characters are automatically included in the font - using aliases to the regular ASCII versions... They appear with the `.full` suffix in my font editor:
 
<img width="1247" alt="Screenshot 2021-09-13 at 12 43 51" src="https://user-images.githubusercontent.com/52289/133077766-6396dc1e-e152-4d42-90f9-e3e4e1dc5659.png">

It would be easy enough to add some visual modification to these characters to indicate their different-ness: lines above or below, dots in the corners, underlined, etc.  - anything is possible. What do other fonts do? My searches have been unable to find out much information about them - references usually talk about proportional fonts rather than monospaced. 

I'm happy to make some edits  to these if you can convince me that I'm doing the right thing! :)

**Comment by kimikage** [comment]
In fact, many monospaced fonts do not support CJK characters, including the Fullwidth ASCII Variants. The "so-called" monospaced fonts that support CJK characters are not strictly "mono"-spaced fonts.

Classic CJK "so-called" monospaced fonts have glyphs with the square virtual body (mostly for CJK characters) and glyphs with the rectangular virtual body of half the width (mostly for ASCII characters). Some modern fonts, such as Source Han Mono, use more sophisticated metrics (cf. https://ccjktype.fonts.adobe.com/2019/05/source-han-mono-v1000.html). After all, they are not "mono”-spaced.

Therefore, if you are comfortable with JuliaMono having glyphs of different widths, that is the most usual practice. Otherwise, I think the "moderate" solution is to remove the support for the Fullwidth ASCII Variants and leave them to the fallback font.

Personally, I think visual modification is a good way, but I don't think there is a standard or "right" way. I am concerned that people who don't know the historical context will misuse "functional" decorations (e.g. underlines). So, the visual modification should probably be "ugly" one. :smile:

I'd like to know what other CJK characters users think. 
cc: @aviatesk, @genkuroki, @terasakisatoshi (Japanese-speaking Stargazers)
@johnnychen94 (Julia and simplified Chinese user, who I know well)

**Comment by cormullion** [comment]
>if you are comfortable with JuliaMono having glyphs of different widths

I don't think this is technically possible - the font will be marked as proportional and therefore unavailable in certain font pickers (to name one possible problem I've already encountered) 

Removing is the easiest solution, but it would be a pity to not make an attempt at a more positive solution...

Visual modification would be an interesting avenue to explore, but would have to be considered carefully to fit in with all the various diacritics that also decorate these glyphs.

**Comment by kimikage** [comment]
> would have to be considered carefully to fit in with all the various diacritics that also decorate these glyphs.

In actual use cases, the Fullwidth ASCII Variants are rarely used with diacritical marks, since the code sets from which the characters are derived do not support combining character sequences. In fact, many rendering systems cannot handle them correctly.

**Comment by kimikage** [comment]
Scaling the glyphs horizontally by 110% and vertically by 90% and shifting the baseline will also change the impression.
![fullwidth_ex](https://user-images.githubusercontent.com/12679384/133192223-c92fc390-73cb-480d-95b9-00f821e9d915.png)

I know this can be a pain to tweak for weight variations, though. :sweat_smile:

**Comment by cormullion** [comment]
Yes that would work - but it's basically adding another font, so would require more effort... 😄

**Comment by kimikage** [comment]
So, as a first step, I don't think the removing is a very negative solution. The translation (or shifting the baseline) is the next best thing in terms of effort, since it does not require changing the shapes.

**Comment by kimikage** [comment]
cf. #206
https://github.com/cormullion/juliamono/blob/master/CHANGELOG.md#v0055---2024-05-05-1534
The problem appears to have been fixed.
