### ISSUE TITLE
Make uppercase unicode frak and bfrak letters less ornamented?

### ISSUE THREAD

**Issue by simeonschaub** [cormullion/juliamono#12]
To me, the uppercase unicode frak and bfrak letters (codepoints 120068-120119 and 120172-120223) look a bit too ornamented, which also makes them harder to read:
![Screenshot from 2020-08-03 00-33-50](https://user-images.githubusercontent.com/5220528/89133967-056eb580-d521-11ea-9848-46090944b38d.png)

Wikipedia has some nice type samples [here](https://en.wikipedia.org/wiki/Fraktur), which are more straightforward. The bfrak letters are quite good for most letters, but `GHIJLOQ` are still a bit too complicated for my liking.

**Comment by cormullion** [comment]
I made these simpler versions:

<img width="719" alt="Screenshot 2020-08-07 at 09 11 14" src="https://user-images.githubusercontent.com/52289/89624496-3a1a9e00-d88e-11ea-80ce-dad19f9dca32.png">
<img width="796" alt="Screenshot 2020-08-07 at 09 12 28" src="https://user-images.githubusercontent.com/52289/89624503-3be46180-d88e-11ea-8dbc-c09bb680b2fc.png">

It looks a bit too 'metal' when seen all at once but they should work in mathematical contexts... :)

**Comment by simeonschaub** [comment]
Those look great! Awesome!

**Comment by simeonschaub** [comment]
Beautiful! Fixed now for me.
