### ISSUE TITLE
Glyphs for U+02BF and U+02BE differ

### ISSUE THREAD

**Issue by gitn--b** [cormullion/juliamono#121]
Thank you for the amazing font! I use the characters U+02BF and U+02BE quite often for transliterations and the difference in style between the two glyphs looks a bit jarring. Is there a particular reason for the difference? And if the difference is not intended, could the glyph for U+02BE be made to correspond to the glyph for U+02BF?

**Comment by cormullion** [comment]
Hi! There's no reason, just an error on my part I think. I'm hoping to make a new release soon, so I'll fix them then.

Thanks!

**Comment by gitn--b** [comment]
That would be amazing! Thank you!

**Comment by cormullion** [comment]
hopefully fixed in v0.044
