### ISSUE TITLE
Incongruity on website

### ISSUE THREAD

**Issue by wleightond** [cormullion/juliamono#127]
The alternate `0` character for `ss04` is different in

§ [contextual_and_stylistic_alternates](https://juliamono.netlify.app/#contextual_and_stylistic_alternates):
![specimen_7](https://user-images.githubusercontent.com/5555832/151540279-682d1d9e-7483-4af0-98a8-0fb23c5e7186.png)

and § [stylistic_sets](https://juliamono.netlify.app/#stylistic_sets):
<img width="710" alt="Screen Shot 2022-01-28 at 11 35 07" src="https://user-images.githubusercontent.com/5555832/151540322-98e3d99b-1dfd-4401-b753-bde59810b0d5.png">

I suspect the first one is incorrect and should not have the slash since `zero` does that.

**Comment by cormullion** [comment]
Hi, thanks. I have more trouble with CSS than with OpenType features 😂 I’ll take a look this weekend.

**Comment by cormullion** [comment]
It was an outdated screenshot, so I've deleted it.

**Comment by wleightond** [comment]
Okay, hope it was useful! Gonna close the issue.
