### ISSUE TITLE
about chinese symbols

### ISSUE THREAD

**Issue by Kinmfer** [cormullion/juliamono#130]
Hello, I like your fonts very much,but there is a little problem with Chinese symbols.
English symbols occupy 1 character, Chinese symbols should occupy 2 characters.
But it doesn't seem to be the case at the moment, especially when programming.(Show part of symbols)
**Julia**
![image](https://user-images.githubusercontent.com/47661687/156361185-1720a028-9530-4854-ad75-584dd07b587f.png)
**other fonts**
![image](https://user-images.githubusercontent.com/47661687/156361309-a42bd9ee-6bb0-4277-95c8-3d83624329c2.png)
![image](https://user-images.githubusercontent.com/47661687/156361362-1f0ccbb4-8e03-4b37-8b19-b1cf97ca75c3.png)
![image](https://user-images.githubusercontent.com/47661687/156361436-fc60f1c7-00bc-44c4-8dae-a9e802a194df.png)
Can you help to optimize it, thanks a lot!!

**Comment by cormullion** [comment]
Hi! Can you tell me the Unicode values you’re looking at- and/or some copy/paste able text I can examine? Thanks!

**Comment by Kinmfer** [comment]
Some examples.
unicode    |   text
\uFF0C     |  ，
\uFF1B     |  ；
\uFF1A     |  ：
\u3002     |  。
\uFF08     |  （
\uFF09     |  ）
\uFF01     |  ！
\uFF1F     |  ？

**Comment by Kinmfer** [comment]
Thanks for your reply.
My OS is Windows 10, font version is the latest.
In VS Code, JetBrains's series, these characters are not double-width
In VS Code
![image](https://user-images.githubusercontent.com/47661687/156477383-aaddeef2-9433-47ce-a20a-5a90620dd7ce.png)
In Pycharm
![image](https://user-images.githubusercontent.com/47661687/156477967-11e4bf36-cbe9-4162-a9a8-8f5741995707.png)
In Goland
![image](https://user-images.githubusercontent.com/47661687/156477638-3b7659b0-c911-4191-85c5-c00e7af8cff1.png)
However, in Terminal they are double-width
In Windows Terminal
![image](https://user-images.githubusercontent.com/47661687/156478605-d82e0d38-ee8f-41ed-ae5a-5a4c074839a2.png)
In Other Terminal which built in Electron
![image](https://user-images.githubusercontent.com/47661687/156478858-20175404-7029-4ed9-8a2a-e93c4b76a783.png)

I'm also a bit puzzled now.Haha.I think you are right, those other fonts have empty spaces. In Windows which language is Chinese,  the default fall-back font is SimSum.

Other example fonts are [FiraCode](https://github.com/tonsky/FiraCode),[JetBrains Mono](https://github.com/JetBrains/JetBrainsMono),[Source Code Pro](https://github.com/adobe-fonts/source-code-pro)

**Comment by Kinmfer** [comment]
Ok, I will  try your idea.Thank you very much.
