### ISSUE TITLE
Trump cards in Unicode playing card block

### ISSUE THREAD

**Issue by JanssenSimon** [cormullion/juliamono#131]
Hello!

I noticed that there is coverage of most of the unicode playing card block. The only glyphs missing are the Trumps (U+1F0E0 to U+1F0F5)

It would be nice to have these glyphs in a style that matches the lovely playing cards that are already there.

Cheers

**Comment by cormullion** [comment]
Hi! Yes, I saw those in the list but had no idea what they were - never seen them before. They're not the tarot, are they?

```
1f0e0 PLAYING CARD TRUMP-1 • individual
1f0e1 PLAYING CARD TRUMP-2 • childhood
1f0e2 PLAYING CARD TRUMP-3 • youth
1f0e3 PLAYING CARD TRUMP-4 • maturity
1f0e4 PLAYING CARD TRUMP-5 • old age
1f0e5 PLAYING CARD TRUMP-6 • morning
1f0e6 PLAYING CARD TRUMP-7 • afternoon
1f0e7 PLAYING CARD TRUMP-8 • evening
1f0e8 PLAYING CARD TRUMP-9 • night
1f0e9 PLAYING CARD TRUMP-10 • earth and air
1f0ea PLAYING CARD TRUMP-11 • water and fire
1f0eb PLAYING CARD TRUMP-12 • dance
1f0ec PLAYING CARD TRUMP-13 • shopping
1f0ed PLAYING CARD TRUMP-14 • open air
1f0ee PLAYING CARD TRUMP-15 • visual arts
1f0ef PLAYING CARD TRUMP-16 • spring
1f0f0 PLAYING CARD TRUMP-17 • summer
1f0f1 PLAYING CARD TRUMP-18 • autumn
1f0f2 PLAYING CARD TRUMP-19 • winter
1f0f3 PLAYING CARD TRUMP-20 • the game
1f0f4 PLAYING CARD TRUMP-21 • collective
```

I'll look them up some time.

**Comment by knuesel** [comment]
Searching for these codepoints on https://unicode.org/charts/ gives https://www.unicode.org/charts/PDF/U1F0A0.pdf which describes the series as

>These characters are used to represent the 52-card and 56-card variants of modern playing cards, as well as the 56-card Minor Arcana of the Western Tarot. The glyphs shown in the charts have only a symbolic and schematic equivalence to particular varieties of actual playing cards.

It seems that this description is incomplete: the [Minor Arcana](https://en.wikipedia.org/wiki/Minor_Arcana) is just the Tarot version of the regular cards, for example the regular "spades" correspond to the "swords" of the Minor Arcana so it doesn't include the trump cards. For the trump cards it seems that there are different versions: Occultists use the [Major Arcana](https://en.wikipedia.org/wiki/Major_Arcana) of the [Tarot de Marseilles](https://en.wikipedia.org/wiki/Tarot_of_Marseilles), but the reference glyphs in Unicode correspond to the playing cards (Tarot Nouveau), see https://en.wikipedia.org/wiki/Bourgeois_Tarot#Trumps.

**Comment by cormullion** [comment]
Ah, thanks - I've seen the traditional tarot quite often, in films etc., but never seen this Tarot Nouveau. Looks like an interesting challenge for a rainy day... :)

**Comment by JanssenSimon** [comment]
Thank you so much <3
