### ISSUE TITLE
Can't apply juliamono font for julia REPL in Windows

### ISSUE THREAD

**Issue by hungpham3112** [cormullion/juliamono#136]
Step to reproduce:
1. scoop install julia
2. open julia(julia app) not via any terminal
3. already have juliamono in your machine
4. right click on title bar > propertises > font > juliamono > see the result

![image](https://user-images.githubusercontent.com/75968004/159161110-387eeb02-719d-43b6-a35e-2248bb7356b6.png)

I still have the shortcut inside above directory. Thanks in advance.

**Comment by cormullion** [comment]
Hi! Can you try to install another font, say JetBrainsMono or Fira Code?

**Comment by hungpham3112** [comment]
> Hi! Can you try to install another font, say JetBrainsMono or Fira Code? If you can, then there might be an issue with JuliaMono; otherwise it looks like a problem that affects all fonts.

Yah, I tested and this is a problem with the REPL, not your font. Thank you.
