### ISSUE TITLE
U+237C ⍼ RIGHT ANGLE WITH DOWNWARDS ZIGZAG ARROW zig-zag isn’t straight

### ISSUE THREAD

**Issue by freemin7** [cormullion/juliamono#139]
According the addendum of [this](https://ionathan.ch/2022/04/09/angzarr.html) blogpost. 
> Julia Mono’s is a little weird: the bottommost bar of the zig-zag isn’t straight, and the vertical bar of the angle again has inconsistent widths.

I agree that it looks wrong. Let's do open source magic and make the blog post outdated.

**Comment by cormullion** [comment]
Yes, I added it to my todo list. 😂

**Comment by jackmmartin** [comment]
u+237c

**Comment by cormullion** [comment]
![iCab Mobile Session](https://user-images.githubusercontent.com/52289/190260438-7fed7e4c-9af0-4d4f-8e38-9930e6459a9a.png)
