### ISSUE TITLE
Hinting problems with curly braces

### ISSUE THREAD

**Issue by simeonschaub** [cormullion/juliamono#14]
At 10pt without antialiasing, curly braces are not vertically symmetric and are missing a part of the bottom closing bit:

![Screenshot from 2020-08-05 19-34-01](https://user-images.githubusercontent.com/5220528/89444923-c0ca6080-d752-11ea-869f-251d7c13489b.png)

**Comment by cormullion** [comment]
Looking at https://github.com/cormullion/juliamono/issues/5 , compared with other users you seem to prefer **very** close lines - is your line height set to something very small? Hopefully more hinting might help but if the lines touch they'll be cut off anyway (depending on enviornment, I suspect).

**Comment by simeonschaub** [comment]
I am using the [default kitty spacing](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.adjust_line_height), which seems to be no additional spacing at all. I would have thought that characters should never draw outside their respective line anyways, but maybe they do.

**Comment by cormullion** [comment]
Ah yes, I looked at my Kitty config and I'd set it to a luxurious 120%... :) If I set it to a miserly 90%, it still looks great:

<img width="607" alt="Screenshot 2020-08-05 at 19 49 14" src="https://user-images.githubusercontent.com/52289/89451898-ca54c800-d754-11ea-8297-a32c69564cb2.png">

so I can only hope that the hinting I've been adding improves it for you.

It's becoming clear that the task of making a font look good on everyone's machine is virtually impossible! :)

**Comment by simeonschaub** [comment]
Unfortunately, I still observe this on v0.005. Setting my line height to 110% does indeed fix it for me.

> It's becoming clear that the task of making a font look good on everyone's machine is virtually impossible! :)

Yes, the more I learn about these issues, the more I admire you for still battling on against these weird font rendering issues. Your work here is very much appreciated! At the end of the day, before you waste too much effort on this I think, I can manage to somehow live with 110% linespacing 😁.

**Comment by simeonschaub** [comment]
From https://github.com/kovidgoyal/kitty/commit/5555a66638fe758a73529414c16fef1ce0e0901f#commitcomment-41249130:

> That would imply that the fonts bounding box is correct so the patch above does nothing but the character is being positioned outside the bounding box when actually drawn. This needs to be fixed in the font.

**Comment by cormullion** [comment]
Haha, "buggy fonts"... :)

**Comment by simeonschaub** [comment]
To be fair, it turned out that JuliaMono is actually not "buggy" in that it is writing outside the bounding box. It's just the hinting that's a bit off.

**Comment by cormullion** [comment]
:) Well I've tweaked the design of these a bit, so perhaps v0.006 will be slightly better...

**Comment by simeonschaub** [comment]
Fixed in v0.006 for me! You are my hero! :tada:
