### ISSUE TITLE
HALFWIDTH ARROWs not actual arrows

### ISSUE THREAD

**Issue by pfitzseb** [cormullion/juliamono#140]
HALFWIDTH UPWARDS ARROW (U+FFEA)/HALFWIDTH DOWNWARDS ARROW (U+FFEC) are presumably supposed to be arrows (potentially with half of U+2191's width)

![image](https://user-images.githubusercontent.com/6735977/166418725-079c5365-81db-417f-8892-65b486b1d256.png)

Definitely not critical; I was mostly just confused by what those characters were supposed to be :P

**Comment by cormullion** [comment]
I'm confused too :) On my Mac: 

<img width="359" alt="Screenshot 2022-05-03 at 09 48 59" src="https://user-images.githubusercontent.com/52289/166426784-b11b93fb-6e09-4bfc-a462-9cd6295f8c87.png">

**Comment by pfitzseb** [comment]
Hmm, is this codepoint included in JuliaMono? Might just be us getting different fallback fonts or something?
```
$ otfinfo -u JuliaMono-Regular.ttf | grep 201F
uni201F 4714 uni201F

$ otfinfo -u JuliaMono-Regular.ttf | grep FFEC
```

**Comment by cormullion** [comment]
You're picking up peculiar fallback fonts I think, since they're not defined  in JuliaMono. I could easily add them if you needed them.

<img width="368" alt="Screenshot 2022-05-03 at 10 17 44" src="https://user-images.githubusercontent.com/52289/166430134-3073f78a-44a1-4c99-92f8-57646f95a721.png">

**Comment by pfitzseb** [comment]
> I could easily add them if you needed them

I don't, but thanks :) This was only motivated by me mucking around with Tokenize and stumbling over
https://github.com/JuliaLang/Tokenize.jl/blob/7ccb53489d5820feccbe60e3146ac6d81a1f00c8/src/token_kinds.jl#L1367-L1368
being rendered weirdly for me.

**Comment by cormullion** [comment]
Cool. It's good to know that someone's using the font, anyway...!
