### ISSUE TITLE
\blockrighthalf character U+2590 displaying as a quarter block

### ISSUE THREAD

**Issue by rmsrosa** [cormullion/juliamono#143]
I am on a Mac, and, when using JuliaMono in either the Mac Terminal or in VSCode, the right half block character U+2590 displays as the quadrant upper right block U+259D.

Here is an image showing, **on the bottom,** the integrated VSCode REPL (which I believe should actually inherit the font from the main editor window, but apparently is not) with the correct fonts and, **on the top,** the copy-and-pasted characters obtained from the output on the bottom and with the wrong fonts:

<img width="238" alt="Screen Shot 2022-06-15 at 08 56 59" src="https://user-images.githubusercontent.com/17986148/173821686-24708381-9345-4059-8761-6c93dcd484c8.png">

I did update (earlier today) to the JuliaMono font I downloaded today (v0.045). I am using Monterey 12.2.1 and the latest VSCode (1.68.0).

When I switch the font on the main editor window, the font is displayed correctly. It is only when it is set to JuliaMono.

Just pasting the code here for the sake of it (I know this will depend on the font used by the viewer's browser):
```julia
julia> "\u2590\u259d"
"▐▝"
```

**Comment by cormullion** [comment]
Hi! I get confused with all these block characters... 

I see this in the Terminal for "\u2590\u259d":

<img width="274" alt="Screenshot 2022-06-15 at 13 22 55" src="https://user-images.githubusercontent.com/52289/173825845-a0adbdba-a19d-40e9-b322-8a0f5ad130b1.png">

and this in VSCode:

<img width="156" alt="Screenshot 2022-06-15 at 13 24 17" src="https://user-images.githubusercontent.com/52289/173826227-cc0e8abe-aeb7-47e8-94ea-214c0f714aac.png">

Are these the wrong way round?

**Comment by rmsrosa** [comment]
This looks good. I don't know why it is different for me. I don't know what else I could check or try in order to debug it. Thanks for the quick reply!

**Comment by cormullion** [comment]
Fonts are aggressively cached by the OS - sometimes you have to close lots of apps down in order to get the newer versions installed. (There might be some cache-flushing commands somewhere, but I don't know them.) But as for your original problem, I'm not sure ...

**Comment by rmsrosa** [comment]
Hmm, okay. I will reboot the computer and see how it goes. I just updated the font today. Let's see. Anyway, I guess we can close this issue since it doesn't seem to be reproducible. If something comes up later, we'll reopen it. Thanks a lot!
