### ISSUE TITLE
Possible solution to font cannot be found

### ISSUE THREAD

**Issue by rikhuijzer** [cormullion/juliamono#146]
The documentation suggests adding the following to LaTeX:
```
\newfontfamily \JuliaMono {JuliaMono-Regular.ttf}[
    Path      = /Users/me/Library/Fonts/,
    Extension = .ttf
    ]
\newfontface \JuliaMonoMedium{JuliaMono-Regular}
\setmonofont{JuliaMonoMedium}[
    Contextuals=Alternate
]
``` 
This does work, but assumes that JuliaMono is installed on the system so throws an `The font "JuliaMono-Regular" cannot be found` in a GitHub Runner (https://github.com/JuliaBooks/Books.jl/pull/257, https://github.com/rikhuijzer/PlutoStaticHTML.jl/pull/124).

The following does work on systems where the font is not installed globally. 
```
\\usepackage{fontspec}
\\setmonofont{JuliaMono-Regular.ttf}[
    Path = $(juliamono_dir)/,
    Contextuals = Alternate,
    Ligatures = NoCommon
]

\\newfontfamily{\\juliabold}{JuliaMono-Bold.ttf}[
    Path = $(juliamono_dir)/,
    Contextuals = Alternate,
    Ligatures = NoCommon
]
```

For me this works now. I'm leaving this here for other people who will probably walk into this at a later point in time. Debugging LaTeX is hard.

**Comment by cormullion** [comment]
Thanks!
