### ISSUE TITLE
Package a stripped down version

### ISSUE THREAD

**Issue by uncomfyhalomacro** [cormullion/juliamono#147]
Hello cormullion! I really like the JuliaMono font but is there another version of this where it does not include glyphs (such as the Julia logo). I really want a stripped down version without the custom glyphs. If you have a suggestion on how to remove them, please do tell me. Thanks again!

**Comment by cormullion** [comment]
Hi! You could try using the "-Latin" fonts that provide just the basic bare-minimum character set.

But in general I think it's hard to know where to draw the line. Braille characters?  Box drawing glyphs? Mathematical Script fonts? There are many possible ways to describe "essential" and "custom".

In the manual/web site (https://juliamono.netlify.app/#if_you_really_dont_like_any_ligatures) there's the bones of a script you could use to make a font subset. The example there is to remove OTF features, but I think it could be adapted to remove glyph ranges.

But - in a way - wide-ranging Unicode support is kind of the whole point of this font; there are plenty of better fonts with less-wide coverage. 😂

**Comment by uncomfyhalomacro** [comment]
Alright. I tried your suggestion. It works. I didn't know that exists. Closing :heart:
