### ISSUE TITLE
Letter õ (otilde)

### ISSUE THREAD

**Issue by mihrits** [cormullion/juliamono#15]
In Estonian the letter õ is commonly used and at the moment the character has a bit too wide tilde for the base or it's too close to the base. For both õ and Õ. I might be oblivious about other languages and fonts, maybe Portugese fonts do use it like that. I've included some images to show, what looks to me, a more appropriate size and height for the tilde.
![image](https://user-images.githubusercontent.com/41431010/89506931-82758580-d7d4-11ea-92e4-43a519453055.png)
![image](https://user-images.githubusercontent.com/41431010/89507135-c5cff400-d7d4-11ea-8204-1caf1d0f3e3a.png)

**Comment by cormullion** [comment]
How about:

<img width="283" alt="Screenshot 2020-08-06 at 19 22 31" src="https://user-images.githubusercontent.com/52289/89567805-2fbebc80-d81a-11ea-9804-6ef306134193.png">

I don't want to go much smaller, given the lower resolution screenshots I've seen... :)

**Comment by waldyrious** [comment]
As a Portuguese speaker, all of the images in this thread look acceptable to me. Just one note — please make sure it is distinguishable from `ö` (o with diaeresis) and `ő` (o with double acute accent) at smaller sizes of the font.

**Comment by mihrits** [comment]
@cormullion These seem much better to me. Thanks!
