### ISSUE TITLE
Add fairy-chess glyphs such as U+1FA4F: WHITE CHESS KNIGHT-ROOK, and similar

### ISSUE THREAD

**Issue by PraseodymiumSpike** [cormullion/juliamono#150]
Of course, the other glyphs in the "Chess Symbols" block would be very much appreciated as well.

**Comment by cormullion** [comment]
😂 🤷‍♂️

**Comment by PraseodymiumSpike** [comment]
Is that a yes?

**Comment by cormullion** [comment]
![Please add Glyph 🩏 · Issue #150 · cormullionjuliamono](https://user-images.githubusercontent.com/52289/195455698-c2c50edf-ee1b-4296-8063-e4287df3e4ca.png)

**Comment by PraseodymiumSpike** [comment]
https://glyphy.info/?s=0x1fa4f
It shows as not available.

**Comment by PraseodymiumSpike** [comment]
further information: https://www.unicode.org/charts/PDF/U1FA00.pdf

**Comment by PraseodymiumSpike** [comment]
even more information: https://en.wikipedia.org/wiki/Chess_symbols_in_Unicode#Fairy_chess_pieces

**Comment by cormullion** [comment]
Right, I'm with you now. :) 

Here's the Unicode block:

<img width="302" alt="Screenshot 2022-10-13 at 10 27 15" src="https://user-images.githubusercontent.com/52289/195559045-6ee2ae65-e411-4db6-b271-3395e7b47951.png">

Originally I only did these ones:

<img width="814" alt="Screenshot 2022-10-13 at 10 26 11" src="https://user-images.githubusercontent.com/52289/195558800-40a1aae0-3f59-4ad9-9254-c34d0ac7ae25.png">

I didn't think the rotated ones were worth the effort, but now on reflection I think it might be more difficult to rotate glyphs so perhaps they're worth doing now.

I'll add the remaining ones for the next release.

Not sure when I'll tackle the XIANGQI pieces, though...

**Comment by PraseodymiumSpike** [comment]
I would suggest having the knight+bishop combination not be a horse with a piece taken out of it. That looks rather painful for the horse.

**Comment by cormullion** [comment]
The poor horse has already lost its legs...

**Comment by PraseodymiumSpike** [comment]
Well, presumably, they're there; they're just not shown.

**Comment by cormullion** [comment]
I redid the bishops and knight-bishops. 

<img width="603" alt="Screenshot 2022-10-16 at 16 01 46" src="https://user-images.githubusercontent.com/52289/196042761-61779558-50f1-4b5c-85d9-66cff887dc71.png">

Either Black or White is winning/losing...
