### ISSUE TITLE
Feature Request: Make capital Fraktur letters look more like Fraktur.

### ISSUE THREAD

**Issue by SyxP** [cormullion/juliamono#151]
I'm not sure if you're allowing this "in my opinion, this should be..." request, but is it possible to have an update (or at least a stylistic switch) for the capital Fraktur letters?

In particular some of the letters look very different from the usual Fraktur font, for example: 0x1d516 𝔖, gets rendered looking like a 5 in JuliaMono. This is (somewhat outdated) a popular symbol for denoting the symmetric group.

**Comment by SyxP** [comment]
Oh, it was changed in https://github.com/cormullion/juliamono/issues/12

**Comment by cormullion** [comment]
Yes, Fraktur is very hard to do, at small sizes. What do you make of the "𝔖" here? I'd guess at G, or E...

**Comment by SyxP** [comment]
When I first learned it, I always read it as a G, and took a while (before I discovered detexify) to learn that it was a S. But after years of looking at it, it now already looks like a S, so its hard to unsee. I notice that some other characters look different from the version I have in TeX, but I never really seen them used before, so I didn't know they were different. (The other fraktur symbols I have used is in lower-case.)

While searching around, I found a rather fun read: https://mathoverflow.net/questions/87627/fraktur-symbols-for-lie-algebras

**Comment by cormullion** [comment]
Difficult for me to imagine that people used to comfortably read this typeface daily 100 years ago...

**Comment by cormullion** [comment]
I'm making the "S" a bit less like what a 5 would look like in fraktur.

<img width="486" alt="Screenshot 2022-11-30 at 10 20 39" src="https://user-images.githubusercontent.com/52289/204858899-175e8351-4138-4063-802a-cbd662b30bca.png">

**Comment by DanielMGessel** [comment]
That one on the right is very nice although, just an opinion, it's a bit $ ish (yeah, I'm from the $tate$). Ignoring that, quite elegant!
