### ISSUE TITLE
f becomes strange symbol after install julia mono

### ISSUE THREAD

**Issue by brianguenter** [cormullion/juliamono#153]
I just installed Julia Mono on my windows 11 machine, with fonts downloaded from this repo a few days ago.  f is now being displayed as a strange symbol in VSCode (see picture). Has anybody seen this before and is there a simple fix?

<img width="275" alt="image" src="https://user-images.githubusercontent.com/116222085/206553224-428cbabd-fbd2-4a84-beff-2d29fd4a7ce4.png">

Just deleted JuliaMono from the fonts directory and downloaded the fonts again from here and reinstalled them. Problem is still there.

The f character appears to be the only one affected:

<img width="172" alt="image" src="https://user-images.githubusercontent.com/116222085/206557385-04d36e15-c51c-44ce-b71c-725c61f317c6.png">

**Comment by cormullion** [comment]
I see you've got various alternates - 'a', 'g', 'j', 'r', - did you select these, or is it some kind of default? Anyway, I'd guess it's caused by font cache-ing, which is fairly aggressive, right down to OS-level.

**Comment by brianguenter** [comment]
I did not consciously select the various alternatives 'a', 'g', 'j', 'r'. Didn't realize they were alternatives. 

I disabled the Windows font caching service, deleted the font cache and restarted the caching service to rebuild the font cache. But the strange character substituted for f is still there. 

This seems like a long shot but could this possibly be related to a graphics driver issue? My driver has been unstable lately with occasional lockups and black screens.

**Comment by cormullion** [comment]
> I did not consciously select the various alternatives 'a', 'g', 'j', 'r'. Didn't realize they were alternatives.

You usually choose these by adding lines to the [settings.json](https://juliamono.netlify.app/faq/#vs-code) but if you didn't specify them, it's interesting...

I've only seen issues similar to yours when I tried to update fonts without quitting applications first (on a Mac, the font daemons are reluctant to let go of old versions in memory). I can't think of another plausible reason for single glyphs to look so odd (apart from cosmic rays😀). 

Sorry I can't help more at present...

**Comment by brianguenter** [comment]
Thanks anyway. I'll close the issue then.
