### ISSUE TITLE
Provide choices for "J" and "3" to make the top not flat.

### ISSUE THREAD

**Issue by lptl** [cormullion/juliamono#154]
Hi, I would like to ask options for "J" and "3" so that the top of these two letters are not flat. I am using the "ss" to customise the font  and all things go very well. I wish more options could be added in the future.

**Comment by lptl** [comment]
For example:
<img width="66" alt="Screenshot 2022-12-19 at 22 11 37" src="https://user-images.githubusercontent.com/45854583/208525059-f7845180-2929-4a50-a537-33d222b6b6b2.png">
<img width="66" alt="Screenshot 2022-12-19 at 22 12 35" src="https://user-images.githubusercontent.com/45854583/208525071-f0d90088-8659-43cf-9277-02a81bb4d6bf.png">
The original styles are:
<img width="66" alt="Screenshot 2022-12-19 at 22 13 26" src="https://user-images.githubusercontent.com/45854583/208525170-e7547035-4604-49b6-802e-b17000812588.png">
<img width="66" alt="Screenshot 2022-12-19 at 22 13 32" src="https://user-images.githubusercontent.com/45854583/208525182-8b704f00-5796-4a03-af68-5ffdf5405254.png">

**Comment by cormullion** [comment]
Ok, I see. Thanks.
