### ISSUE TITLE
Cyrillic Small Letter Monograph Uk (U+A64B) gylph shape

### ISSUE THREAD

**Issue by Logo121** [cormullion/juliamono#155]
As per https://github.com/be5invis/Iosevka/issues/1517#issuecomment-1379422104.

A more thorough explanation can be seen [here](https://www.unicode.org/wg2/docs/n4607.pdf):
![image](https://user-images.githubusercontent.com/21302803/211997410-0acd188f-3e59-4ba4-b637-c9633859679b.png)

By this comment, the original lowercase Uk `ꙋ` should be blended, as opposed to the unblended `ᲈ` (U+1C88). These two forms coexisted in some writings, so the encoding of these two forms separately probably means that they are intended to be distinct.

(Not that I think they will ever be used in a way that the identification causes a problem but still)

For the current lowercase Uk, I'm not sure if they can be used directly for U+1C88 either. The sources and all fonts I found renders it as a `ѵ` over `о`, without the tail. If that glyph is to be supported along with this fix, it probably has to be remade.

**Comment by cormullion** [comment]
Thanks! I'm grateful for all the documentation you've supplied, but I confess I'm also quite confused as to what to actually do...

Let me ask two questions:

1 Which existing glyphs do you  me to change?

2 Which new glyphs do you want me to add?

I've been using the Unicode code charts as my main reference:

<img width="1068" alt="Screenshot 2023-01-12 at 10 05 45" src="https://user-images.githubusercontent.com/52289/212038770-970470fc-1fcd-4769-88aa-c88ebadbcf87.png">

<img width="554" alt="Screenshot 2023-01-12 at 10 09 17" src="https://user-images.githubusercontent.com/52289/212038785-b085a8ed-8a3c-478f-b9a5-5e51124f1fe1.png">

Are these suitable for adaptation?

**Comment by Logo121** [comment]
Only U+A64B needs to be changed.

I've mentioned U+1C88 (unblended uk) just in case you want to move the existing glyph for U+A64B to that codepoint.  
I'm not an expert at this either (I'm just referring to Unicode documents as well), so it's probably safe enough to just follow the Unicode-provided glyphs.  
That's what most fonts I found (and showed in that issue) do anyway.

**Comment by jmcwilliams403** [comment]
This issue was addressed with the latest release
