### ISSUE TITLE
How to turn of ligatures and contextual alternate characters in CSS

### ISSUE THREAD

**Issue by djalbat** [cormullion/juliamono#159]
Hello!

I am switching from FiraCode to JuliaMono in Occam:

https://occam.science

One thing, though. I couldn't get the script to strip out ligatures and the like to work. The Python tool seemed to work but the resultant file was corrupted somehow. When I converted it to a Woff2 file and tried it in Chrome, Chrome didn't like it.

Anyway, as I understand it I can disable ligatures and the like directly in CSS like so:

```
font-variant-ligatures: none;
```

My question then is whether this is all I have to do. This only has to work in the latest version of Chrome.

It is imperative that all ligatures and contextual alternate characters are disabled for reasons I won't bore you with.

Thank you for the amazing font, by the way.

**Comment by cormullion** [comment]
Hi! I will try to investigate the stripping script - I’ve not yet tried it (fredrik’s stuff is always good).

As for the CSS, it’s a can of worms, with each browser doing something different. The online references (eg [this Adobe](https://helpx.adobe.com/fonts/using/open-type-syntax.html) one) are good, but I sometimes think I see different behaviour. Eg, the ‘calt’ feature should be disabled if you don’t want contextual alternates - apparently it can’t be on Mac and yet I sometimes think it can …  

I think the stripping option will be best, but I don’t yet know why it doesn’t work… Certainly easier to test than CSS… 😄

**Comment by djalbat** [comment]
Thank you for the prompt reply. To clarify for yourself and for anyone else coming to this issue...

It was my mistake, missing out the `'*'` argument when making use of Python package. I found it while putting together this reply.

There is nothing wrong with Fredrik's script, it simply makes use of a particular Python package, calling it with certain arguments; and iterates over font files in a directory. It is convoluted in the way it does this, using Docker, but it is fine.

Here is a more transparent sequence of commands that may help some. It assumes you are using a Mac with a recent version of Python installed, together with Homebrew in order to install the necessary Woff2 utilities. Is also assumes that you are in a directory that contains a `JuliaMono-Regular.ttf` file.

```
brew install woff2
pip install fonttools
pyftsubset JuliaMono-Regular.ttf '*' --output-file=JuliaMono-Regular-STRIPPED.ttf  --layout-features-=calt,liga
woff2_compress JuliaMono-Regular-STRIPPED.ttf 
woff2_compress JuliaMono-Regular.ttf 
```

You can run these commands inside a virtual environment if you prefer. I left those lines out for brevity.

Note that you can see the differing file sizes when the TTF files are compressed.

Now you have two WOFF2 files, one with the ligatures, etc in place, the other with them stripped.

To make use of them, in the `head` element of your HTML file:

```
    <link rel="preload" href="css/woff2/JuliaMono-Regular.woff2" as="font" type="font/woff2" crossorigin >
    <link rel="preload" href="css/woff2/JuliaMono-Regular-STRIPPED.woff2" as="font" type="font/woff2" crossorigin >
```

And in your CSS:

```
  @font-face {
    src: url("/css/woff2/JuliaMono-Regular.woff2");
    font-family: "JuliaMono";
    font-weight: normal;
  }
  
  @font-face {
    src: url("/css/woff2/JuliaMono-Regular-STRIPPED.woff2");
    font-family: "JuliaMono-STRIPPED";
    font-weight: normal;
  }
```

Obviously change the paths to suit your setup.

Now reference these fonts in the usual way via the `font-family` style and you can see, as I did, that they both work.

My apologies Fredrik!

**Comment by cormullion** [comment]
Thanks very much! Hope it works out well.
