### ISSUE TITLE
Inverse geometric shapes consistency

### ISSUE THREAD

**Issue by Logo121** [cormullion/juliamono#160]
[reference from the equivalent issue for Iosevka](https://github.com/be5invis/Iosevka/issues/1606) in case you want to look into this as well.

![image](https://user-images.githubusercontent.com/21302803/224884208-d253e855-ec1f-483f-9825-4f3e2d59cf33.png)

Simply put, the Inverse geometric shapes `◘◙◚◛` probably should have the same inverted background as those in Legacy Computing symbols `🮴` (see the second row), though implementations vary.

Considering how close the backgrounds of those glyphs in JuliaMono are to the full character space (where as the inverted background for `🮴` does cover the whole thing), I'd guess this is just an oversight and can be changed.

**Comment by cormullion** [comment]
Hi! Should be an easy change. What are the typical uses for these glyphs?

**Comment by Logo121** [comment]
There aren't any defined "use" for these glyphs; they are mostly just remnants of old encoding systems, which have these "inverted" characters with full, inked background without any gaps.

I guess it's kinda like Box Drawing characters, or those multiline bracket or math operators, but far less useful.

**Comment by cormullion** [comment]
No worries- I thought you might have some cool app which uses them  (so why do we include them 😂)

**Comment by cormullion** [comment]
<img width="196" alt="Screenshot 2023-04-14 at 10 30 40" src="https://user-images.githubusercontent.com/52289/232006279-43c4efc8-18b0-426a-bf49-e1ac613067f6.png">

**Comment by Logo121** [comment]
Looks good. Is it just me or are the half circles slightly thinner than the full circle one though?

**Comment by cormullion** [comment]
Not just you, they are 😂
