### ISSUE TITLE
Download fonts with specific stylistic sets

### ISSUE THREAD

**Issue by lptl** [cormullion/juliamono#161]
Hi, maybe this issue is kind of irrelevant to this font. I wish to download fonts with specific stylistic sets instead of setting them in editors. For example, I choose ss01 and ss03 then the downloaded font would use ss01 and ss03 stylistic set. 

I tried to use FontForge and FontLab to edit the downloaded font, but it seems hard to do it manually. I can't replace the glyph with another glyph. I think there must exist a function to load existed stylistic sets and export as a new font so I can use. But after trying a long time, I can't find how to do it.

**Comment by lptl** [comment]
Sorry I think I solved it my problem with FontLab. But it would be nice if such download option could be developed in the future :>.

**Comment by cormullion** [comment]
Although I can't make a web site that does this type of thing, you can  use `fonttools` at the command line (https://fonttools.readthedocs.io/en/latest/subset/index.html) to process a font locally to your requirements. For advanced customizations you could look at the Iosevka font (https://fonttools.readthedocs.io/en/latest/subset/index.html) perhaps.
