### ISSUE TITLE
Ascii tilde

### ISSUE THREAD

**Issue by iandoug** [cormullion/juliamono#163]
Hi

Thanks for all you hard work. :-)

Is it possible to get a more distinct ASCII Tilde? It does not have to be as exaggerated as Hack, but more distinct from a dash and swung dash would be nice.

Use case: as a separator is .csv files, works better than commas.

Thanks, Ian

**Comment by cormullion** [comment]
Hi! Yes, there are ways. What’s your editing environment? In VS-Code, for example, it would be possible to select font CVs - Character Variants; I could add an alternative tilde as, say, cv03 or similar. At the moment there is cv01 and cv02 (alternative 3 and 7 designs).

**Comment by iandoug** [comment]
Hi

Thanks for reply. 

I live in Kate on Linux :-)

I don't see any options for stylistic alternatives in the settings.

I suppose I could do something drastic like borrowing the glyph from Hack, Iosevka, JetBrains or Noto :-)

Thanks, Ian

**Comment by cormullion** [comment]
This -  https://github.com/twardoch/fonttools-opentype-feature-freezer - could be useful, once there’s an alternative tilde glyph in the font. I’ll investigate. 😀

**Comment by cormullion** [comment]
Default tilde:

<img width="395" alt="Screenshot 2023-04-15 at 16 48 45" src="https://user-images.githubusercontent.com/52289/232235259-90360148-1490-4306-851b-d9c540ad7397.png">

Alternative tilde in `cv03` 

<img width="406" alt="Screenshot 2023-04-15 at 16 49 29" src="https://user-images.githubusercontent.com/52289/232235260-8f0b9057-273b-44a8-be19-e0c0208977cd.png">

Will be in the next release...

**Comment by iandoug** [comment]
Cool, thanks :-)

**Comment by iandoug** [comment]
BTW I include Julia Mono in my comparison of fonts suitable for academic writing.
Busy working on an update to latest versions and Unicode 15. But need a font that has most of the glyphs ... Symbola is not so free any more. 

https://www.keyboard-design.com/academic-font-coverage-comparison.html

**Comment by cormullion** [comment]
Interesting site! Might be worth indicating the monospaced fonts somehow, since they have a specific use case.

**Comment by iandoug** [comment]
Mmm.. let me see how well it works if I colour-code the text sample backgrounds to Sans / Serif / Mono.

Thanks, Ian

**Comment by iandoug** [comment]
> Interesting site! Might be worth indicating the monospaced fonts somehow, since they have a specific use case.

Done.
https://www.keyboard-design.com/academic-font-coverage-comparison.html
