### ISSUE TITLE
Lowercase letter 'œ' (U+0153) is slightly squashed together

### ISSUE THREAD

**Issue by 5hwb** [cormullion/juliamono#166]
The lowercase form of the ligature letter 'œ' has a noticably squished shape, especially compared to the very similar ligature letter 'æ'.

Here's a screenshot of [the sample text box on the JuliaMono website as of 1 May 2023](https://juliamono.netlify.app/) - note how 'œ' takes up less space than 'æ' but ends up more cramped than it should be.

![juliamono oe ligature issue](https://user-images.githubusercontent.com/18253200/235438608-2ee475af-2d3b-4ac0-913c-fbbf841e9725.png)

This happens with all weight and italic variants of JuliaMono:

![image](https://user-images.githubusercontent.com/18253200/235439239-d50deab6-75f9-4e37-95c9-f1d29e2faeb3.png)

![image](https://user-images.githubusercontent.com/18253200/235439265-b218ecb3-01e0-4ad4-8b46-f0dca87ceed2.png)

![image](https://user-images.githubusercontent.com/18253200/235439331-b2707638-74fb-4455-bdc3-a269130ab8e2.png)

Could this be fixed eventually?

**Comment by cormullion** [comment]
Thanks! Yes. should be in the next release...

**Comment by 5hwb** [comment]
Cool - I confirmed that the issue is resolved, happy to close now.
