### ISSUE TITLE
Please add missing family name aliases "JuliaMono Regular" and "JuliaMono Bold" to respective ttf files

### ISSUE THREAD

**Issue by DanielMGessel** [cormullion/juliamono#168]
Most of the different weights have a second family name with a space and the weight appended.

Adding the alias for Regular and Bold would solve a weight selection problem in a program I'm using.

**Comment by cormullion** [comment]
Does this version of JM Light behave a bit better in your program? 

[JuliaMono-Light.ttf.zip](https://github.com/cormullion/juliamono/files/11375763/JuliaMono-Light.ttf.zip)

**Comment by DanielMGessel** [comment]
Thanks - I don't think it's a problem with "Light" - I'm using a fairly deep stack of Python libraries to generate png files on Debian GNU/Linux so it's a bit messy. I don't actually know the face selection algorithm (or which layer it's actually in), but it's not doing what I want if I use family "JuliaMono". It's peculiar to this SW stack: I generate intermediate SVGs which select differently (better) under FireFox.

It turns out I can get a specific weight by using a family name like "JuliaMono Medium", which looks like an alternate family name in the font file. However, Regular and Bold only have "JuliaMono" as a family name and they're not being selected at all. If Regular and bold had the longer family alternate family names, "JuliaMono Regular" and "JuliaMono Bold", I could easily override the weight selection algorithm entirely.

Since these alternate names are in most of the files, it doesn't seem like it would be a bad thing to have them in all the files.

If there's a good reason they aren't in the Regular and Bold weights, I'll see if I can fix it up with Python fonttools (my skills there have gotten rusty since I last used them).

**Comment by cormullion** [comment]
In that version I added the additional names and weight (300) only to Light (first on the list😀) - those are the only two fields I can find that let me add extra names. If they don't work in Light I don't need to bother adding them to all the others...🤔

**Comment by DanielMGessel** [comment]
My bad: the Long family names show up in fc-list (a Linux font utility) and I assumed they were in the ttf files. If they’re not in the files, they must be generated by the OSs font management. Apologies for making assumptions. I’ll dig around a bit and report back in a day or two, and most likely close this issue.

**Comment by DanielMGessel** [comment]
That was quick: it’s a fontconfig thing - Regular and Bold do not get family aliases, but other styles do. I’ll have to fix it up on my end; sorry for the spurious issue.

**Comment by DanielMGessel** [comment]
Kept digging here and the ttx tool shows that the first name entry in the ttf file is long for some, light JuliaMono Light:

   <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      JuliaMono Light
    </namerecord>

But this, from JuliaMono Regular is just the short name:

    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      JuliaMono
    </namerecord>

The idea would be to change the name to "JuliaMono Regular"... Is that possible and reasonable?

I should be able to do it on my end with ttx if not.

Thanks.

**Comment by cormullion** [comment]
I'm just following the advice [here](https://glyphsapp.com/learn/naming). I'll have another look some time, but I don't want to change anything which might affect everyone else's installation... 😱😀

**Comment by DanielMGessel** [comment]
Thanks for the link; that explains alot. Fontconfig has a fairly powerful selection override mechanism that can be tuned systemwide and per-user. I've just been learning some of the details and was able to (not 100% cleanly) get it to behave the way I wanted.

I'm going to share the `.fonts.conf` file I put in my home directory; I may not be the last to try to figure this out.

Thanks for your patient support.
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
<dir>/usr/local/share/fonts</dir>

<match>
  <test name="family"><string>JuliaMono Regular</string></test>
  <edit name="family"><string>JuliaMono</string></edit>
  <edit name="weight"><int>80</int></edit>

</match>
<match>
  <test name="family"><string>JuliaMono Bold</string></test>
  <edit name="family"><string>JuliaMono</string></edit>
  <edit name="weight"><int>200</int></edit>
</match>
</fontconfig>
```
