### ISSUE TITLE
Some of sytlistic sets won't change when replaced with Open Type Feature Freezer

### ISSUE THREAD

**Issue by adityadaniel** [cormullion/juliamono#169]
Hi! 

Thank you for creating Julia Mono. 

However I see some issue where stylistic sets won't change when use [open type feature freezer](https://github.com/twardoch/fonttools-opentype-feature-freezer). 

For examples, running this command won't change the `r` glyph into serifless. 
`pyftfeatfreeze -f 'ss01,ss08,ss09,ss10' ~/Downloads/JuliaMono-ttf/JuliaMono-Regular.ttf ~/Downloads/JM-Regular.ttf`

**Comment by cormullion** [comment]
looking through some of the issues on the https://github.com/twardoch/fonttools-opentype-feature-freezer repo, I wonder whether this is supposed to work like that. On my first reading it appears to just remap Unicode values only - and the alternate ’r’ doesn’t have a Unicode value so …

Have a look at the issues there and see what you think.
