### ISSUE TITLE
Umlauts have different baseline

### ISSUE THREAD

**Issue by simeonschaub** [cormullion/juliamono#17]
Probably effects other characters as well. Unrelated to font size:
![image](https://user-images.githubusercontent.com/5220528/89571045-53d4ca80-d827-11ea-85a6-0dd4f0427aa9.png)

**Comment by cormullion** [comment]
Hi Simeon! I'm not sure what I'm looking at here - is this another kitty example? 

On my kitty (v0.16.0, MacOS, linespacing 110%) I see:

<img width="232" alt="Screenshot 2020-08-07 at 09 01 44" src="https://user-images.githubusercontent.com/52289/89623572-bd3af480-d88c-11ea-85d9-d0fa8d7a90f0.png">

**Comment by simeonschaub** [comment]
Ah, I should have tried more combinations! With 100% linespacing, I am seeing this for all font sizes. I am still seeing this up to 130% linespacing at 10pt font size, but then it goes away if I make the font large. The latest kitty master with `--debug-font-fallback` doesn't give any warnings when writing umlauts, so it doesn't seem like kitty is intentionally moving these around, probably just bad hinting again.

**Comment by cormullion** [comment]
:(  You've put me off Linux for life... Can I interest you in an iMac 5K? :)

**Comment by simeonschaub** [comment]
Sure – if you get me one. :grin: Might still install Linux on it though. (Although I've heard that they're new "security chip" might prevent that nowadays, so you might have me there.)

**Comment by cormullion** [comment]
So after a bit more investigation, I think I'm blaming this on Kitty. On the left, the Ubuntu terminal; on the right, Kitty.

![Screenshot from 2020-08-08 08-28-52](https://user-images.githubusercontent.com/52289/89705054-ccd04100-d951-11ea-8117-08839f2c7c9e.png)

So I'm saying "buggy app" :)

**Comment by simeonschaub** [comment]
Just discovered that this was fixed with v0.011, even with 100% linespacing. Awesome! :tada:

**Comment by simeonschaub** [comment]
Unfortunately it broke again in 0.012 :cry:

**Comment by cormullion** [comment]
damn - I'm trying to compromise between #30 and this one... but it 's like trying to square the circle. ¯\\\_(ツ)\_/¯

**Comment by cormullion** [comment]
Anyway, it looks good here, so it must be kitty's fault: :) I'll keep at it, though.

<img width="1357" alt="Screenshot 2020-09-01 at 18 28 46" src="https://user-images.githubusercontent.com/52289/91886276-052d1b80-ec81-11ea-9c52-ee97702d693c.png">

**Comment by simeonschaub** [comment]
Yeah, I very much appreciate your persistence here!
