### ISSUE TITLE
Italic font can not display

### ISSUE THREAD

**Issue by kalong911** [cormullion/juliamono#172]
0.049 the Italic can not display, but 0.048 can display.
![图片](https://github.com/cormullion/juliamono/assets/134461846/f265da40-12ec-40f1-873b-f68c63f9559c)

**Comment by cormullion** [comment]
Hi! That's the job of the editor, and down to the way you've configured it.

I don't use Sublime Text myself, but a quick search yielded this: https://forum.sublimetext.com/t/how-to-make-comments-in-italics/11776 ...

**Comment by stevenbagley** [comment]
I am seeing the same problem using Emacs on MacOS. Version 0.048 italics work. Version 0.049 italics do not.

**Comment by cormullion** [comment]
That’s interesting if 0.048 worked and 0.049 doesn’t. Let me investigate to see whether the software generated anything different. What’s the emacs environment?

**Comment by cormullion** [comment]
Do you run it in a terminal (sorry, not an Emacser😀)

**Comment by stevenbagley** [comment]
I am using Emacs as a GUI application, not in the terminal.

**Comment by cormullion** [comment]
Ok thanks. One guess is that `fontconfig` has decided to unlink the files from the same family, after some change in the exported fonts. I’ll investigate when I’m not on my phone.

**Comment by cormullion** [comment]
I've made a small change to the font naming, and it seems to work so far in SublimeText and Emacs. This will be in the next release if it all works OK.

<img width="913" alt="Screenshot 2023-05-30 at 13 03 38" src="https://github.com/cormullion/juliamono/assets/52289/d95ff271-4526-4646-8396-4abefd320990">

**Comment by stevenbagley** [comment]
Version 0.050 solves the italics problem for me. Thanks.
