### ISSUE TITLE
New stylistic set for parentheses

### ISSUE THREAD

**Issue by capiet** [cormullion/juliamono#173]
Hi! I really want to know if there are any future plans for extending stylistic set features, especially for parentheses. While the font is really awesome, they (parentheses) stand out from the rest of the characters in height, even comparing with curly and square braces. If it's not possible in the nearest feature, then I would close the issue, because I think it's not going to be a popular feature request for you. Thanks!

**Comment by cormullion** [comment]
Hi! Can you indicate visually what sort of thing you have in mind, and what the benefits are - the main design principle of JulyaMono is to make important programming characters extra legible. Adding a couple of extra glyphs isnt too much work though 😂

**Comment by capiet** [comment]
Your example looks similar to what I had in mind, however, I would also like to make these brackets more rounded if possible. Over the past two years I have used many different fonts, and in some, such as Hack, I have met a type of brackets similar to yours, in my opinion they look in the sense that they are somehow too straight. I understand that it makes no sense for you to focus on other fonts, but for example, brackets in Jetbrains Mono in terms of rounding and general appearance in the text, again in my personal opinion, looks less eye-catching and pleasing to the eye. As for the size of the remaining brackets, I think it is also possible, if you want to implement them, to add for them the possibility of including approximately the same size. This is solely my personal opinion about these fonts, but perhaps it will be useful for you in terms of developing your own font. Here's an image with Jetbrains Mono braces types.
![изображение](https://github.com/cormullion/juliamono/assets/79054211/f73b4089-547c-4fa0-b483-062af14e163e)

**Comment by cormullion** [comment]
Do you mean parentheses -()- or brackets-[] ?

**Comment by capiet** [comment]
> Do you mean parentheses -()- or brackets-[] ?

I mean parentheses but as you said before "What about the brackets and braces - should they also be reduced in size?", I think that brackets and braces could also be reduced.
