### ISSUE TITLE
Problems with mathematical double struck characters

### ISSUE THREAD

**Issue by djalbat** [cormullion/juliamono#174]
I am not quite sure whether I have done something wrong or that you don't have support for these characters.

Here are my mappings...

```
  "DOUBLE-STRUCK CAPITAL C": 0x2102,
  "DOUBLE-STRUCK CAPITAL H": 0x210D,
  "DOUBLE-STRUCK CAPITAL N": 0x2115,
  "DOUBLE-STRUCK CAPITAL P": 0x2119,
  "DOUBLE-STRUCK CAPITAL Q": 0x211A,
  "DOUBLE-STRUCK CAPITAL R": 0x211D,
  "DOUBLE-STRUCK CAPITAL Z": 0x2124,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL A": 0x1D538,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL B": 0x1D539,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL D": 0x1D53B,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL E": 0x1D53C,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL F": 0x1D53D,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL G": 0x1D53E,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL I": 0x1D540,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL J": 0x1D541,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL K": 0x1D542,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL L": 0x1D543,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL M": 0x1D544,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL O": 0x1D546,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL S": 0x1D54A,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL T": 0x1D54B,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL U": 0x1D54C,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL V": 0x1D54D,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL W": 0x1D54E,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL X": 0x1D54F,
  "MATHEMATICAL DOUBLE-STRUCK CAPITAL Y": 0x1D550,
```
The double struct characters work fine but the mathematical double struck characters do not:

<img width="401" alt="Screenshot 2023-06-10 at 16 26 53" src="https://github.com/cormullion/juliamono/assets/17334729/3178dde9-32a0-4761-a1bd-e688024e2de8">

Do you have any idea why?

Many thanks in advance!

**Comment by cormullion** [comment]
They ought to be there, I think:

https://glyphy.info/?s=double-struck

Does the notation of hex numbers change over 0xFFFF? I know that hex numbers higher than that sometimes do (depending on the context)…?

**Comment by djalbat** [comment]
A| very useful link, thank you! I can pad out my Unicode support now over time knowing that you support these characters.

It was indeed of course my error. To quote[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode):

`While there is a mathematical relationship between the supplementary code point value (e.g. 0x1F303) and both surrogate values that represent it (e.g., 0xD83C and 0xDF03), it does require an extra step to either calculate or look up the surrogate pair values every time a supplementary code point is to be used. For this reason, it's more convenient to use [String.fromCodePoint()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint), which allows for returning supplementary characters based on their actual code point value. For example, String.fromCodePoint(0x1F303) returns code point U+1F303 "Night with Stars".`

The solution is to use [String.fromCodePoint()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint).
