### ISSUE TITLE
Badly positioned diacritics in Latin Extended Additional block (1E00–1EFF)

### ISSUE THREAD

**Issue by kimmus** [cormullion/juliamono#178]
I have noted the following glyphs in Unicode block Latin Extended Additional (1E00–1EFF) in which diacritics are misplaced, in some cases grossly so (overlaying the base character):
JuliaMono Regular
1E38 1E39 1E5C 1E5D 1E68 1E69 1EAC 1EAD 1EB6 1EB7 1EC6 1EC7 

JuliaMono RegularItalic
1E38 1E39 1E5D 1E68 1E69 1EAD 1EB6 1EB7 1ED4 

JuliaMono Light
1E38 1E68 1EB6 1EB7 

BJuliaMono LightItalic
1E38 1E68 1EB7 1EBE 1EC0 1EC4 

JuliaMono Medium
1E38 1E39 1E5C 1E5D 1E68 1E69 1EAC 1EAD 1EB6 1EB7 1EC6 1EC7 

JuliaMono MediumItalic
1E38 1E39 1E5D 1E68 1E69 1EAD 1EB7 1EC6 1EC7 1ED4 

JuliaMono SemiBold
1E38 1E39 1E68 1E69 1EAC 1EAD 1EB6 1EB7 1EC6 1EC7 

JuliaMono SemiBoldItalic
1E38 1E39 1E5D 1E68 1E69 1EAD 1EB7 1EC6 1EC7 

JuliaMono Bold
JuliaMono BoldItalic

JuliaMono ExtraBold
1E38 1E39 1E5C 1E5D 1E68 1E69 1EAC 1EAD 1EB6 1EB7 1EC6 1EC7 

JuliaMono ExtraBoldItalic
1E38 1E39 1E5D 1E68 1E69 1EAD 1EB7 1EC6 1EC7 

JuliaMono Black
1E38 1E39 1E5C 1E5D 1E68 1E69 1EAC 1EAD 1EB6 1EB7 1EC6 1EC7

JuliaMono BlackItalic
1E38 1E39 1E5D 1E68 1E69 1EAD 1EB7 1EC6 1EC7 

Many other diacritics are poorly positioned—too close to their letters or to other diacritics, or unnecessarily far from them. The above are the most conspicuous.

**Comment by cormullion** [comment]
Hi! Thanks- what programming language/text environment/terminal are you using?

**Comment by cormullion** [comment]
Ah, I see what's happened with these - the software didn't propagate the masters correctly across all the instances:

<img width="392" alt="Screenshot 2023-07-08 at 07 52 58" src="https://github.com/cormullion/juliamono/assets/52289/2d2782ac-9137-49aa-a8fe-3c7c0ebae9fa">

**Comment by kimmus** [comment]
Should this issue not be marked as a bug? It’s about to go ‘stale’ otherwise.

**Comment by cormullion** [comment]
Hopefully these are mostly fixed. Please report any omissions. :)
