### ISSUE TITLE
Documentation of features?

### ISSUE THREAD

**Issue by kimmus** [cormullion/juliamono#179]
I may be dumb, but I can’t find any documentation of the ‘features’ like stylistics sets and ligatures. It’s not in the zip archive that contains the font files, and I can’t see it anywhere on Github. Could you post a link (and perhaps make it easier to find)?

**Comment by cormullion** [comment]
Hi! You can visit juliamono.netlify.com for some details. 

This repo has to be kept very small, I forget why now …  some kind of restriction when it’s cached by jsdelivr or cdnjs …

**Comment by kimmus** [comment]
Thank you!
