### ISSUE TITLE
Spanish ñ is skewed

### ISSUE THREAD

**Issue by miguelraz** [cormullion/juliamono#18]
This repo looks awesome! I just looked at the example on the website and the Spanish example contains an ñ whose "tilde"/vergulilla is skewed. 

I'm filing an issue as a responsible OSS person but have no idea how this fonts thing works. :D

**Comment by cormullion** [comment]
Hi Miguel! 

I'm seeing this:

<img width="293" alt="Screenshot 2020-08-07 at 08 50 38" src="https://user-images.githubusercontent.com/52289/89622576-26ba0380-d88b-11ea-940a-823e71ece6d1.png">

although after I fixed [this](https://github.com/cormullion/juliamono/issues/15) it's more like:

<img width="330" alt="Screenshot 2020-08-07 at 08 53 58" src="https://user-images.githubusercontent.com/52289/89622838-929c6c00-d88b-11ea-9cb4-99c9ce6b1522.png">

Are these skewed, or are you seeing something different? Are there Mexican tildes?

**Comment by miguelraz** [comment]
Looks better! Thanks for receiving the feedback!
I don't know where this becomes bikeshedding but the ~ could be a bit higher. See https://en.m.wikipedia.org/wiki/Ñ.
I also have not seen the Ñ yet, am afk atm.

**Comment by miguelraz** [comment]
Hey, late to the party but thanks for this!

**Comment by cormullion** [comment]
Cool - keep your eyes open for anything else!
