### ISSUE TITLE
Black Arrow issues

### ISSUE THREAD

**Issue by Logo121** [cormullion/juliamono#182]
Here's the black left, left-right and right arrow `⬅⬌➡` in JuliaMono:
![image](https://github.com/cormullion/juliamono/assets/21302803/2dcae9cc-012f-4fd2-927a-fbc90df1e565)

Black Right Arrow (U+27A1) is in a different block and is named slightly different compared to the others, but it *is* the right arrow version of the "Black Arrow" characters (which skips the right arrow):
![image](https://github.com/cormullion/juliamono/assets/21302803/59e891e3-2ef9-413b-9390-8ba5a88c1a8e)

Left-right arrow is just the left arrow again for some reason.

**Comment by cormullion** [comment]
Thanks! There are so many arrows in Unicode ... 😅

**Comment by Logo121** [comment]
![image](https://github.com/cormullion/juliamono/assets/21302803/b4ba5abd-780f-45da-9f43-23ec72fedc50)
Black Right Arrow is still thicker than the other black arrows?

**Comment by cormullion** [comment]
Ha ha, ok. I'll have another go some time.

**Comment by Logo121** [comment]
Seems to be fixed already, closing
