### ISSUE TITLE
Subscript i looks very similar to subscript 1, especially when bold

### ISSUE THREAD

**Issue by oxinabox** [cormullion/juliamono#184]
It isn't too bad at normal weight

![screen shot showing them at normal weigh](https://github.com/cormullion/juliamono/assets/5127634/3f39f868-cad8-4257-8b07-81e03715f54d)

but when you go to bold them:

![screen shot showing them in bold](https://github.com/cormullion/juliamono/assets/5127634/4bb6f621-f289-413a-89af-89f2b47f9a8a)

I suggest that removing the  slab serif (in particular at the top) from the subscript `i`, would fix this.
Though that would make it no longer look like full sized `i`.

I believe same issues apply to the superscript `i`

**Comment by cormullion** [comment]
I'll look at improving this in the next release (December-ish?). 

At small point sizes the pixels are getting clumsy and unpredictable:

![subscripts](https://github.com/cormullion/juliamono/assets/52289/3b758ae4-489b-4cd4-b21b-76dd652550a9)

and it can be difficult to predict exactly what will happen on different terminals, operating systems, etc.

The available weight range - Light/Regular/Medium/Semibold/Bold/Extrabold/Black - offers some room for tweaking, too...
