### ISSUE TITLE
Remove zip file from repository

### ISSUE THREAD

**Issue by bkmgit** [cormullion/juliamono#186]
Thanks for the fonts. Would you consider not having a zip file in the main repo, and linking to the latest release zip file instead or not packaging juliamono-ttf.zip in the release tar.gz file?

**Comment by cormullion** [comment]
Hi! Whar would be the pro's and con's of the removal?

**Comment by bkmgit** [comment]
Thanks for your response.
Pros:
- Lighter repository
- Zip file would not be duplicated in https://github.com/cormullion/juliamono/archive/refs/tags/v0.051.tar.gz or https://github.com/cormullion/juliamono/archive/refs/tags/v0.051.zip
Cons:
- May need to add a link if someone needs to download tar.gz file directly.

**Comment by cormullion** [comment]
Yes - reasonable (if not compelling). The main 'con' is that I'd have to change the way I upload stuff... I'll label this as 'enhancement'.
