### ISSUE TITLE
Set VendorID to corm

### ISSUE THREAD

**Issue by bkmgit** [cormullion/juliamono#187]
The VendorID in the font files should be set to corm rather than UKWN.  One can check the VendorID using [otfinfo](https://github.com/kohler/lcdf-typetools) and can update it using [FontForge](https://fontforge.org/en-US/), though other tools should work.  This could be done using CI when posting releases, or by building the ttf font files from source using CI.

**Comment by cormullion** [comment]
I added a VendorIdentification field, which appears as "Vendor ID":

<img width="1155" alt="Screenshot 2023-09-06 at 10 12 35" src="https://github.com/cormullion/juliamono/assets/52289/e2e67272-7d75-4de5-bb61-0172f9d2ef0d">

for the next release.
