### ISSUE TITLE
Pipe

### ISSUE THREAD

**Issue by ShalokShalom** [cormullion/juliamono#189]
Is there a specific reason, why there is no pipe ligature?

Considering it's a main part of the language.

**Comment by cormullion** [comment]
Which language?

**Comment by ShalokShalom** [comment]
Julia?

F#, Haskell, its the same pipe everywhere. 😃

**Comment by cormullion** [comment]
Ah, in that case, the standard pipe ligature in the `calt` set is suitable.

If you prefer a font with more ligatures, try [Fira Code](https://github.com/tonsky/FiraCode). By design, JuliaMono only has a few. 😀

**Comment by ShalokShalom** [comment]
And how to use the `calt` feature? 😃

**Comment by cormullion** [comment]
That very much depends on which OS, application, or editing environment you're using. I'm sure you can google for it.
