### ISSUE TITLE
A Julia way to install/update the font

### ISSUE THREAD

**Issue by xukai92** [cormullion/juliamono#19]
Just brainstorming: 
Does it make sense to make the font as a "Julia package" so that people can do `] add JuliaMono` to get the font?

**Comment by cormullion** [comment]
I think this might be possible. Although, writing scripts to install fonts on all possible OSs sounds like a fairly significant job, with good knowledge of OS-level scripting, security, etc... Obviously the Pkg wizards could do it, but I couldn't.

**Comment by simeonschaub** [comment]
It would be pretty easy to just put this font into a jll. That way, it should be pretty easy to embed, if you want to use it in GTK.jl, for example. At least on linux, you should then be able to just symlink that to `~/fonts` to install them on your system.

**Comment by simeonschaub** [comment]
PR for a jll here: JuliaPackaging/Yggdrasil#1433

**Comment by cormullion** [comment]
I'll watch with interest!

**Comment by simeonschaub** [comment]
You can find an initial prototype for the installer here: https://github.com/simeonschaub/JuliaMono.jl. Currently only works on Linux and I am still not sure, if that's really the correct way to do this, but it's a start.

**Comment by BeastyBlacksmith** [comment]
what about distributing it via homebrew?

**Comment by waldyrious** [comment]
> looks like it's in the process of being added

Actually, with the merge of https://github.com/Homebrew/homebrew-cask-fonts/pull/2290, it's already available for installation. One just needs to do:

    $ brew tap homebrew/cask-fonts
    $ brew cask install font-juliamono

**Comment by BeastyBlacksmith** [comment]
can confirm it works
