### ISSUE TITLE
≺ (`\prec`) hard to distinguish from less-than

### ISSUE THREAD

**Issue by simeonschaub** [cormullion/juliamono#190]
I found myself using this character (and some of its siblings like ≻ (`\succ`) and ≽ (`\succeq`)) in some more "mathy" Julia code and couldn't help but wonder whether it might be possible to make them a little more distinct from their non-curvy counterparts.

I do realize this is a lot to ask for at typical coding font sizes and the current state is far from unreasonable. Taking https://www.cmor-faculty.rice.edu/~heinken/latex/symbols.pdf as a reference, LaTeX's curves look like they stay together a little longer and then get more exaggerated towards the opening instead.

#### JuliaMono:

![image](https://github.com/cormullion/juliamono/assets/5220528/9dcb3e6b-8332-43cd-af8f-96153be72b34)

#### The above LaTeX example for comparison:

(LaTeX of course gets away with using much thinner weights)

![image](https://github.com/cormullion/juliamono/assets/5220528/f23d460e-4243-4199-9a84-264342d92d35)

<details>
<summary>Julia code to generate</summary>

```julia
julia> using REPL

julia> filter(kv -> startswith(kv[1], r"\\succ|\\prec"), REPL.REPLCompletions.latex_symbols) |> sort!∘collect∘values |> x -> join(stdout, x, " ")
≺ ≻ ≼ ≽ ≾ ≿ ⋨ ⋩ ⪯ ⪰ ⪱ ⪲ ⪳ ⪴ ⪵ ⪶ ⪷ ⪸ ⪹ ⪺
```

</details>

**Comment by cormullion** [comment]
Good idea. Something like this perhaps?

<img width="713" alt="Screenshot 2023-10-17 at 11 29 03" src="https://github.com/cormullion/juliamono/assets/52289/c43d2142-1b5a-4a58-ad1f-e597925e9c8a">

**Comment by simeonschaub** [comment]
That looks awesome! 😍

One tiny thought, feel free to ignore, but would it be possible to make them a little larger as well or is this already the limit you would reasonably go? I'd argue that unlike the regular equality operators which occur in code frequently and therefore need to blend in, these have some more license to stick out because usually something non-standard is going on. I'm not a designer though, so this line of reasoning might not make much sense in a more general purpose font design context

**Comment by cormullion** [comment]
Yes, it’s tricky. Although these are Unicode characters, they’re not well suited to go in a monospaced font, because all glyphs all have to have the same width - they can be taller of course. If they were much wider they’ll either be truncated or start overlapping their neighbours, depending on which terminal/IDE you’re using - “unwanted ligatures” perhaps 😀

**Comment by simeonschaub** [comment]
Yeah, that makes a lot of sense. There probably isn't that much room to go a lot taller here either since that will interfere for the stacked variants. I'll be perfectly happy with the tweaks you showed above already, so please go ahead

**Comment by anderslundstedt** [comment]
> Good idea. Something like this perhaps?
> 
> <img alt="Screenshot 2023-10-17 at 11 29 03" width="713" src="https://user-images.githubusercontent.com/52289/275801679-c43d2142-1b5a-4a58-ad1f-e597925e9c8a.png">

Am I missing something or does `≼` (u+227c) and `≽` (u+227d) each occur twice here, where each second occurrence is slightly lower?

Personally I think I would prefer the not so heavily stacked signs `≤`, `≥`, `≺`, `≻`, `≼`, `≽`, `≾`, `≿` to have their “sharp point” at the same height as those of `<` and `>`—but I have barely thought this through so their might very well be some good reason against that. That said, I think all these already look perfectly alright in JuliaMono 0.051:

<img width="434" alt="Screenshot 2023-10-19 at 09 01 13" src="https://github.com/cormullion/juliamono/assets/4514101/d2d92d6e-d345-4874-a96a-835d9b809b61">

**Comment by cormullion** [comment]
no, you're not missing anything 😀 the attempt at a redesign of U+227C involved making the `<` curve more but then having to move the single line to be a straight line below since I couldn't work out how to make it look right. Thus it looks like the U+2aaf version (which I'm guessing has the same meaning...).

**Comment by CameronBieganek** [comment]
> the attempt at a redesign of U+227C involved making the `<` curve more but then having to move the single line to be a straight line below (like the U+2aaf version (which I'm guessing has the same meaning...) since I couldn't work out how to make it look right with the curve

Here's an example from Menlo that seems to work pretty well:

<img width="200" alt="image" src="https://github.com/user-attachments/assets/ffd2eece-652d-42ab-9936-6847d9cfd5b1">
