### ISSUE TITLE
small case "r" looks wierd

### ISSUE THREAD

**Issue by lakshits11** [cormullion/juliamono#191]
Every other letter is PERFECT except smallcase r. Maybe the slab on r can be removed?
You can try adding variations to each letter such as Iosevka. 

Other than that, I greatly appreciate your font.

<img width="714" alt="image" src="https://github.com/cormullion/juliamono/assets/54276661/7f87b85c-554d-4cb7-b1a2-d01c56ad221d">

You can see here the "r" feels different from other letters.

**Comment by anderslundstedt** [comment]
The stylistic set with feature code `ss10` gives you an alternate ‘r’.

**Comment by cormullion** [comment]
Thanks! Mostly perfect is very good to hear ... :) 

The reason for the serifs on "r" is usually to add a bit of extra width for this very narrow letter - the big problem with monospaced fonts is that all the letters have to occupy the same width.  So "i", "l", and "r" are often made wider, using serifs, to compensate for their narrowness. I think narrow fonts like Iosevka can leave the serifs off easier than wider fonts.

<img width="893" alt="Screenshot 2023-10-25 at 09 40 22" src="https://github.com/cormullion/juliamono/assets/52289/0c3788ac-fbae-4ca8-9add-d80113bbae40">

A base serif is quite common, but then you might see problems if the "i" and "r" both have very similar designs and heavily depend on the dot to make them different.
