### ISSUE TITLE
Glyph shape of 2 Cyrillic Ext-C characters (U+1C81, U+1C85)

### ISSUE THREAD

**Issue by Logo121** [cormullion/juliamono#193]
Comparison with EversonMono (bottom):
![image](https://github.com/cormullion/juliamono/assets/21302803/469919cc-0826-49c4-838f-812f184a8080)

U+1C81 (CYRILLIC SMALL LETTER LONG-LEGGED DE) is a variation of cyrillic de with longer "legs", which in JuliaMono they are actually shorter.  
(There are no specification on how long they should be, but I guess it is good enough to align them with `pq`?)

U+1C85 (CYRILLIC SMALL LETTER THREE-LEGGED TE) is a variation of cyrillic te with three legs, which in JuliaMono it is just "CYRILLIC SMALL LETTER THREE-LEGGED".

**Comment by cormullion** [comment]
Thanks. Will be fixed in next release.

**Comment by Logo121** [comment]
![image](https://github.com/cormullion/juliamono/assets/21302803/455b40a7-5755-4ada-9aae-a7b7519ea83d)

the alignment looks weird but eh, fixed enough for me.
