### ISSUE TITLE
Unpaired parentheses in CHANGELOG.md

### ISSUE THREAD

**Issue by muzimuzhi** [cormullion/juliamono#194]
Current https://github.com/cormullion/juliamono/blob/master/CHANGELOG.md#v0052---2023-11-30
> ## [v0.052] - 2023-11-30
> 
> ### Added
> 
> -  (U+F35D) Private Use Area: external link icon: this popular never quite made it into Unicode (proposal [here](https://www.unicode.org/L2/L2018/18303-external-link.pdf) but it's useful 

Expected, added right parentheses right after "(proposal here"

> ## [v0.052] - 2023-11-30
> 
> ### Added
> 
> -  (U+F35D) Private Use Area: external link icon: this popular never quite made it into Unicode (proposal [here](https://www.unicode.org/L2/L2018/18303-external-link.pdf)) but it's useful 

Not sure if it's allowed to update CHANGELOG entries for released versions.

```diff
From c5f46be11e4b8c8fd224edc1625da39ae86f8dee Mon Sep 17 00:00:00 2001
From: Yukai Chou <muzimuzhi@gmail.com>
Date: Sat, 2 Dec 2023 15:50:03 +0800
Subject: [PATCH] fix typo in CHANGELOG.md

---
 CHANGELOG.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/CHANGELOG.md b/CHANGELOG.md
index bd557b5..75d1943 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -6,7 +6,7 @@
 
 ### Added
 
--  (U+F35D) Private Use Area: external link icon: this popular never quite made it into Unicode (proposal [here](https://www.unicode.org/L2/L2018/18303-external-link.pdf) but it's useful 
+-  (U+F35D) Private Use Area: external link icon: this popular never quite made it into Unicode (proposal [here](https://www.unicode.org/L2/L2018/18303-external-link.pdf)) but it's useful 
 
 - added mirrored versions of the non-mirrorable glyphs for BiDi (ie right-to-left): ⅀, ∁, ∂, ∃, ∄, ∑, ∖, √, ∛, ∜, ∝, ∦, ∫, ∬, ∭, ∮, ∯, ∰, ∱, ∲, ∳, ∹, ∻, ∾, ∿, ≀, ≁, ≂, ≄, ≆, ≇, ≈, ≉, ≊, ≋, ≟, ≠, ≢, ⊌, ⊧, ⊪, ⊬, ⊭, ⊮, ⊯, ⊾, ⊿, ⋵, ⋸, ⋹, ⋿, ⌠, ⌡, ⟀, ⟌, ⟓, ⟔, ⦜, ⦝, ⦞, ⦟, ⦢, ⦦, ⦧, ⧂, ⧃, ⧉, ⧎, ⧜, ⧡, ⧣, ⧤, ⧥, ⧴, ⧶, ⧷, ⨊, ⨋, ⨌, ⨍, ⨎, ⨏, ⨐, ⨑, ⨒, ⨓, ⨔, ⨕, ⨖, ⨗, ⨘, ⨙, ⨚, ⨛, ⨜, ⨞, ⨟, ⨠, ⨡, ⨤, ⨦, ⨩, ⨾, ⩗, ⩘, ⩪, ⩫, ⩬, ⩭, ⩯, ⩰, ⩳, ⩴, ⪣, ⫝̸, ⫢, ⫦, ⫳, ⫻, ⫽, 𝛛, 𝜕, 𝝏, 𝞉, 𝟃 (issue #192)
 
-- 
2.43.0

```

**Comment by cormullion** [comment]
Hi! Thanks. The CHANGELOG has no technical or official status, it's just something that some folks (and me) might find useful occasionally. I'll add a parenthesis next time I update it.

**Comment by kimmus** [comment]
Should it not read ‘this popular character’ or some such?

**Comment by cormullion** [comment]
It should. I must have typed that line at the end of the day...😴
