### ISSUE TITLE
Daggers too similar?

### ISSUE THREAD

**Issue by anderslundstedt** [cormullion/juliamono#198]
Thanks for a nice and extremely useful font!

I think it would be nice if the double dagger U+2021 `‡` would be more distinguishable from the dagger U+2020 `†`—similar to how the triple dagger U+2E4B `⹋` is clearly distinguishable from the dagger:

<img width="359" alt="Screenshot 2023-12-31 at 00 06 04" src="https://github.com/cormullion/juliamono/assets/4514101/52dda302-b1c9-434b-94d0-33e9d0b04d07">

If a change is made, I would not complain if the PUA superscripts variants U+F0086 and U+F0087 would be similarly changed.

<img width="352" alt="Screenshot 2023-12-31 at 00 09 27" src="https://github.com/cormullion/juliamono/assets/4514101/aa97a8e8-2b62-4862-a4e2-ebe286165e00">

(And I would definitely not complain about the addition of a PUA superscript triple dagger.)

Happy new year!

**Comment by cormullion** [comment]
Good idea! The current one looks ineffective as a dagger anyway, so perhaps using a less literal design is the way to go. I think some fonts just join two daggers end to end, perhaps that works. The triple dagger 2E4B is obviously not dangerous, unless it's thrown at your enemy.

**Comment by anderslundstedt** [comment]
Looks great!
