### ISSUE TITLE
Windows 10 - not valid font files

### ISSUE THREAD

**Issue by hearnsj** [cormullion/juliamono#2]
When dropping these fonts into the Fonts folder on Windows 10 I get a message that they are not valid font files.
The file browser identifies them as OpenType font file

Happy to run any tests if you make any changes.

**Comment by cormullion** [comment]
Sounds fun... :) Which files did you drop?

**Comment by cormullion** [comment]
I don't have Windows, but there seem to be a few general workflow errors that people report. Eg:

![b3e2dce5d6cd8f8d16f7a634455098a970ef1b8f](https://user-images.githubusercontent.com/52289/88689790-d4424f80-d0f2-11ea-919a-a114a45381eb.png)

I'll see if I can find anything else to test...

**Comment by hearnsj** [comment]
I will repeat the font addition - but as Administrator

**Comment by RoyiAvital** [comment]
If you have Linux it is really easy to have Windows on VM. Maybe a way to solve the Windows issues?

**Comment by hearnsj** [comment]
I downloaded the fonts as a zip file. Unpacked the files and installed each one. Worked fine.
Please close this issue!

**Comment by cormullion** [comment]
Thanks so much John - you can join in the other issue now because it doesn't look so good on Windows... :)
