### ISSUE TITLE
Mystery spacing issues

### ISSUE THREAD

**Issue by GanerCodes** [cormullion/juliamono#203]
Alright so I've been absolutely beaned by the following issue:
99% of everything works fine. Not problems at all. 
_however_
There are a few random spacing issues that I cannot figure out what the issue is. Characters like 〚〛❴❵➰ when in my various editors likes to:
1. Be double width, hugging the left side (similar to how emojis work from other fonts)
![image](https://github.com/cormullion/juliamono/assets/34655998/2a879501-23a8-4a9f-ac84-0128a7161aef)
2. Render fine, however breaks vertical traversal 
![image](https://github.com/cormullion/juliamono/assets/34655998/be2798b4-9536-4548-b2d9-3e801e38b6b8)

i have spent hours messing with fontforge, fontconfig, etc etc etc and I cannot for the life of me understand this. Please help

**Comment by cormullion** [comment]
Hi. Any idea what version?  (Look at glyph U+E843.) That vertical bar looks very short to me 🤔. Editor or terminal? 

Difficult to reproduce or diagnose until there's more information...

**Comment by GanerCodes** [comment]
> Hi. Any idea what version? (Look at glyph U+E843.) That vertical bar looks very short to me 🤔. Editor or terminal?
> 
> Difficult to reproduce or diagnose until there's more information...

Latest release (0.054), also the bar is ∣ not | my bad

Both vscodium and st terminal, im sure other things too but those are the ones I use

**Comment by cormullion** [comment]
Interesting...

As a precaution, please delete JuliaMono-RegularLatin.ttf and JuliaMonoBold-Latin.ttf from your system. These are restricted to a basic Latin character set and only have 330 glyphs. Sometimes these get picked up by mistake by applications and as a result fallback fonts are used extensively. 

At first I thought you were typing the mathematical left bracket U+27E6 (⟦) but I see now that you're typing the CJK left bracket U+301A (〚) which as you can already see (at least on github) has a double-spacing effect in some fonts. But in JuliaMono-Regular these glyphs are the same width. 

Here's FontGoggle's breakdown of `⟦⟧〚〛❴❵`:

<img width="1556" alt="Screenshot 2024-03-24 at 09 41 15" src="https://github.com/cormullion/juliamono/assets/52289/a6011c28-d96f-433f-afb2-e8cf44461718">

So design-wise these glyphs are the same width, and should be behaving normally. The question is why they're being treated as double-space CJK.

**Comment by GanerCodes** [comment]
Yep it still happens (only had JuliaMono-Regular.ttf enabled anyway).  is normal as well.
The following are more problem-characters: "✣➡❗♯⚇✓✗"

The existence of mathematical left/right bracket is useful as well btw thanks

**Comment by cormullion** [comment]
Well ❗ is also an emoji, like a smiley, so some applications will set it wider (double width), others won't, if a single-width glyph is present in the font (JuliaMono has a version of this glyph).

For example: VSCodium editor:

<img width="337" alt="Screenshot 2024-03-25 at 09 40 28" src="https://github.com/cormullion/juliamono/assets/52289/01b469fc-a585-4f19-9fe3-88cb84844434">

VSCodium terminal:

<img width="393" alt="Screenshot 2024-03-25 at 09 41 03" src="https://github.com/cormullion/juliamono/assets/52289/ffc70af9-dfdf-421b-9248-47f18bf1d835">

I can't reproduce any errors with the other characters - "✣➡♯⚇✓✗" - though.

It would probably be better for your use case if you used fonts like FiraCode, JetBrains, or Plex Mono - these have fewer glyphs and the behaviour of the fallback mechanism for emoji-like characters will be easier to predict.
