### ISSUE TITLE
Interrobang glyph is incorrect

### ISSUE THREAD

**Issue by Timwi** [cormullion/juliamono#204]
Hi! Currently using JuliaMono version v0.054.

The ‪INTERROBANG character (U+203D) has the wrong glyph. It is using the glyph for U+2049 (EXCLAMATION QUESTION MARK).

The INVERTED INTERROBANG (U+2E18) is correct, so a possible fix would be to just use that one and turn it 180°.

**Comment by cormullion** [comment]
I originally went for this design (rather than the [others](http://shadycharacters.co.uk/2017/09/miscellany-81-interrobang-taxonomy/) because it was much better for legibility on lower-resolution screens. This stays distinct long after the 'closed' variants have turned into blurry question marks or odd-looking 'P's. The closed variant seems to work better in graphic design contexts, and logos, rather than in code.

I could make a `cvxx` character variant option to allow a different variant. Or change it, if there's enough enthusiastic support...

**Comment by Timwi** [comment]
The blog entry you linked to sure does list a number of possible variants.

However, the shape that the character has at the moment is not what most people associate as the “interrobang”. In fact, it is indistinguishable from U+2049 (EXCLAMATION QUESTION MARK) and inconsistent with U+2E18 (INVERTED INTERROBANG).

I’m trying hard to avoid telling you what to do, as this is your font and your creative decision, and I love the font no matter what you do. Despite, some possible suggestions I might have include:

* Keep the general design but make it sufficiently different from U+2049 and change U+2E18 to an upside-down version of it.
* Change it to a more “typical” shape of an interrobang but encourage people to use U+2049 instead (e.g. by changing the example on the homepage).
* Change it to a more “typical” shape of an interrobang and make a `cvxx` character variant option for the current design.

**Comment by cormullion** [comment]
I changed them:

<img width="827" alt="Screenshot 2024-04-10 at 15 36 44" src="https://github.com/cormullion/juliamono/assets/52289/974a73c1-ac5e-4e7b-9f23-6a67f551d62a">

**Comment by cormullion** [comment]
>(Can’t see a new release yet, I assume that’s coming soon)

A few weeks perhaps ... I try not  to release too often - otherwise people just get fed up with upgrades... :)

**Comment by Timwi** [comment]
Perfectly understandable. There’s no rush! Thank you so much for your amazing work!!

**Comment by anderslundstedt** [comment]
> > (Can’t see a new release yet, I assume that’s coming soon)
> 
> A few weeks perhaps ... I try not to release too often - otherwise people just get fed up with upgrades... :)

I always enjoy when there is a new release! I would not mind more frequent releases :)

(Of course, I have no complaints with the current frequency of releases.)
