### ISSUE TITLE
Possible alternate variant of small letter "l" with stylistic set?

### ISSUE THREAD

**Issue by Xenapte** [cormullion/juliamono#205]
Hi! I was trying to switching my font from Fira Code to Julia Mono since the latter has italic variants, and I must say it's a really fantastic font.

However, the only thing that bothers me is that I feel the bottom of small letter `l` is a little too curly and personally, I don't find it harmonizing with the rest. I understand that this was done to make the letter wider and many people prefer this style, but I think it would be better if you could add a variant of `l`, where the strokes are straight and a horizontal bar is used to stretch the width instead, just like the bottom part of `i`. This is possible with Fira Code so I enabled it while I was using it.

![](https://github.com/cormullion/juliamono/assets/17661805/dcefd601-b66e-422f-a17c-84a8ed6a04a9)

**Comment by cormullion** [comment]
Hi! it's easy to add a `cv..` for that!

 I think the main reason for the current design is just to keep it as different as possible from `1` and `I`  - it's easy to confuse `1`,`l`, and `I` otherwise.

**Comment by Xenapte** [comment]
Thanks! I know this is done to keep glyph shapes distinct - I think I've seen this reasoning in other fonts too, but I do like the straight variant (maybe because I'm just too used to seeing it as it is used in many popular monospaced fonts?)

Anyways a style variant would be much appreciated and thanks again for the efforts!

**Comment by cormullion** [comment]
It could look like this:

<img width="142" alt="Screenshot 2024-03-31 at 16 28 08" src="https://github.com/cormullion/juliamono/assets/52289/43e96b7b-3a45-495c-9584-a538af18b882">

If you're able to try out an environment that allows you  to select `cv04`, you could try it out: 

[jm-cv04.zip](https://github.com/cormullion/juliamono/files/14816517/jm-cv04.zip)

**Comment by Xenapte** [comment]
> It could look like this:
> <img alt="Screenshot 2024-03-31 at 16 28 08" width="142" src="https://private-user-images.githubusercontent.com/52289/318281735-43e96b7b-3a45-495c-9584-a538af18b882.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjI3NjIsIm5iZiI6MTcxMTk2MjQ2MiwicGF0aCI6Ii81MjI4OS8zMTgyODE3MzUtNDNlOTZiN2ItM2E0NS00OTVjLTk1ODQtYTUzOGFmMThiODgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA5MDc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNGFkNjYxNjRmNTljMjYyNzRkZDYwOTAwZmQ3YTllNWYzOWViOTZiODRiMzg2MTAzMjA1NjEyYTA2YzY1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-pMCA54dC5iFTklKKHMsoc_ys1Y2rUEAi_8RO_-a6P8">
> 
> If you're able to use an environment that allows you to select `cv04` (such as VSCode), you could try it out:
> 
> [jm-cv04.zip](https://github.com/cormullion/juliamono/files/14816517/jm-cv04.zip)

This is absolutely a joy to use, thanks for taking care of my quirks on stylistic choices! Currently the only issue I see is the gap between the `lt` digraph being kinda too wide, but I get that *we can't do kernings on a monospaced font* ([issue #123](https://github.com/cormullion/juliamono/issues/123#issuecomment-1007984422)), so guess I have to get used to it :)
![L3PO`V4J3X1UXG`((PXJ_1M](https://github.com/cormullion/juliamono/assets/17661805/3bbb755b-8bdc-4c45-a541-d0403790ea1d)


Btw I don't know if it's time for me to close this issue - maybe you wanna tweak it more before finalizing?

**Comment by cormullion** [comment]
Yes,I can (just) see what you mean - we might be getting close to optical illusion/antialiasing/rendering differences. Perhaps the asymmetry of the two letters (more weight on one side than the other) contributes to the perception of a gap...

After a tiny tweak, here's a comparison with SF Mono and Fira Mono:

<img width="682" alt="Screenshot 2024-04-01 at 16 53 52" src="https://github.com/cormullion/juliamono/assets/52289/a1b00bb1-f551-464b-9066-e2c6fa5c832b">

I'm not planning on another release just yet, though. Can leave this open until then.

**Comment by Xenapte** [comment]
Alright, I see it.

**Comment by singularitti** [comment]
> I get that _we can't do kernings on a monospaced font_

See [this comment](https://github.com/cormullion/juliamono/issues/123#issuecomment-2094964917).

**Comment by singularitti** [comment]
Hi, I tried to turn `cv04` on in VSCode but nothing seems to be different in `l`, am I doing it wrong? Here's my settings:

```json
"editor.fontFamily": "JuliaMono",
"editor.fontLigatures": "'ss05', 'ss07', 'ss09', 'ss12', 'ss14', 'ss15', 'ss16', 'ss17', 'cv02', 'cv03', 'cv04'"
```

**Comment by Xenapte** [comment]
> Hi, I tried to turn `cv04` on in VSCode but nothing seems to be different in `l`, am I doing it wrong? Here's my settings:
> 
> ```json
> "editor.fontFamily": "JuliaMono",
> "editor.fontLigatures": "'ss05', 'ss07', 'ss09', 'ss12', 'ss14', 'ss15', 'ss16', 'ss17', 'cv02', 'cv03', 'cv04'"
> ```

It is a test feature not released yet:

> [jm-cv04.zip](https://github.com/cormullion/juliamono/files/14816517/jm-cv04.zip)

**Comment by singularitti** [comment]
OK, thanks. I saw it in the [CAHNGELOG of v0.055](https://github.com/cormullion/juliamono/blob/4c267272a8bf299156b1c5785117ff121be80946/CHANGELOG.md?plain=1#L11). Maybe we should remove it and put it in the next release?

**Comment by cormullion** [comment]
It's working for me.

<img width="715" alt="Screenshot 2024-05-06 at 09 23 52" src="https://github.com/cormullion/juliamono/assets/52289/0c7ca149-c8ad-4a46-b232-5744e0e96cbe">

The OS caches fonts very 'assertively', sometimes it's difficult to get it to let go of previous versions. While I don't think you have to reboot to zap the font caches, certainly deleting the fonts before installing a newer version is helpful...

**Comment by singularitti** [comment]
I don't know then... I tried to zap the old font completely and reinstall via Homebrew, then reboot. But it is still the old style. I tried `jm-cv04.zip` and it works. Could @Xenapte confirm this work for you? Thank you!

**Comment by Timwi** [comment]
Is there a way to force cv04 using pyftsubset? I tried `--layout-features+=cv04` and `--layout-features=cv04` but neither seemed to replace the `l` character. I also tried `ss10` to get the alternate `r` but to no avail.

**Comment by Xenapte** [comment]
> I don't know then... I tried to zap the old font completely and reinstall via Homebrew, then reboot. But it is still the old style. I tried `jm-cv04.zip` and it works. Could @Xenapte confirm if this works for you? Thank you!

Latest release (0.055) works for me. Maybe it's a homebrew issue and you need to just try downloading from here directly

**Comment by Xenapte** [comment]
> Is there a way to force cv04 using pyftsubset? I tried `--layout-features+=cv04` and `--layout-features=cv04` but neither seemed to replace the `l` character. I also tried `ss10` to get the alternate `r` but to no avail.

pyftsubset doesn't work with stylistic sets. It only supports features covered by running `pyftsubset --layout-features=?`.

If you want to use python fonttools to freeze stylistic sets, you need to [write your own code to do that](https://typedrawers.com/discussion/4443/enabling-stylistic-sets-e-g-ss02-with-fonttools). Or just use a different tool.

**Comment by Timwi** [comment]
Thanks! Based on your link, I found the tool `pyftfeatfreeze` that can do this. It works perfectly for `ss01` (alternate g), `ss06` (simple a), and `cv04` (alternate l). However, it does not appear to do anything for `ss10` (alternate r). Could this be a problem with the font file? I notice that the tool doesn’t complain if I specify a completely invalid feature code.

**Comment by Xenapte** [comment]
> Thanks! Based on your link, I found the tool `pyftfeatfreeze` that can do this. It works perfectly for `ss01` (alternate g), `ss06` (simple a), and `cv04` (alternate l). However, it does not appear to do anything for `ss10` (alternate r). Could this be a problem with the font file? I notice that the tool doesn’t complain if I specify a completely invalid feature code.

Some relevant issues I found there:
- [fonttools-opentype-feature-freezer#12](https://github.com/twardoch/fonttools-opentype-feature-freezer/issues/12)
- [fonttools-opentype-feature-freezer#20](https://github.com/twardoch/fonttools-opentype-feature-freezer/issues/20)

I don't really know if this is an issue of the `pyftfeatfreeze` tool or the font itself based on my limited knowledge.

**Comment by cormullion** [comment]
You could try

https://mutsuntsai.github.io/fontfreeze/

to lock features in. 

I found another computer, and installed vs-code, wezterm, kitty, and the latest release of JuliaMono, and everything worked as documented…. 🤔

(wezterm has a configuration quirk - it needs ‘assume_emoji_representation=false’ although I don’t think it should)
