### ISSUE TITLE
Problem with CJK glyphs

### ISSUE THREAD

**Issue by Xenapte** [cormullion/juliamono#206]
Hi! Sorry for bothering you again but I believe this is an actual issue that need fixing, more so than my previous one (which is purely personal preference).

Currently JuliaMono includes the CJK character '点' (U+70B9), possibly in line with the symbols of ㍘ to ㍰ (used in Chinese for hours of the day, but I don't think I've ever seen them in use). However this makes the font look quite awkward with CJK texts containing the glyph (which is pretty common in both Chinese and Japanese):
![](https://github.com/cormullion/juliamono/assets/17661805/1008865e-6165-4365-9a03-58dafd9fb4bb)

We can't use a fallback font here as virtually all CJK fonts have their own sets of basic Latin symbols too, so they would take precedence when placed in front of JuliaMono.

I think this can be solved by either removing these glyphs or setting them to double width (which is customary with CJK monospace fonts).

PS. after uploading this image I've noticed that the font includes CJK punctuations which normally should also be full-width (example: U+FF0C '，'), so maybe these need fixing too.

**Comment by cormullion** [comment]
Thanks! I don’t know about this area of monospaced font design, (I just added some that I found interesting) so I’m more than happy to delete glyphs that shouldn’t be there. Do you think you could make a list of glyph unicodes to be removed? No worries if not, I can make a guess. 😀

**Comment by Xenapte** [comment]
Alright, I haven't used JuliaMono with CJK text much - normally I'd prefer using code/documentation purely in English, but I do need to write a Chinese document on this specific instance, so I'll make my **guess** here too after some look with Fontforge :)

Glyphs that definitely need removal:
- Chinese hour symbols 3358-3370
- CJK characters U+534D, U+70B9

Glyphs that *don't really need* to be removed if you can make them full-width instead (if not then I think removing them is better):
- CJK Symbols and Punctuation, Hiragana, Katakana 3000-30FF
- Vertical Forms FE10-FE1F
- CJK Compatibility Forms FE30-FE4F
- Full-width symbols in FF00-FFEF (note that some glyphs in this range are half-width, so don't remove / set full-width all of them too quickly)

Other glyphs that I'm not sure:
- U+3297 '㊗', U+3299 '㊙' - maybe these can be kept for the consistency with other circled characters?
- Hexagrams 4DC0-4DFF - these are just too cool to be removed, so I'd guess either keeping them or making them full-width instead

![](https://github.com/cormullion/juliamono/assets/17661805/7c747e8b-7bfa-440e-947b-a077d1d4f082)
The full range of CJK glyphs in JuliaMono, excluding some glyphs near the end of the Basic Multilingual Plane. Originally I was going to say removing all of them, but apparently they've put some other good symbols there too.

**Comment by cormullion** [comment]
Thanks so much! I’ll make these removals for the next release. 

Obviously it’s not possible to change any widths - if the glyphs in a font don’t all conform to the same width, the font will fail the tests for being monospaced.

**Comment by Xenapte** [comment]
Hey I think this issue still exists in the newest version. Some glyphs in the U+3000 - U+30FF range weren't deleted including some very frequently used punctuations (so they really mess up the formatting):

- U+3001 `、` CJK comma
- U+3002 `。` CJK period / full stop
- Some quotation marks/brackets which all fall in that range

Sorry for the late reply, although I speak CJK languages I don't usually write/read documents (especially software documents using a monospace font) in them a lot. I can help you look through the current font again if you like.

Don't know if this is the correct place for as this issue's been closed. I can turn this into a new one if needed (or if no one replies).

**Comment by Xenapte** [comment]
Seems fixed.
