### ISSUE TITLE
Take down the "JuliaMono julia manual" since it pollutes google search?

### ISSUE THREAD

**Issue by KristofferC** [cormullion/juliamono#207]
I am seeing references to for example https://cormullion.github.io/assets/images/juliamono/juliamanual/manual/parallel-computing.html from google which I guess is not intended. Maybe this could be taken down or alternatively be made not to be indexed by search engines.

**Comment by cormullion** [comment]
Good idea.  

Can't do anything about google though...

**Comment by cormullion** [comment]
Deleted in https://github.com/cormullion/cormullion.github.io/commit/f2e3fe51ebaeb9ad7da4cb20eb4c570388d7d0d0

**Comment by KristofferC** [comment]
Google should update in time.
