### ISSUE TITLE
Unintentional missing glyphs in v0.055?

### ISSUE THREAD

**Issue by moble** [cormullion/juliamono#208]
Thank you so much for this font, I absolutely love it.  I love it so much, in fact, that I installed the newest version yesterday (the day it come out).  But this morning I tried actually using it and found that there were some problems.  I see that you removed some glyphs, but these are things like `\vec`, `\alpha`, `\bfk`, `\scrT`, `\prime`, `\_j`, and maybe even just `j`.  I've tested this repeatedly by uninstalling and reinstalling the font, restarting VS Code and Emacs, and even my laptop in between, and the results are consistent.

I'm on macOS (Sonoma 14.4.1).  Here's what it looks like in both VS Code (updated right now) and VS Code Insiders (updated right now), when I remove JuliaMono from Font Book, then reinstall either 0.054 and restart VS Code

<img width="906" alt="JuliaMono_VSCode_054" src="https://github.com/cormullion/juliamono/assets/1470769/5a8d3692-e558-47ff-97c3-5fc5d29665f3">

or remove then reinstall 0.055 and restart VS Code

<img width="917" alt="JuliaMono_VSCode_055" src="https://github.com/cormullion/juliamono/assets/1470769/6820c68b-138e-4704-90a7-55570cc49b54">

That's a lot of different glyphs, but obviously the biggest problems are the "NOGLYPH" blocks where `\vec` and `\bfk` should be showing up.  In fact, now that I look at this, it looks like the `j` and `\scrT` that show up for 0.054 weren't right either?

(Note that `\eth` has never successfully combined with `\bar`, which is hidden by the `\^2` here, but is also offset when they're just on their own.  I might open another issue for that...)

I also checked what things look like in Emacs 29.3 with 0.054

<img width="643" alt="JuliaMono_Emacs_054" src="https://github.com/cormullion/juliamono/assets/1470769/f63ff021-3507-4a05-99cb-92a859c3b6b3">

and with 0.055

<img width="648" alt="JuliaMono_Emacs_055" src="https://github.com/cormullion/juliamono/assets/1470769/54c8c1b0-7dc7-4dad-acf4-d4f561282a41">

Note that I really didn't change any settings in between restarting things, but the line spacing here is also clearly different.  Also, the `\vec` and `\bfk` do show up in Emacs, but apparently not correctly for 0.055.  (And, interestingly, `\eth\bar` works in both cases for Emacs.)

**Comment by cormullion** [comment]
Perhaps you could upload a text file here containing the code you've typed, and I can see what it looks like... ?

**Comment by moble** [comment]
Oh, sure.  It's not yet public code but here's that snippet:


```julia
        @threads for j ∈ eachindex(𝒯.R)
            Rⱼ = 𝒯.R[j]
            αⱼ = real(𝒯.α[j])
            ð̄²α = real(𝒯.ð̄²α[j])
            κ⁻¹ = γ * (1 - v⃗ ⋅ Rⱼ(𝐤))
            spline = @view 𝒯.splines[:, :, j]
            guess = firstindex(𝒯.u)
            for (i, u′) ∈ enumerate(𝒯.u′)
                u = κ⁻¹ * u′ + αⱼ
                d, guess = interpolate(𝒯.u, 𝒯.h, spline, u, guess)
                𝒯.d′[j,i] = κ⁻¹ * (d - ð̄²α)
            end
        end
```

(Also, [here](https://gist.github.com/moble/5fb4d89c2d3d04d065af85104c1c7d87) as a gist for no reason.)

**Comment by cormullion** [comment]
On my Mac (Ventura 13.6)

VSCode:

<img width="816" alt="Screenshot 2024-05-06 at 18 53 11" src="https://github.com/cormullion/juliamono/assets/52289/10d999f0-86ea-4b75-a571-b648db61760a">

Terminal (Vim):

<img width="794" alt="Screenshot 2024-05-06 at 18 52 37" src="https://github.com/cormullion/juliamono/assets/52289/b048fcc6-d6ed-40f0-b1b8-5b53dd28dead">

Cot editor:

<img width="999" alt="Screenshot 2024-05-06 at 18 47 00" src="https://github.com/cormullion/juliamono/assets/52289/450ac5df-b1d4-4c7b-95dc-798d36b60a7a">

Wezterm (Helix):

<img width="1134" alt="Screenshot 2024-05-06 at 19 10 40" src="https://github.com/cormullion/juliamono/assets/52289/3a204499-b184-49d7-b764-2417deb085bd">

I'd say VSCode is struggling a little, but mostly they look OK. As you probably know, not all terminals can render every possible glyph composition correctly... 

Just to be on the safe side, make sure you delete all JuliaMono.*Latin.ttf files - these occasionally slip into play by accident and can confuse the unwary with the sudden lack of glyphs.

Other than that, I can only think that there's some unwelcome font cache-ing still going on. The OS really doesn't want to let go of any fonts that might conceivably be in use.

**Comment by moble** [comment]
> Just to be on the safe side, make sure you delete all JuliaMono.*Latin.ttf files - these occasionally slip into play by accident and can confuse the unwary with the sudden lack of glyphs.

What?  There are `JuliaMono-RegularLatin.ttf` and `JuliaMono-BoldLatin.ttf` that come with the current release.  Are you saying there may be files with a dot in the name from some old installation?  Or are you saying that I shouldn't install these Latin files that come with the current release?

> Other than that, I can only think that there's some unwelcome font cache-ing still going on. The OS really doesn't want to let go of any fonts that might conceivably be in use.

I closed everything, removed JuliaMono via Font Book, searched almost my entire computer to make sure there were no JuliaMono* files remaining, then ran `sudo atsutil databases -remove && sudo atsutil server -shutdown && sudo atsutil server -ping`, restarted my computer, and installed the JuliaMono 0.055 ttf files again.  Same problems.

Can you suggest any other rocks for me to look under?

I'm really confused because this all started when I just installed 0.055 without removing 0.054 (telling Font Book to replace , so I would have thought that in the worst-case scenario it might pick up the older version, but not just totally fail to find glyphs at all.  Also, I've noticed that indeed the `->` and `=>` ligatures are now gone.

**Comment by cormullion** [comment]
I wish I could reproduce your problem.

>What? There are JuliaMono-RegularLatin.ttf and JuliaMono-BoldLatin.ttf

JuliaMono is quite a big font, and so (as the documentation explains) there are two smaller versions of the font included, which are basically restricted to the ISOLatin character set. These have "Latin" in the name. They don't usually cause any problems (I've never seen a problem personally), but it is of course possible that one of these Latin fonts gets prioritized and selected by the font management utility you're using (there are many and they all have quirks). If this happens, then most of the characters you see (apart from the lowest 400 or so in the Unicode chart) will be fallback glyphs from other fonts.

(As with most fonts, if you don't need a particular file, just delete it. The last time I downloaded CascadiaCode, I got 88 TTF and 77 OTF font files...)

One way to tell which version of JuliaMono you're currently seeing, which avoids complications such as stylistic sets and contextual alternates, is to look at the representation of the Unicode character U+E843:

```
echo -e "\ue843"
```

which should look like this:

<img width="77" alt="Screenshot 2024-05-08 at 11 11 37" src="https://github.com/cormullion/juliamono/assets/52289/4a41d266-d2cc-40f9-bfb6-1c15ad44ae81">

And, because this is a Private Use Area glyph, there will be a question mark if any other font (including JuliaMono-RegularLatin) is active.

**Comment by moble** [comment]
Ah, I didn't understand that I wasn't supposed to install the Latin variants.  Deleting those seems to have solved my problems.  I've reinstalled 0.055 now, and everything (except for `\eth\bar`) looks great.  Thanks for the clarification!


Also, that `\ue843` trick is pretty neat.  Funny enough, when I copy-pasted that into VS Code while 0.054 was still installed, it showed up properly, but then Github Copilot suggested a glyph that looked almost the same, but with 0.053.  (Maybe an italic variant that hadn't been updated, because Copilot's suggestions are in italics?)
