### ISSUE TITLE
Ligatures are gone in WezTerm after upgrading to JuliaMono 0.055

### ISSUE THREAD

**Issue by piechologist** [cormullion/juliamono#209]
After running `brew upgrade` I got JuliaMono 0.055. Now, WezTerm prints the distinct ASCII characters `|>` and `->` instead of the ligatures. Also, `ss05` for the lighter asterisk and `cv03` for the pronounced tilde don't work anymore. The Julia logos `e801` and `e802` are missing, too.

Everything still works fine in the Zed editor, though. Weird.

I tricked homebrew into installing JuliaMono 0.054 and the issue was resolved. Upgraded again to 0.055 and the issue came up again. 

macOS 12.7.4 Monterey
WezTerm 20240203-110809-5046fc22

Let me know if you need more information and thanks in advance!

**Comment by cormullion** [comment]
In your config, you’ll need “assume_emoji_presentation=false” because Wezterm won’t use JuliaMono (because it contains a colored glyph).

**Comment by piechologist** [comment]
Thank you for the quick response!

I'm afraid the issue is caused by something else. I changed my config to:
```lua
    font = wezterm.font_with_fallback {
        {
            family = 'JuliaMono',
            assume_emoji_presentation = false,
            harfbuzz_features = { 'ss05', 'ss13', 'cv03' },
        },
        'Apple Color Emoji',
    },
```
and the issue persists. I'm sure WezTerm uses JuliaMono (I checked `r` and `g` and they do look like JuliaMono 😃).

When I switch to `assume_emoji_presentation = true` I get some other fallback font (definitely not JuliaMono 😱).

**Comment by cormullion** [comment]
Check that you’re not picking up JuliaMono-Latin by default. (delete it) Otherwise- it works for me 🤔

**Comment by piechologist** [comment]
> Check that you’re not picking up JuliaMono-Latin by default. (delete it)

That did the trick! I don't even need `assume_emoji_presentation`. Thank you for the help and for this great font!
