### ISSUE TITLE
Homebrew install instructions are outdated

### ISSUE THREAD

**Issue by ruurtjan** [cormullion/juliamono#210]
The installation page now says:
```
On the latest version of Homebrew, you can install the fonts with:

brew tap homebrew/cask-fonts
brew install --cask font-juliamono
```

But running that first command gives:

`Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.`

**Comment by cormullion** [comment]
🤔 I changed this before 

https://github.com/cormullion/juliamono/issues/110

I’ll investigate.

**Comment by ruurtjan** [comment]
Thanks!

Installation went fine without `brew tap homebrew/cask-fonts` by the way.

**Comment by cormullion** [comment]
👍 I like the occasional beer myself but I still find all this “cask/tap/keg” terminology a bit confusing 😀
