### ISSUE TITLE
Add Anchors to U+25CC DOTTED CIRCLE for Proper Rendering of Combining Diacritical Marks.

### ISSUE THREAD

**Issue by AlexpFr** [cormullion/juliamono#211]
The character [U+25CC](https://www.compart.com/fr/unicode/U+25CC) `DOTTED CIRCLE` ([Wikipedia - Dotted circle](https://en.wikipedia.org/wiki/Dotted_circle)) is often used as a neutral character to represent combining diacritical marks ([Wikipedia - Combining character](https://en.wikipedia.org/wiki/Combining_character)).
The Unicode standard allows, for example, writing `U+25CCU+0327`, which should render [image].

However, no anchor is currently present on the `DOTTED CIRCLE` to achieve a correct rendering.
An ugly hack that works in VS Code is to type, for example, `U+0327U+025CC`, but the result depends on the editor...

Is it possible/desirable to add anchors to the `DOTTED CIRCLE` character to properly render the combined diacritical marks alone?

Thanks.

**Comment by cormullion** [comment]
I'd like to see the `[image]` in your comment.

This is what I see:

<img width="203" alt="Screenshot 2024-06-06 at 10 08 23" src="https://github.com/cormullion/juliamono/assets/52289/09cdd174-2cc2-47a3-a313-3b8e6c9f122e">

**Comment by AlexpFr** [comment]
Noto Sans Mono have anchors on the dotted circle:

![image](https://github.com/cormullion/juliamono/assets/62973006/eaf27409-9676-482e-bae9-71cf4c0266cd)

**Comment by cormullion** [comment]
Yes, it's very variable depending on environment. On my Mac:

| works OK       | doesn’t work        |
| :------- |:------- |
| BBEdit | Kitty | 
|Jupyter Notebook | Wezterm|
| Terminal| Alacritty|
|iTerm| VS-Code|
| Pages||

I can add anchors easily, although I can't say if this will fix it in all these applications.

**Comment by AlexpFr** [comment]
> I can add anchors easily, although I can't say if this will fix it in all these applications.

Yes... At least with anchors, it will work consistently across applications that correctly implement Unicode.

If you need more information or want to test the behavior, feel free to reach out, I'm available to assist!

**Comment by AlexpFr** [comment]
I'm not an expert in font creation, but the issue lies in the different interpretations of text editors when a combining character is displayed alone. For example, VS Code combines it with the preceding character by adding a space, which is confusing.

There may be rules to introduce directly into the GPOS table of the font to make the behavior more predictable without needing to add anchors to characters that shouldn't have them. ??

**Comment by cormullion** [comment]
VS-Code seems happy with the anchors I added on 25CC.

<img width="72" alt="Screenshot 2024-06-06 at 11 18 32" src="https://github.com/cormullion/juliamono/assets/52289/2e9025af-a750-47d8-921f-c99672267d67">

**Comment by AlexpFr** [comment]
Thanks a bunch!

![image](https://github.com/cormullion/juliamono/assets/62973006/d7bde967-d5a4-4de3-951a-d2e454c0e62b)
