### ISSUE TITLE
Some slightly misaligned box drawing characters

### ISSUE THREAD

**Issue by Timwi** [cormullion/juliamono#212]
* U+254E (BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL) is slightly horizontally misaligned compared to the other box drawing characters, and U+250A (BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL) is slightly too short on the top, causing an extra gap where there should be none:

![screenshot showing misalignment of ╎ and gap above ┊](https://github.com/cormullion/juliamono/assets/1565951/2ff6e97e-bd41-428d-abee-fd018b3027a3)

* U+2504 (BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL) and U+2508 (BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL) have gaps on the left and right:

![screenshot showing gaps in ─╌─┄─┈─](https://github.com/cormullion/juliamono/assets/1565951/1277a3c5-23bd-4d2c-b424-e0e571446357)

* U+250B (BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL) and U+2509 (BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL) have small gaps as well:

![screenshot showing gap above ┋ and in ━╍━┅━┉━](https://github.com/cormullion/juliamono/assets/1565951/278d7ce5-9ccd-440c-841e-10c152749193)

It would be nice if these could be slightly elongated (and U+254E slightly moved over) so that they join up with their neighbors.

Thank you so much for this amazing font!

**Comment by cormullion** [comment]
Thanks! I will get these correct one day!

Could you perhaps check this version to see whether I've improved them a bit?

[jm-056.zip](https://github.com/user-attachments/files/15864266/jm-056.zip)

**Comment by Timwi** [comment]
Hm, why is there a bot that automatically closes bugs after 14 days? Is it desired for reporters to post a comment every 14 days just to keep the issue alive?

**Comment by Timwi** [comment]
OK I tried the newest version and it seems that this issue has been fixed. Thank you so much!! Not sure if “stale” and “This issue was closed because it has been inactive for 14 days” was the correct messaging here.

**Comment by cormullion** [comment]
Hi! The bot should only look at issues that aren’t labeled as Bug or Enhancement - I might have forgotten to label this one. 😱

A reasonable number of people open issues but then move on, without responding to follow-ups -  seems ok to slowly close them.
