### ISSUE TITLE
change cyrillic "я" glyph please

### ISSUE THREAD

**Issue by warpje5** [cormullion/juliamono#213]
Hello, whole font is perfect, I even make all my friends use it, but for us, russians, "я" glyph just doesnt make any sense, it feels unnatural and blend, especially on small scale like this 
![image](https://github.com/user-attachments/assets/4c7653ac-4ccf-4dc2-a083-acdcade0f6f3)
that curvy and and straight down left leg makes "я" glyph feel like completely other one. Especially when you have "к" glyph in same word with perfect angle.

Here is how this exact glyph looks with different popular mono fonts (last in line is JuliaMono)
![image](https://github.com/user-attachments/assets/1c8f0570-1d7b-4a26-a5bf-378a40e68f6e)

Other than that the font is perfect, thank you for your hard work!

**Comment by cormullion** [comment]
Hi, thanks! I updated the font - you can use master of v0.057 until I make a new release...

**Comment by warpje5** [comment]
thank you, now it looks flawless! 
![image](https://github.com/user-attachments/assets/51a91a7b-946d-4121-a6c3-062ac67da707)
