### ISSUE TITLE
Line spacing is too small

### ISSUE THREAD

**Issue by ravshansbox** [cormullion/juliamono#216]
Line spacing is too small compared to other monospace fonts.
This is especially noticeable when switching in terminal apps like default Terminal.app or iTerm on MacOS.
Also noticeable inside vscode when editor pane and terminal is open side by side and both not empty.

**Comment by ravshansbox** [comment]
<img width="811" alt="image" src="https://github.com/user-attachments/assets/a1938c17-f67c-4e80-bf85-ca1141732fa4">
<img width="811" alt="image" src="https://github.com/user-attachments/assets/6567c83a-52b6-4e23-b818-025e58fee286">

**Comment by ravshansbox** [comment]
<img width="651" alt="image" src="https://github.com/user-attachments/assets/e67d1a04-48b6-4db4-9aca-b53894e99165">

**Comment by ravshansbox** [comment]
Maple Mono:

<img width="646" alt="image" src="https://github.com/user-attachments/assets/81aebd8e-8516-4194-94e7-30d6a98e20aa">

**Comment by cormullion** [comment]
I like it tight - so the line drawings work better 😂

Most editors and terminals let you adjust line spacing.

**Comment by ravshansbox** [comment]
Vscode does not allow to customize it's terminal line height

**Comment by cormullion** [comment]
Yes it’s not the most flexible terminal emulator.

**Comment by ravshansbox** [comment]
Increased for myself using this script:

https://gist.github.com/ravshansbox/8b50e5b815ffdb5825608812c82baa6f

**Comment by cormullion** [comment]
Cool!
