### ISSUE TITLE
Docs: Clarify that Latin variants shouldn't be installed

### ISSUE THREAD

**Issue by moble** [cormullion/juliamono#217]
As I found out in #208, the files `JuliaMono-RegularLatin` and `JuliaMono-BoldLatin` are (the only?) two files that should *not* be installed, or they can screw things up.  Currently the docs say that "You don't want to use these", but not in a very prominent spot, and that's still pretty ambiguous.  I fully admit that I'm very naive when it comes to the black magic involved in how apps find glyphs, but I suspect that most users will be just as naive.

I think it would be better to specifically explain that these can / should be excluded when installing the fonts.  One good place to explain this would probably be in the ["Installation"](https://juliamono.netlify.app/download/#installation) section of the "Download" page.  Currently, the relevant instructions say to "drag the font files" — which I interpreted as implying *all* the font files.  Maybe it would be helpful to have a sentence or two right at the beginning of that section explaining that "the files" should normally be taken to mean everything but the Latin ones.

**Comment by cormullion** [comment]
I’m investigating … https://github.com/fonsp/Pluto.jl/discussions/3025

**Comment by moble** [comment]
This appears to be closed by v0.058.

Thanks so much for all your work.  I really love this font!

**Comment by cormullion** [comment]
Thanks! Hopefully the problem will slowly fade over time - although people don't always upgrade their current fonts as often as their other software 🤷‍♂️
