### ISSUE TITLE
Demo page: are fonts loaded twice?

### ISSUE THREAD

**Issue by fonsp** [cormullion/juliamono#23]
It looks like all the fonts are loaded twice - from the same URL, but in separate requests (the response headers are different).

![doublefont](https://user-images.githubusercontent.com/6933510/90237191-2b9b2c00-de24-11ea-8a35-9e164521a094.gif)

**Comment by fonsp** [comment]
(Maybe this is normal - I don't know much about font loading on the web)

**Comment by cormullion** [comment]
Hello again! 

I wonder if this is caused by the two `src url`s in the CSS  - I wasn't sure which one was going to work on the Friday of JuliaCon (various issues with the CORS headers on different browsers) so in case Netlify couldn't deliver the fonts, perhaps Github could... Perhaps I could remove the Netlify sources and rely on github...

I had hoped that the font would download and display quickly, but if it's waiting for two downloads to complete I've shot myself in the foot... :)

**Comment by fonsp** [comment]
I don't think that it's because of the two `src`: this is a compatibility thing - IE only sees the first `src`, modern browsers only see the last (conforming to the CSS spec). And the first `src` point to `github.com/...`, but both requests go to `juliamono.netlify.app`.

**Comment by cormullion** [comment]
I load just from Netlify now (loading from Github didn't work today for some reason...)

**Comment by fonsp** [comment]
Oh I forgot to post it yesterday, but I did the same in Chrome and it only loaded fonts once, so I was going to post that I probably just misread the firefox dev console.

But today I did it again, and it only loads the `Regular` variant (once), not the other weights. I guess you changed something?

![image](https://user-images.githubusercontent.com/6933510/90312384-55c41b00-df04-11ea-966b-799b4615872a.png)

And on firefox, it now loads the font 10 times? I checked the headers, and it's 10 separate requests:

![image](https://user-images.githubusercontent.com/6933510/90312437-c2d7b080-df04-11ea-8b03-d3fff7596a0f.png)

**Comment by cormullion** [comment]
Aye, I changed it this morning - but I couldn't get any downloads from github.com at all, so just deleted those and relied on the netlify paths. I'm going to research it some more... (It occurred to me that free Netlify sites like this have download caps so perhaps there's that as well to worry about! :))

**Comment by fonsp** [comment]
> 
> 
> I load just from Netlify now (loading from Github didn't work today for some reason...)

This could be an HTTP headers problem with GitHub. I would recommend using a CDN that delivers from GitHub releases:

https://cdn.jsdelivr.net/gh/cormullion/juliamono@0.008/webfonts/JuliaMono-Regular.woff2

They look at the file extension (`.woff2`) and make sure that the correct headers are set (just like netlify does). It should also faster across the globe.

**Comment by cormullion** [comment]
That's cool - did you have to register or anything or is it a URL anyone can use?

**Comment by fonsp** [comment]
Nope they forward all of github! Once someone requests a file for the first time, they cache it internally.

They can also do JS (and CSS?) minification by changing the filename from `.js` to `.min.js`.

**Comment by pfitzseb** [comment]
Pretty sure this is a prefetching thing -- as soon as you mark something as `preload` the browser can decide when and how often to load a resource (and some browsers are very bad at showing what's actually happening). I wouldn't worry too much about this.

**Comment by fonsp** [comment]
Thanks!
