### ISSUE TITLE
julϊ̇a 

### ISSUE THREAD

**Issue by onButtonUp** [cormullion/juliamono#25]
Technically, the two dots should overhang towards the 'a'. Personally, I enjoy it as is. 

![image](https://user-images.githubusercontent.com/7108393/90307479-566c9b00-de8b-11ea-9d51-13f789258f46.png)

(One may add something like the following to `startup.jl` to further enjoy juliamono.)

    using REPL

    function myrepl(repl)

        repl.interface = REPL.setup_interface(repl)

        repl.interface.modes[1].prompt = "julϊ̇a> "

        return

    end

    atreplinit(myrepl)

---

You probably thought about it and being "mono" spaced . . .

**Comment by cormullion** [comment]
:) I used to run this too (https://juliamono.netlify.app/faq/#why_dont_these_accentsmarks_work_properly) - but there was one environment/terminal where it caused problems... Can't remember which now... :)
