### ISSUE TITLE
Maybe differentiate \Psi and \psi more

### ISSUE THREAD

**Issue by MasonProtter** [cormullion/juliamono#26]
Currently, I find that `\Psi` and `\psi` in JuliaMono look a little too similar for my taste. It's not a big deal when they're right next to eachother and you can cross reference them, but I worry that I'd mistake the lowercase for uppercase or vise versa if I only saw one of them in isolation. 

E.g. here is Julia mono 
![image](https://user-images.githubusercontent.com/29157027/90546828-da52ab80-e147-11ea-9392-af410c7caa2d.png)
and here is Droid Sans which I think did and excellent job with their `\psi`. 
![image](https://user-images.githubusercontent.com/29157027/90547142-47fed780-e148-11ea-9f15-3819b73ad501.png)
_____

Using emacs and Konsole in Manjaro Linux / KDE Plasma. The monitor is a BenQ GW2765HT 27.0" 2560x1440 Monitor.

**Comment by cormullion** [comment]
Cool idea, I'll have a play and see what emerges. Adding serifs - especially to `\Psi` - is an option, but I'll try to avoid it if I can...

**Comment by cormullion** [comment]
Cool idea, I'll have a play and see what emerges. Adding serifs - especially to `\Psi` - is an option, but I'll try to avoid it if I can...

**Comment by cormullion** [comment]
How about these:

<img width="801" alt="Screenshot 2020-08-19 at 09 42 55" src="https://user-images.githubusercontent.com/52289/90612753-61fbf100-e200-11ea-92ff-d47e86968fb9.png">

**Comment by MasonProtter** [comment]
Looks great!

**Comment by cormullion** [comment]
Now in version v0.009. Keep 'em coming!

**Comment by MasonProtter** [comment]
Wonderful!
