### ISSUE TITLE
Tilde and accents are cropped out in upper case characters

### ISSUE THREAD

**Issue by martincornejo** [cormullion/juliamono#28]
Couldn't but noticed that tildes and accents are incomplete with taller upper case letters: ñÑ áÁ (at least on the Windows Terminal)

## JuliaMono
![image](https://user-images.githubusercontent.com/53337152/91616641-635ab580-e986-11ea-877d-6fdab273fb66.png)

## Cascadia Code
![image](https://user-images.githubusercontent.com/53337152/91616720-913ffa00-e986-11ea-948f-540460215b6e.png)

**Comment by cormullion** [comment]
Hi! It does look like Windows Terminal is cropping quite tightly - here's MacOS in comparison with line spacing set to 1:
 
<img width="714" alt="Screenshot 2020-08-29 at 11 15 04" src="https://user-images.githubusercontent.com/52289/91634564-2f64ac00-e9e9-11ea-8acd-45877294a7ff.png">

One day I'll have a Windows machine to investigate these type of issues...
