### ISSUE TITLE
line-height changed?

### ISSUE THREAD

**Issue by shabahengam** [cormullion/juliamono#30]
please look at the picture.
Left v0.010 ... Right v0.011
https://0x0.st/iExn.png
6 line less is a big change.don't you think?

OS: Linux
Terminal: rxvt-unicode
Editor: Neovim
Font: JuliaMono Medium,Size 10

**Comment by cormullion** [comment]
Indeed - i’m trying to find a good compromise between good line spacing and people losing the tops of accents - see previous issue. 😂 

Next release might be adjusted back a bit. You can stay with v0.010 perhaps?

**Comment by shabahengam** [comment]
> You can stay with v0.010 perhaps?

Yep,I will stay with v0.010.Thank you for creating this font. :+1:

**Comment by cormullion** [comment]
By the way, do you have a separate line-spacing option on your terminal?

**Comment by shabahengam** [comment]
`URxvt.lineSpace:        0` is set in `.Xresource`.
PS: I had this issue with [agave font](https://github.com/agarick/agave), maybe [this issue ](https://github.com/agarick/agave/issues/15)can help?

**Comment by cormullion** [comment]
I think most fonts have to compromise, I'm trying to find settings that works for people who use accented characters and people who want more lines to a screen. ;) I think a quality terminal application should allow you to make the choice you want: here's the MacOS terminal with 0.8 (left) and 1..0 (right) linespacing. The font shouldn't be having to do this job for you...

<img width="1523" alt="Screenshot 2020-09-01 at 15 14 49" src="https://user-images.githubusercontent.com/52289/91863231-cf7b3900-ec66-11ea-8cd7-3ddb8a8218d3.png">

In the next release (today or tomorrow) I'm going to compromise between the settings of release v0.10 and v0.11. If this doesn't work for you, I'll be disappointed 😄) - and I'd suggest you try a more powerful terminal app that gives more customization...

**Comment by shabahengam** [comment]
v0.012 is better.now I have 40 lines on my screen(in neovim).thank you :+1:

**Comment by cormullion** [comment]
Cool!

**Comment by cormullion** [comment]
Cool!

**Comment by cormullion** [comment]
Cool!

**Comment by cormullion** [comment]
Cool!

**Comment by shabahengam** [comment]
OK, I close the issue because I think it get fixed.Thank you :+1:
