### ISSUE TITLE
Printing bug for >-->

### ISSUE THREAD

**Issue by simeonschaub** [cormullion/juliamono#31]
To reproduce, write `>-->` in a terminal with ligatures enabled. The last `>` becomes invisible and actually every character after that becomes invisible as well. Could this be a bug in the ligature rendering? I am using the latest v0.011 and this doesn't happen with any other font.

**Comment by cormullion** [comment]
Yes I don't know what happened there. I'll blame cosmic rays hitting the hard drive... ;) I've repaired it and it will be up soon...

**Comment by simeonschaub** [comment]
Fixed now!
