### ISSUE TITLE
Not working properly on VS code 

### ISSUE THREAD

**Issue by stanleesocca** [cormullion/juliamono#32]
After downloading the font and installing correctly, The fonts don't seem to be working correctly on my vs code editor. Current setting.json:

```
   "terminal.integrated.fontSize": 14,
   "editor.fontFamily": "JuliaMono-Regular",
    "terminal.integrated.fontFamily": "Consolas",
    "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'ss07'",
    "editor.suggest.showInterfaces": false,
    "julia.execution.resultType": "both",
    "editor.fontSize": 16
```

But editor keep displaying this: 

![image](https://user-images.githubusercontent.com/31194250/92173899-6816e200-ee3c-11ea-94c8-85cc22ebc0aa.png)

Ordinarily, I would be expect the font style and ligature to display nicely like in the screenshot in https://juliamono.netlify.app/ 
Not sure why mine isn't working and what I'm missing

**Comment by cormullion** [comment]
Remove "-Regular" perhaps, if you're on Windows?

**Comment by stanleesocca** [comment]
Removed. But nothing change. Indeed, it's on a Windows

**Comment by cormullion** [comment]
Pity, that was my best suggestion... 😀 Do you have any other apps you can try to see if it's installed? I know that it works, I've seen screen shots... :)

**Comment by stanleesocca** [comment]
Finally got it to work. I guess all I needed to do was restarting vs code. Maybe, has something to do with windows way of working.

**Comment by cormullion** [comment]
Fonts are tricky things, sometimes. Aggressively cached... 😀

**Comment by stanleesocca** [comment]
Thanks for this nice package. A random question, how do one place an underscore in unicode text just as you did in example. \sum_{n} doesn't seem to work as you normally do in latex.

**Comment by stanleesocca** [comment]
Again got it. Awesome package. I will close the issue
