### ISSUE TITLE
remove <- ligature?

### ISSUE THREAD

**Issue by simeonschaub** [cormullion/juliamono#33]
The `<-` ligature can be confusing for Julia code, since in Julia, `<-` is not an operator. This is because it misleadingly makes`1<-2`  look like `1 <- 2`, where it actually parses as `1 < -2`. Since this font is advertised as being explicitely designed for Julia, would it make sense to disable that ligature by default?

**Comment by cormullion** [comment]
Yes, that makes sense. I could make it work if there were preceding and trailing spaces, perhaps?

**Comment by simeonschaub** [comment]
Technically, `1 <- 2` is still valid syntax (see JuliaLang/julia#30464), although I doubt this is actually used much. I don't really have a very strong opinion either way.

**Comment by cormullion** [comment]
I removed it - one less thing to worry about!

**Comment by simeonschaub** [comment]
Oh, sorry, forgot to close this. Thanks for fixing it!
