### ISSUE TITLE
Capital Phi Φ too low

### ISSUE THREAD

**Issue by jagot** [cormullion/juliamono#34]
As shown in the screenshot, the "ring" of the capital Phi Φ seems to rest on the baseline:
![image](https://user-images.githubusercontent.com/117947/92389077-a819e580-f118-11ea-9d26-8140d8441259.png)

This feels wrong to me, being half Greek. This is more in line with what I expect, i.e. that the vertical line ends on the baseline (taken from Wiki):

![image](https://upload.wikimedia.org/wikipedia/commons/c/c2/Phi_uc_lc.svg)

- 27" 1980x1080 monitor => 82 dpi (https://www.philips.com.my/c-p/271B8QJEB_69/lcd-monitor)
- macOS Catalina
- Emacs
- JuliaMono 0.013

**Comment by jagot** [comment]
To illustrate a problematic case:

![image](https://user-images.githubusercontent.com/117947/92389575-a4d32980-f119-11ea-87db-1ad5cd00f486.png)

It is difficult to see which of the phis is lower case and which is upper case. To me, they both look like lower case, but different versions.

**Comment by cormullion** [comment]
Hi there! Can you help me by clarifying what's going on by including some Unicode code points - these φs are very confusing for me! See issue https://github.com/cormullion/juliamono/issues/29), and also see the Unicode Consortium [here](https://www.unicode.org/reports/tr25/tr25-6.html), section 2.3.1. 

If I understand you and them correctly, the 0x03A6 GREEK CAPITAL LETTER PHI should be higher, resting on the baseline, whereas the 0x03D5 (GREEK PHI SYMBOL) should be basically the same ("Straight") design but lower, with a descender, but not "loopy" like 0x03C6 (GREEK SMALL LETTER PHI) ?

Sort of like this:

<img width="625" alt="Screenshot 2020-09-07 at 14 53 12" src="https://user-images.githubusercontent.com/52289/92394686-e2d04d80-f119-11ea-81dd-d303931235db.png">

**Comment by jagot** [comment]
Ok, so here is my take on this:

- Capital Phi Φ should have the vertical line resting on the baseline and the overall size should be similar to capital O and capital Theta Θ. Sometimes you see horizontal lines at the top and the bottom of the vertical lines, but these are really serifs (as shown in the screenshot) and should not be there in a sans-serif font.
- The loopy version 0x03C6 is what I would write with a pen on paper, whereas the non-loopy version 0x03D5 is what I expect in print (there are of course exceptions to this rule). Some scientists use both in the same work to mean different things, which to me is horrifying since they are stylistic variations of the same symbol.
- Both lower case letter should have the same size of the "round part", which should rest on the baseline, and have descenders which are of the same length. The non-loopy version should have an ascender that is shorter than the descender, or at least never high enough to reach the full height of a capital letter.

Take this with a grain of salt, it may be useful to consult with people who have grown up in Greece, e.g. @datseris.

From page 2 of https://www.unicode.org/charts/PDF/U0370.pdf:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/117947/92406007-33a26f00-f137-11ea-85a6-72d341a375cb.png">

**Comment by cormullion** [comment]
This is great, thanks! I'll make a few changes for the next release, v0.014, probably later this week.

**Comment by Datseris** [comment]
Hi there, yeap what Stefanos said in the original post is the correct version. Captial Φ is same size as e.g. Σ or Ξ or ... But you guys already resolved everything in the later post! I confirm that the post of Stefanos with the size indications in red is very much what you'd see in Greek type as well as handwritting.

Notice also the difference between the wigly small φ and the straight one (which is like a copy of the capital Phi but smaller in size). The "scientific standard" version the non-wigly, see also the standard latex notation: `\phi` vs `\varphi` : https://www.overleaf.com/learn/latex/List_of_Greek_letters_and_math_symbols#Greek_letters  

However the wigly phi is in fact the typical version taught in Greece as lower-case and is more common than the non wigly for the lower-case version. For example, when I switch my keyboard to Greek and type the equivalent of phi, I get this symbol: φ. Wikipedia also seems to prefer the wigly:

![image](https://user-images.githubusercontent.com/19669089/92409840-4f5f4280-f142-11ea-8819-180396921369.png)

**Comment by cormullion** [comment]
@Datseris ευχαριστώ!

**Comment by jagot** [comment]
I realized I might as well look at the whole alphabet at the same time (this could be a separate issue, if you prefer):

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/117947/92439144-954ff100-f1aa-11ea-8411-e9588a42d013.png">


- Marked in red are those that I feel are serifs, i.e. not part of the "idea" of the letter (to paraphrase Plato); lower case chi could be argued to have serifs as well, but there more variations are seen.
- A few letters are blacker (heavier) than the others:
  - Upper case: Omicron, Ypsilon, and possibly Psi
  - Lower case: gamma, psi
- I think those letters that look the same in the Greek and Latin alphabets should have the same glyphs, e.g. Zeta <-> Z, Xi <-> X

I made a scan from an old Greek grammar book that uses many fonts (which may or may not be a good idea...):

![greek](https://user-images.githubusercontent.com/117947/92438237-bb749180-f1a8-11ea-9d9a-40b8fba2e64c.jpg)

Especially the main font makes a good example of what the essential part of each letter is. The [Porson typeface](https://greekfontsociety-gfs.gr/typefaces/19th_century) is another nice example.

I hope this comments are not out-of-place, a lot of this is of course a matter of subjective opinion. Overall, JuliaMono is a nice font!

**Comment by cormullion** [comment]
Thanks so much for your suggestions! I really appreciate the contributions.

Indeed, I don't think this font will be good for setting Plato, or any Greek texts .... :) I suppose one of the main aims was to make every letter as distinct as possible, since the glyphs are typically used on their own, out of context, mixed in with Latin and other shapes, rather than seen in words of their own group. So, for example, ν should be easy to distinguish from v and ⌵ and ⋁ on an average quality display at 10pt... 

I'll try to fix the more egregious problems soon. If I get round to spending a lot more time on this, I might revisit the designs of all of them! 😅

**Comment by jagot** [comment]
Yes, I thought about the disambiguation argument, but I would rarely use say a capital Alpha in the same code to be a distinct symbol from capital A. Being so similar, a serif would not work very well to keep them separate anyway.

https://www.reddit.com/r/ProgrammerHumor/comments/ce1d81/til_the_greek_question_mark_prank/

**Comment by Datseris** [comment]
Ugh, tell me about it. Sometimes I switch to greek to type φ and then forget to switch back and might type A but the parser (at least in Juno) thinks Α and Α are two different things. UUUUUUGH

**Comment by cormullion** [comment]
<img width="115" alt="Screenshot 2020-09-08 at 13 16 19" src="https://user-images.githubusercontent.com/52289/92475562-80d51e00-f1d5-11ea-9789-1e7619580694.png">

**Comment by 4aHxKzD** [comment]
Came here to open an issue regarding lower case phi being too similar do upper case phi. But it seems that it is already being taken care of :)
