### ISSUE TITLE
Varient Ligatures with very small gap?

### ISSUE THREAD

**Issue by oxinabox** [cormullion/juliamono#35]
Can we use stylistic alternatives to have a second set of ligatures?
I would just like a small gap, rather than no gap for them.
I think 1 full pixel, rather than just a little bit of  shading, would be all i want.

<img width="35" alt="image" src="https://user-images.githubusercontent.com/5127634/92406707-9ba18700-f130-11ea-9ebc-45117ac030e6.png">

I had to zoom so far in to see that there was infact some shading between the characters

<img width="671" alt="image" src="https://user-images.githubusercontent.com/5127634/92406755-bffd6380-f130-11ea-8158-0ea8ef8d3f9d.png">

**Comment by cormullion** [comment]
Interesting idea.

Glyphs are excluded from subsequent processing once they're successfully processed once. This is presumably intended to prevent infinite loops, self-recursive calls, and stuff. So if the `calt' feature is enabled (which it is by default), the `=` and `>` are processed there, and therefore not eligible for further processing by a `ss08` stylistic set.

But if you disable the `calt` feature, some glyphs aren't processed, and are therefore available for use with a stylistic set.

<img width="586" alt="Screenshot 2020-09-07 at 18 29 06" src="https://user-images.githubusercontent.com/52289/92409299-0acea980-f138-11ea-8c9e-2f20210e4b65.png">

I don't have any control over pixels, I can only leave a gap.

I'll put this in the next release (v0.014) and you can play with it and see whether you like it...?
