### ISSUE TITLE
Release zip as well as tar.gz

### ISSUE THREAD

**Issue by musm** [cormullion/juliamono#38]
It's just a little bit of an extra pain for Windows users

**Comment by cormullion** [comment]
Oh is the .zip not a Zip file? It just says ZIP archive:

<img width="261" alt="Screenshot 2020-09-16 at 17 53 02" src="https://user-images.githubusercontent.com/52289/93368162-7eae3780-f845-11ea-923e-dd33cbfa5103.png">

(Mac user here... :)

**Comment by musm** [comment]
I downloaded them from https://github.com/cormullion/juliamono/releases/tag/v0.015 
and only the .tar.gz non-source code files where available

**Comment by cormullion** [comment]
Perhaps that's  a github actions thing. Will investigate.

**Comment by cormullion** [comment]
@simeonschaub How could a github actions script offer an option of either a ZIP or tar,gz release to a user - is that even possible?.

**Comment by simeonschaub** [comment]
I think it is possible to upload multiple release artifacts, but I have to look into how to do that inside the action.

**Comment by cormullion** [comment]
Thanks!
