### ISSUE TITLE
\cap (U+2229) should sit on baseline?

### ISSUE THREAD

**Issue by JeffBezanson** [cormullion/juliamono#4]
I get the following rendering on linux (tried x emacs and terminal so far):
![cupcap](https://user-images.githubusercontent.com/744556/88867967-e993a880-d1dc-11ea-874e-1b3989de93aa.png)

The cap appears to be levitating a bit.

**Comment by cormullion** [comment]
Thanks!  🕴

I've been guessing where to put these unfamiliar (to me) symbols - `-`-centred or baseline-aligned...? Anyway, this should be fixed in v0.002.
