### ISSUE TITLE
Design of fractions

### ISSUE THREAD

**Issue by kimikage** [cormullion/juliamono#41]
I really love this font :heart: and it seems to be intentionally designed, but I don't like the design of the fractions.

![frac](https://user-images.githubusercontent.com/12679384/93771291-44cf9d80-fc58-11ea-8e44-1775c5330feb.png)

I can't visually recognize the center character of the figure above as a fraction. In particular, the numerators other than 1 and 2 are hard to recognize because they do not have a horizontal line element at the bottom.

I also don't see the rationale for fitting a glyph between the baseline and ascender line. It feels like it unnecessarily reduces the size of the figures. (**Edit:** As I commented below, if this is a ligature issue, I can understand why it would be of such a size and position, but that does not change the claim.) I would prefer to follow the position and size of superscript and subscript numbers.

I know that OpenType has features for styling fractions (`frac`/`afrc`). However, I suggest changing the "default" glyph design.

**Comment by kimikage** [comment]
Wait, is this a rendering issue?
https://github.com/cormullion/juliamono/blob/d5ff406eb2b2f178d09020fba9fb0f9543207805/website/_assets/unicode-sample.svg
![frac2](https://user-images.githubusercontent.com/12679384/93777413-b3fcc000-fc5f-11ea-9f3b-92015229716d.png)

**Comment by cormullion** [comment]
Hi! Usually it’s me that asks you to make things bigger so this is unusual! 😂

The fractions haven’t had much work on them up to now, since they’re not much used in Julia source code. Perhaps I’ll revisit them in a future update. Perhaps a Stylistic Set could hold alternate designs.

**Comment by kimikage** [comment]
> they’re not much used in Julia source code.

You are right. The three letters ¼, ½, and ¾ are in U+0000-U+00FF (i.e. ISO-8859-1), so I noticed that when I dumped the glyphs in the range, not while I was coding Julia scripts. :sweat_smile:

I was more worried about the environmental dependency issues in the automatic generation of glyphs than the design itself.

**Comment by kimikage** [comment]
Maybe this has been fixed in v0.026?

Thanks!

**Comment by cormullion** [comment]
Probably not "fixed" (since nothing is ever perfect) but hopefully better as of v0.016... :)
