### ISSUE TITLE
Wrong glyph for U+240E SYMBOL FOR SHIFT OUT

### ISSUE THREAD

**Issue by dscorbett** [cormullion/juliamono#45]
In version 0.016, U+240E SYMBOL FOR SHIFT OUT looks like “SS”. It should look like “SO”.

**Comment by cormullion** [comment]
No problem. What kind of Julia programming are you up to that needs these unusual characters?! 😄

**Comment by dscorbett** [comment]
Oh, I’m not actually using these characters. I just enjoy doing font QA.

**Comment by cormullion** [comment]
Ha, well, thanks anyway! Sorry there's so many... 😃
