### ISSUE TITLE
Wrong glyphs for U+013F..U+0140 LATIN CAPITAL/SMALL LETTER L WITH MIDDLE DOT

### ISSUE THREAD

**Issue by dscorbett** [cormullion/juliamono#47]
In version 0.017, the dot of U+013F LATIN CAPITAL LETTER L WITH MIDDLE DOT and U+0140 LATIN SMALL LETTER L WITH MIDDLE DOT is above the letter. It should be to the right. Also, the dots should be the same size as U+00B7 MIDDLE DOT.
![Ŀŀ·](https://user-images.githubusercontent.com/1124347/94571345-e26d3300-023d-11eb-9d66-dfb50e0d6404.png)

**Comment by cormullion** [comment]
moved to #49
