### ISSUE TITLE
Mirrored phonetic glyphs

### ISSUE THREAD

**Issue by dscorbett** [cormullion/juliamono#48]
In version 0.017, U+0281 LATIN LETTER SMALL CAPITAL INVERTED R, U+02B4 MODIFIER LETTER SMALL TURNED R, and U+02B5 MODIFIER LETTER SMALL TURNED R WITH HOOK are all mirrored across the vertical axis from how they should look.
![ʁʴʵ](https://user-images.githubusercontent.com/1124347/94572742-5bb95580-023f-11eb-8cc2-201464a0d235.png)

**Comment by cormullion** [comment]
Thanks! Do you think you could put all these in a single issue?

**Comment by dscorbett** [comment]
You mean all the issues I find? Sure, I can do that if you want, but won’t it be confusing to track so many unrelated issues in the same ticket?

**Comment by cormullion** [comment]
no, because I like working through lists... 😀

**Comment by cormullion** [comment]
moved to #49
