### ISSUE TITLE
Glyphs to fix

### ISSUE THREAD

**Issue by dscorbett** [cormullion/juliamono#49]
- [x] In version 0.017, the dot of U+013F LATIN CAPITAL LETTER L WITH MIDDLE DOT and U+0140 LATIN SMALL LETTER L WITH MIDDLE DOT is above the letter. It should be to the right. Also, the dots should be the same size as U+00B7 MIDDLE DOT.

    ] ![Ŀŀ·](https://user-images.githubusercontent.com/1124347/94571345-e26d3300-023d-11eb-9d66-dfb50e0d6404.png)

- [x] In version 0.017, U+0281 LATIN LETTER SMALL CAPITAL INVERTED R, U+02B4 MODIFIER LETTER SMALL TURNED R, and U+02B5 MODIFIER LETTER SMALL TURNED R WITH HOOK are all mirrored across the vertical axis from how they should look. 

     ![ʁʴʵ](https://user-images.githubusercontent.com/1124347/94572742-5bb95580-023f-11eb-8cc2-201464a0d235.png)

- [ ] Many glyphs are blank: U+01F6, U+03E2..U+03EF, U+0464..U+046F, etc. This is worse than no glyph at all because it looks like a space and blocks font fallback.

- [x] U+027F LATIN SMALL LETTER REVERSED R WITH FISHHOOK should have a descender: [the code chart](https://www.unicode.org/charts/PDF/U0250.pdf) says “preferred presentation is with a descender”.

- [x] The lunate sigmas U+03F2 and U+03F9 are wrong. They should be lunate, like the letter ⟨C⟩, but they currently look identical to U+03C2 and U+03A3.

- [x] The crossbar of U+03F4 GREEK CAPITAL THETA SYMBOL should reach all the across the letter, joining to the sides of the circle, unlike U+0398 GREEK CAPITAL LETTER THETA.

- [x] U+03E0 GREEK LETTER SAMPI should only have two dangling strokes, not three.

- [x] The dentistry symbols U+23BE..U+23CC are meant to join left and right to adjacent dentistry symbols, like box drawing symbols do.

- [x] U+0190 LATIN CAPITAL LETTER OPEN E and U+2107 EULER CONSTANT are wrong. The top should be round, as in the lowercase form U+025B.

- [x] U+2108 SCRUPLE is wrong. It should look more like, though not necessarily identical to, U+042D CYRILLIC CAPITAL LETTER E.

- [x] There is a bug in the 'cmap' table where the glyphs for U+0400 and U+040D are also mapped to U+0450 and U+040D.

- [x] U+0275 LATIN SMALL LETTER BARRED O has an inner straight line but U+019F LATIN CAPITAL LETTER O WITH MIDDLE TILDE has an inner wavy line. Despite their misleading names, they are a case pair and their inner lines should be consistent. I recommend using a straight line.

- [x] The hook of U+0225 LATIN SMALL LETTER Z WITH HOOK should go on the right, as in its capital form U+0224.

- [x] The components of the ligatures U+02A4 LATIN SMALL LETTER DEZH DIGRAPH, U+02A5 LATIN SMALL LETTER DZ DIGRAPH WITH CURL, U+23D6 METRICAL TWO SHORTS JOINED, U+A728 LATIN CAPITAL LETTER TZ, U+A733 LATIN SMALL LETTER AA, and U+1D12B MUSICAL SYMBOL DOUBLE FLAT should be ligated but aren’t.

- [x] The curly upsilons U+03D2..U+03D4 are not curly.

- [x] U+02F6 MODIFIER LETTER MIDDLE DOUBLE ACUTE ACCENT looks like a quotation mark instead of a double acute accent.

- [x] U+018F LATIN CAPITAL LETTER SCHWA, U+04D8 CYRILLIC CAPITAL LETTER SCHWA, U+04DA CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS, U+A732 LATIN CAPITAL LETTER AA, U+A734 LATIN CAPITAL LETTER AO, U+A736 LATIN CAPITAL LETTER AU, U+A738 LATIN CAPITAL LETTER AV, U+A7AB LATIN CAPITAL LETTER REVERSED OPEN E, and U+A7AC LATIN CAPITAL LETTER SCRIPT G should be as tall as other capital letters.

- [x] U+214E TURNED SMALL F is a lowercase letter. It should be as tall as ⟨x⟩.

- [x] The Hebrew characters U+05D0..U+05EA, U+2136, U+2138, and U+FB25 are assigned to the wrong code points. Hebrew is utterly illegible in this font.

- [x] U+2210 N-ARY COPRODUCT should be taller and descend below the baseline, because it is an _n_-ary operator. Cf. U+220F N-ARY PRODUCT.

- [x] U+2E42 DOUBLE LOW-REVERSED-9 QUOTATION MARK is upside-down.

- [x] U+301D REVERSED DOUBLE PRIME QUOTATION MARK and U+301E DOUBLE PRIME QUOTATION MARK should be redesigned to match U+301F LOW DOUBLE PRIME QUOTATION MARK.

- [x] U+A69C MODIFIER LETTER CYRILLIC HARD SIGN and U+A69D MODIFIER LETTER CYRILLIC SOFT SIGN should be superscript.

- [x] U+A71F MODIFIER LETTER LOW INVERTED EXCLAMATION MARK should be subscript.

- [x] The dot of U+A73E LATIN CAPITAL LETTER REVERSED C WITH DOT should go inside the letter, not above it.

- [x] U+A771 LATIN SMALL LETTER DUM is missing the abbreviation stroke at the bottom right.

- [x] The stroke of U+A749 LATIN SMALL LETTER L WITH HIGH STROKE should be horizontal.

- [x] Despite its misleading name, according to [L2/20-038](https://www.unicode.org/L2/L2020/20038-voqs-req.pdf), U+A7F8 MODIFIER LETTER CAPITAL H WITH STROKE is really a superscript _small_ capital H with stroke. Cf. U+02B6, which is the correct size for a modifier small capital letter.

- [x] U+AB64 LATIN SMALL LETTER INVERTED ALPHA should look like an upside-down Latin alpha, not a right-side-up Greek alpha.

- [x] U+AB5D MODIFIER LETTER SMALL L WITH INVERTED LAZY S should have an inverted lazy S, not a normal lazy S.

- [ ] The glyph at U+FAB2 CJK COMPATIBILITY IDEOGRAPH-FAB2 belongs in a private use area.

- [ ] The fullwidth characters U+FF01..U+FF60 are not fullwidth.

- [x] The rings of U+10B3E LARGE TWO RINGS OVER ONE RING PUNCTUATION and U+10B3F LARGE ONE RING OVER TWO RINGS PUNCTUATION are positioned wrong.

- [x] U+1D12A MUSICAL SYMBOL DOUBLE SHARP is not supposed to look like two adjacent sharp signs. It is a distinct symbol.

- [x] U+1F0BF PLAYING CARD RED JOKER, U+1F0CF PLAYING CARD BLACK JOKER, and U+1F0E0 PLAYING CARD FOOL are indistinguishable.

**Comment by cormullion** [comment]
Thanks for your efforts - and for putting them in a list (much easier than multiple github issues). I've addressed most of them.  Of the three I haven't:

1 - empty glyphs: unfortunately I can't at the moment delete them. If I do, the font doesn't compile. I'm hoping this is a bug in the software, and that it'll be fixed in a forthcoming release.

2 - PUA - this is the bad influence of nerdfonts, I think. Not sure if I'll fix it though.

3 - fullwidth characters. I have no idea about these, as yet.

**Comment by dscorbett** [comment]
What tool are you using that requires blank glyphs? When compilation fails, is there an error message? If there’s no way to work around it in your font editor, you can use pyftsubset to remove the blank glyphs.

**Comment by dscorbett** [comment]
U+0450 and U+045D no longer have the wrong glyphs. Instead, they have no glyphs. That indicates that it is possible to make this font with missing glyphs without a compilation error.

The dentistry symbols now mostly connect, except that U+23C9 DENTISTRY SYMBOL LIGHT DOWN AND HORIZONTAL is slightly shifted to the right.

U+05E3 HEBREW LETTER FINAL PE now has the correct glyph except that when it was moved from U+05DC the glyph was raised.

U+2E42 DOUBLE LOW-REVERSED-9 QUOTATION MARK is still wrong: it is now mirrored across the vertical axis.

U+1D12B MUSICAL SYMBOL DOUBLE FLAT is still not ligated.
