### ISSUE TITLE
Help with this experiment! 

### ISSUE THREAD

**Issue by cormullion** [cormullion/juliamono#5]
Thanks for your interest in this experiment!

Wouldn't it be great if your code ran perfectly on everybody's machine, no matter what? I wish... 😃 So, I'm interested in seeing how different this font 'code' runs on various machines. So, if you have a spare minute, you could upload a picture of JuliaMono-Regular running on your setup.

I suggest opening up a file such as `/julia/base/ntuple.jl` for editing in your usual favourite coding environment, and post it with a few details about how old your machine is, which OS, monitor resolution, and so on. I might be able to gather from these where best to spend time trying to improve it.

iMac (Retina 5K, 27-inch, 2017):

<img width="1051" alt="Screenshot 2020-07-30 at 18 08 01" src="https://user-images.githubusercontent.com/52289/88952649-9fb7ca80-d28f-11ea-8307-c58ebb2b2a0d.png">

Thanks!

**Comment by simeonschaub** [comment]
Linux, with FullHD display. Running vim inside the Kitty terminal. JuliaMono-Medium at 10pt, without any sub-pixel antialiasing:

![Screenshot from 2020-07-30 21-16-22](https://user-images.githubusercontent.com/5220528/88964707-0a75ff80-d2aa-11ea-8eb4-14960f8c5cc7.png)

At 10 pt some of the characters look like they're bouncing around a bit, as described in #3, but I am still very much enjoying this font and have set it as the default for my terminal. Awesome work!

**Comment by kalmarek** [comment]
ArchLinux, 1440p, font smoothing
![Screenshot_20200730_232052](https://user-images.githubusercontent.com/1666118/88976201-f2a77700-d2bb-11ea-8087-179ef4bdf613.jpg)

**Comment by cormullion** [comment]
Thanks - results are disappointing, there's quite a difference between the various platforms, which I didn't really anticipate. I'll probably switch from CFF to TTF internally, although that will make the files bigger... 

@simeonschaub I appreciate your testing!  :)

**Comment by cormullion** [comment]
MacbBook Pro 2012 running Ubuntu, 1280x800, antialias, slight autohinting

![Screenshot from 2020-07-31 11-05-58](https://user-images.githubusercontent.com/52289/89026826-47310d80-d321-11ea-872f-5139f6ba50ae.png)

you can see why I was optimistic about quality - I thought that if this was 2012 quality it would be better in 2020...

**Comment by hearnsj** [comment]
Dell LAtitude 5400 laptop.  Display is Philips 25 inch monitor 2560x1440
Editor is Atom 1.50.0-beta0  
Font should be JuliaMono at 17 points    - apologies if this is FiraCode - I did try to configure it cirrectly


![image](https://user-images.githubusercontent.com/19259589/89032984-b6acfa00-d32d-11ea-91db-fdbc35f9561e.png)

**Comment by cormullion** [comment]
@hearnsj Thanks - looks better at 17point... :) My eyes are not compatible with 10point text...

**Comment by xukai92** [comment]
![image](https://user-images.githubusercontent.com/5985769/89041678-b0bf1500-d33d-11ea-9aae-07df520a1988.png)
- VS Code
- 12pt 
- macOS 10.15.5 
- 1920 x 1200

**Comment by cormullion** [comment]
@xukai92 Thanks! Seems fairly accurate rendering if a little fuzzier...

**Comment by xukai92** [comment]
I ended up using 13pt instead which seems to be better.

![image](https://user-images.githubusercontent.com/5985769/89042960-b4539b80-d33f-11ea-893f-4830387f36ef.png)

**Comment by cormullion** [comment]
Yes, I like larger sizes... :)  Apple don't do font-hinting, so I suspect it won't get any better for Mac users. There's the Font smoothing option:

<img width="310" alt="Screenshot 2020-07-31 at 15 12 17" src="https://user-images.githubusercontent.com/52289/89043359-40fe5980-d340-11ea-8479-9fc4e0b7570e.png">

and that's about it. Is it a new Mac?

**Comment by xukai92** [comment]
It's a MacBook Pro 2018. My font smoothing is turned on already

**Comment by myrddin89** [comment]
MacBook Pro (Retina, 13-inch, Mid 2014), 2560 x 1600. 
Editor is Atom 1.49.0 with 12pt font.
<img width="1200" alt="immagine" src="https://user-images.githubusercontent.com/964473/89112852-94b89200-d469-11ea-998e-b5a0b6329022.png">

**Comment by cormullion** [comment]
@myrddin89 Thanks - one of the best environments for this!

**Comment by xukai92** [comment]
The screenshot from @myrddin89 looks much smoother than mine. What makes the difference here?

**Comment by cormullion** [comment]
@xukai92 I noticed your image was a little fuzzier... do you have a Retina display?

**Comment by myrddin89** [comment]
It well may be the Retina resolution, I usually notice the difference, especially after a while I don’t use a non Retina monitor.

**Comment by xukai92** [comment]
Just tried it on the Retina display rather than my 1900x1200 external monitor - it indeed looks better:

![image](https://user-images.githubusercontent.com/5985769/89125572-55288f00-d4d7-11ea-90f5-7ee822b70082.png)

Even this screenshot on my external monitor looks less fuzzier than the actual rendered version ...?

**Comment by simeonschaub** [comment]
Now looks great on v0.004!

![Screenshot from 2020-08-02 23-16-20](https://user-images.githubusercontent.com/5220528/89132675-31386e00-d516-11ea-9319-29410328d895.png)

**Comment by ckoe-bccms** [comment]
Hello,

with v0.004 on ubuntu 16.04, screen is samsung 24" 1920x1080, Xft.dpi: 92, Xft.antialias: true, Xft.hinting: true, Xft.hintstyle: hintsnone. 
I usually first open files in vim in an xterm (using my default terminal font) and eventually remember to switch to gvim later. So two screenshots are attached, on with vim in xterm (xterm -fa "JuliaMono" -fs 12) and one in gvim (Regular, 12pt). 

Probably I am not your typical user :-) Hope this helps anyway and thank you for the interesting project !

![xterm](https://user-images.githubusercontent.com/16237711/89293261-26342980-d64d-11ea-808a-2568d55b045e.png)
![gvim](https://user-images.githubusercontent.com/16237711/89293355-54196e00-d64d-11ea-9b94-6cf68fded8f4.png)

**Comment by cormullion** [comment]
@ckoe-bccms Thanks very much! It doesn't look too bad... 🤣

I think if I was using this setup, I'd choose the alternate designs for /a and /g... :) I know how to do this in Atom and VS-Code, and Kitty, but not in any other terminal app... 😕

**Comment by MasonProtter** [comment]
Here is `julia/base/ntuple.jl` using emacs in Manjaro Linux and KDE Plasma. The monitor is a BenQ GW2765HT 27.0" 2560x1440 Monitor. 

![image](https://user-images.githubusercontent.com/29157027/89473180-7e4b5880-d73f-11ea-8d33-a970c5955faf.png)

and here's some REPL tomfoolery:

![image](https://user-images.githubusercontent.com/29157027/89473837-2e6d9100-d741-11ea-9c53-4801cc94e4c9.png)

**Comment by cormullion** [comment]
@MasonProtter Thanks - that's looking good! What terminal is it? I see you're not getting the contextual alternates by default. (eg `->` to `→`).

**Comment by MasonProtter** [comment]
> @MasonProtter Thanks - that's looking good! What terminal is it? I see you're not getting the contextual alternates by default. (eg `->` to `→`).

Hi @cormullion , that wasn't a terminal it was the emacs GUI and getting ligature support in the emacs GUI is possible, but I never learned how to do it. Here's evidence that the ligatures are working properly in Konsole. 

![image](https://user-images.githubusercontent.com/29157027/89556128-2c054880-d7ce-11ea-8744-3b12442438d9.png)

**Comment by cormullion** [comment]
@MasonProtter Probably a few lines of LISP should do the trick.. :)

**Comment by apparluk** [comment]
[UTF-8 SAMPLER](http://www.columbia.edu/~fdc/utf8/) (Columbia University)

**Comment by cormullion** [comment]
@apparluk Thanks - I'm really looking to see what I can't see from my computer - namely how it looks on other people's.

**Comment by apparluk** [comment]
I compiled `st` on Slackware 14.2 to see the font rendering.

config.def.h can be modified

```
bash-4.3$ cd st-0.8.4
bash-4.3$ sed -i "s|Liberation |Julia|" config.def.h
bash-4.3$ grep Julia config.def.h
static char *font = "JuliaMono:pixelsize=12:antialias=true:autohint=true";
bash-4.3$ CFLAGS="-O2 -march=i586 -mtune=i686" make

...

bash-4.3$ ./st &
[1] 4813
bash-4.3$ 
```

[https://st.suckless.org/](https://st.suckless.org/)
1,024x600

![st](https://user-images.githubusercontent.com/52227507/90200044-b8b79400-ddd6-11ea-8756-7409c32cc6ef.png)

**Comment by EarthGoddessDude** [comment]
OS: Linux Mint 19.3 Tricia x86_64
Host: Aspire E5-575 V1.25
Resolution: 1920x1080
Editor: VS Code
Font Size: 14
![julia-mono](https://user-images.githubusercontent.com/51887608/90208292-86963a00-ddb6-11ea-975b-3731273b5443.png)

**Comment by cormullion** [comment]
@EarthGoddessDude Thanks - that looks pretty acceptable, VS-Code does a good job I think.

@apparluk Thanks - considering the low resolution that's working quite well. But this won't be the best font for this environment... 😥

**Comment by nico202** [comment]
@MasonProtter Hi! In emacs (on gnu/linux) I could enable ligatures on julia mono with code found for [fira font](https://github.com/tonsky/FiraCode/wiki/Emacs-instructions#using-ligatureel) (the one using set-char-table-range worked).

However, in general, my emacs window is rendering juliamono too bold (compared to your screenshot/rendering in other programs).  How did you set it? With
```
(set-frame-font "JuliaMono 8")
```
this is the result
![juliamono](https://user-images.githubusercontent.com/8214542/98338733-ed6c6d80-200a-11eb-91ed-086378cd3683.png)

**Comment by cormullion** [comment]
No idea about emacs, but there's a Light version of the font. But much depends on the quality of the environment you have...

**Comment by nico202** [comment]
The problem is that fc-match select the medium variant instead of the regular:

```
fc-match -v juliamono-20:weight=normal |grep file:
        file: "/home/nixo/.guix-profile/share/fonts/truetype/JuliaMono-Medium.ttf"(w)
```

**Comment by cormullion** [comment]
Errr... I have only five minutes of emacs experience, so I can't really help. A wild suggestion is to delete all the weights you don't need, leave just the one, and see if you can persuade your system to reluctantly use the only one that matches... ¯\\\_(ツ)_/¯

**Comment by nico202** [comment]
I'm not 100% sure, but opening the JuliaMono-Medium with fontforge, element -> fontinfo -> ttf names -> styles (subfamily) shows Regular.  Shouldn't it be "Medium"?

**Comment by nico202** [comment]
Hack Bold -> Bold. Hack Regular -> Regular, JuliaMono Regular -> Regular...

**Comment by cormullion** [comment]
FontForge says Regular whatever you load:

<img width="781" alt="Screenshot 2020-11-07 at 18 29 04" src="https://user-images.githubusercontent.com/52289/98448862-27cb2d00-2127-11eb-9601-526b458283ef.png">

When created, the family is "JuliaMono".

<img width="829" alt="Screenshot 2020-11-07 at 18 30 32" src="https://user-images.githubusercontent.com/52289/98448886-56e19e80-2127-11eb-836c-dd765516e70e.png">

... there's no other box to type stuff. 

Probably, when you open a single font in FontForge, it has no idea whether that one font is part of a family. Whereas, when created, the various instances are created as a family - they have to be, since they're interpolated masters called "Light", "Regular", "Medium", and so on.

**Comment by nico202** [comment]
Are you sure it's the same for other fonts, and not only for juliamono?
Here's what I get with Hack Bold:
![2020-11-07-210226_1280x800_scrot](https://user-images.githubusercontent.com/8214542/98450378-aa121c00-213c-11eb-8e53-38621cedb027.png)

In your second screenshot, maybe it should be a custom parameter?

**Comment by cormullion** [comment]
Who knows ... it works everywhere else... 🤷

**Comment by nico202** [comment]
Well yes, but fc-cache is from fontconfig, and it returns the wrong font.  If manually setting the weight does works, that does not mean that the subfamily is correct.
In emacs, for example, I can set the right subfamily (i.e.: using the regular variant) by specifying the weight to book.  But if it automatically sets the wrong one, maybe it's something related to the font itself (in hack is specified here: https://github.com/source-foundry/Hack/blob/1eddf943125a3f06945b86dbb7f55704a517331c/source/Hack-Regular.ufo/fontinfo.plist#L94).

But I do not know enough about fonts, maybe someone else.
By the way, will you share the sources you use to build TTFs?

**Comment by cormullion** [comment]
Sadly I don't really have the resources or skills to troubleshoot Linux or Windows issues, to be honest, and this little experiment designed for a q0 minute JuliaCon presentation probably won't satisfy everyone's needs.

Hack's a fine font, developed with open source tools by folks who know what they're doing - you may prefer to stick with them. 😂

**Comment by nico202** [comment]
But I like JuliaMono, and with the workaround (weight=book) is working fine, I just wanted to fix this.  But it might be my setup broken as well.

(By the way, JuliaMono is now in guix repository: https://issues.guix.gnu.org/44410)
