### ISSUE TITLE
Backticks are top-heavy

### ISSUE THREAD

**Issue by waldyrious** [cormullion/juliamono#50]
Extracting a [comment](https://github.com/cormullion/juliamono/issues/27#issuecomment-677569420) from #27, because I believe it to be a valid suggestion that could be discussed separately:

> I think the only complaint I have is that `` ` `` looks slightly "heavier" than `'` (seems to be slightly wider at the top?):
>
> ![screenshot](https://user-images.githubusercontent.com/6735977/90765151-bdee7480-e2e9-11ea-9482-6ff44705fa1e.png)

Besides being objectively wider, the fact that it's a diagonal stroke makes it not pixel-aligned, which adds to its heavier appearance. I do like the larger backticks (with a height matching that of `'` and `"`), but I'd prefer if they weren't so top-heavy.

Here's a screenshot showing what I see (VSCode, 13" macbook, JuliaMono 0.017):

![](https://user-images.githubusercontent.com/478237/94802075-eab0a400-03de-11eb-8f6b-382a06dbad56.png)

**Comment by cormullion** [comment]
Yes, that's quite an interesting point!

On lower-resolution displays, diagonal glyphs seem to lose some thickness. For you and me, with high-quality displays, it's true that the back quote is slightly heavier. But on Windows, the difference might be less. It's hard to replicate, but I can get this, with some effort, on my Mac:

<img width="416" alt="Screenshot 2020-10-02 at 10 16 05" src="https://user-images.githubusercontent.com/52289/94907730-7e927680-0498-11eb-9043-86bebb8fe978.png">

and the difference in weight has definitely decreased.

If everyone was using Retina Macs, I'd certainly be happy to do this. But if I do, I might get comments from non-Mac users that the back quotes are too thin... ;)

Which means I'm undecided... 🤔

**Comment by waldyrious** [comment]
I see what you mean, and indeed that's hard to assess. It occurred to me that binarizing your image could provide a more objective measure of which glyph would appear heavier; here are some examples with the threshold set at different levels, close to the midpoint between 0 and 255:

<img width="100" src="https://user-images.githubusercontent.com/478237/94922300-e0aba580-04b1-11eb-9061-28271c2c5b9c.png"/> <img width="100" src="https://user-images.githubusercontent.com/478237/94922301-e2756900-04b1-11eb-9e7f-2089f6c67d8e.png"/> <img width="100" src="https://user-images.githubusercontent.com/478237/94922302-e2756900-04b1-11eb-98a6-163ed0bc0b82.png"/> <img width="100" src="https://user-images.githubusercontent.com/478237/94922306-e30dff80-04b1-11eb-84bc-a73c670eb8db.png"/>

I would say that they still tend towards the backtick being heavier, but of course, this is no scientific evidence of human perception :) just additional data to inform this discussion.

**Comment by waldyrious** [comment]
Hey @cormullion, is there anything I can do to help move this forward?

**Comment by cormullion** [comment]
I could add a stylistic alternative for a thinner backtick - it wouldl be `ss11`. Perhaps I'll do it next week, if I get time.

**Comment by cormullion** [comment]
ss11 is in v0.023, give it a try

**Comment by waldyrious** [comment]
Looks great @cormullion! Here's what I see:

Base backtick:
![Screenshot 2020-10-23 at 13 17 38](https://user-images.githubusercontent.com/478237/97002654-3237d500-1532-11eb-8ce6-ea78a4a1971e.png)

ss11 backtick:
![Screenshot 2020-10-23 at 13 17 46](https://user-images.githubusercontent.com/478237/97002658-32d06b80-1532-11eb-96b6-8cc0250ea68b.png)

It's still more visible than the combining grave, but now it's not as overbearing, and better matches the apparent size of the single quote (yes, it's narrower, but it's also longer due to being slanted, so the "area" seems to be similar).

Thanks for the quick resolution!
