### ISSUE TITLE
Please compare with a "normal" font to highlight which problems this font solves....

### ISSUE THREAD

**Issue by sylvaticus** [cormullion/juliamono#51]
Sorry, I am not much in fonts.. in the page of the project (https://juliamono.netlify.app/) you render examples with this new font.. but it may be instructive also to show, e.g. side by side, how the same text/code is rendered with a "normal" font, to show which problems this font solve compared to just using a standard font....

Cheers...

**Comment by cormullion** [comment]
I see what you mean, but I probably won’t do this, since I’m not claiming it’s better. Besides it’s not that difficult thing for people to do for themselves — in fact most issues opened here compare JuliaMono unfavourably with FiraCode and Roboto Mono for me.  😂😂😂

**Comment by suhr** [comment]
It allows you to write `A ⋈ B ∪ C` or `a ∈ A` in monospace (something I really miss in Source Code Pro).

**Comment by suhr** [comment]
-_-

**Comment by cormullion** [comment]
People can investigate things for themselves. I won't be addressing this issue.

**Comment by knuesel** [comment]
I've started work on a script to automate the comparison of fonts, I'll let you know when I have something to show. We could decide later whether to publish the result on a dedicated site, or to integrate it on the JuliaMono website...
