### ISSUE TITLE
Number sign (hash, pound sign, octothorpe) is too low

### ISSUE THREAD

**Issue by waldyrious** [cormullion/juliamono#52]
I'm not sure if this is an explicit design decision, but the way the number sign is rendered seems a little off to me:

<img width="239" alt="Screenshot 2020-10-07 at 17 56 13" src="https://user-images.githubusercontent.com/478237/95362984-c5340680-08c6-11eb-9ea1-59c4ebeff6f3.png">

I admit that among the letters with descenders, on the right, it doesn't look off, but among uppercase letters and numbers, it seems like a noticeable drop.

For contrast, here's Roboto Mono:
<img width="240" alt="Screenshot 2020-10-07 at 17 55 25" src="https://user-images.githubusercontent.com/478237/95362977-c36a4300-08c6-11eb-893a-f0ed5e4f39bb.png">

And here's Fira Code:
<img width="246" alt="Screenshot 2020-10-07 at 17 55 43" src="https://user-images.githubusercontent.com/478237/95362982-c49b7000-08c6-11eb-83cd-5b74285ff544.png">

IMO aligning the base of the `#` character to the baseline, as these two do, works well in both contexts. Maybe JuliaMono could adopt that style as well?

**Comment by cormullion** [comment]
Makes sense - it doesn't have to align with the arithmetic operators. In general, the lowercase and punctuation marks are aligned, uppercase and numbers are higher...

**Comment by cormullion** [comment]
<img width="628" alt="Screenshot 2020-10-09 at 12 57 11" src="https://user-images.githubusercontent.com/52289/95580278-fd565900-0a2e-11eb-90e5-00475058811a.png">

**Comment by waldyrious** [comment]
The new design looks great! 👍

**Comment by waldyrious** [comment]
Confirmed fixed in [0.018](https://github.com/cormullion/juliamono/releases/tag/v0.018)! Thanks for the quick reaction. Sorry for not closing this earlier, I didn't realize you were waiting on me to do so! :)
