### ISSUE TITLE
APL character issues

### ISSUE THREAD

**Issue by mlochbaum** [cormullion/juliamono#54]
The [APL](https://en.wikipedia.org/wiki/APL_(programming_language)) programming language uses a set of mostly non-ASCII characters for built-in functionality. [Here](https://aplwiki.com/wiki/Typing_glyphs#Approaches_to_Layout_and_Input) is an example APL keymap. Julia Mono supports all the characters (hooray!) even in NARS2000 ([keymap](http://wiki.nars2000.org/index.php?title=Keyboard)), the most demanding APL I know of. The glyphs generally look okay, but there are some issues with specific glyphs and a lot of glyphs that are much smaller or lighter than a typical character. Historically (though a very long time ago), many of these glyphs were produced by overstriking—typing two characters on top of each other. In most cases the issues could be fixed by replacing a glyph with a combination of existing ones, like `⌽` with `|` and `○`.

- U+2336 `⌶` is just the wrong character. It renders as a delete key symbol when it should be "I-beam", usually a stripped-down small-caps I.
- U+233D `⌽` is a very unusual rendering; I would expect to see the bar extend past the circle just like a lowercase phi, but maybe more precisely geometrical.
- U+2372 `⍲` has its tilde cut off; it should have a full tilde like U+2371 `⍱`.
- U+236B `⍫` is extremely small.
- U+235E `⍞` in "quote quad" the quote is almost as big as the quad, making it difficult to recognize. If you're not going to expand the box, the quote should probably be cut off.
- U+2377 `⍷` is inconsistent with U+220A `∊` (which is very small), although this is something I've seen in other fonts as well.

Since they're not always obvious, here's a table of commonly recognized APL overstrikes. There are also characters with an underscore or box that Julia Mono does seem to use overstrikes for. I would say the circle (U+25CB `○`) and quad (U+2395 `⎕`) should be heavier and the quad larger to match other APL characters better.

       |~∘⋆\-¨

    ○  ⌽ ⌾⍟⍉⊖⍥
    ¨   ⍨⍤⍣
    ∆  ⍋  
    ∇  ⍒⍫
    ∧   ⍲
    ∨   ⍱
    0   ⍬
    ⊥    ⍎
    ⊤    ⍕
    ∩    ⍝
    ,        ⍪

**Comment by mlochbaum** [comment]
Thanks for taking a pass through the APL characters (and sorry for contributing to the Hacker News rush). If you decide to come back, here are the ones that I still find to be pretty out of place:

- U+220A `∊`
- U+2368 `⍨`
- U+236C `⍬`
- U+2371 `⍱` isn't too small or light like the others, but the tilde being upside-down is kind of jarring.

I would still say many of the APL characters are underweighted, but overall it looks pretty usable now.

**Comment by ssfrr** [comment]
Another minor APL character issue - the "enclose" (⊂) and "disclose" (⊃) characters don't quite align. They look fine separately, but when right next to each other you can see the issue.

![image](https://user-images.githubusercontent.com/734386/189253173-f3094055-f5a7-4421-a576-64389b07d567.png)

**Comment by cormullion** [comment]
Hi Spencer! For the upcoming 0.046 release I've recently been tweaking a few of the maths glyphs , so the APL set currently looks like this:

<img width="317" alt="Screenshot 2022-09-09 at 08 04 34" src="https://user-images.githubusercontent.com/52289/189291527-e0ab7a22-195c-4967-a050-4c0a57186178.png">

and placing 0x2282 and 0x2283 side by side (which not many languages can do, I expect) looks like this:

<img width="44" alt="Screenshot 2022-09-09 at 08 00 21" src="https://user-images.githubusercontent.com/52289/189290746-a28c0126-7e5c-4f24-a97b-e97ced66f30d.png">


It's difficult to make everything consistent with everything, unfortunately, since there are many different types of consistency possible. So it's always going to be a compromise...

**Comment by ssfrr** [comment]
That looks lovely. Thanks for all your work on this!
