### ISSUE TITLE
Incorrect position of Unicode next to a left parenthesis in LaTeX listing

### ISSUE THREAD

**Issue by mossr** [cormullion/juliamono#55]
The title makes it sound very particular, which it seems to be. Unicode characters such as `π α 𝛂 𝛉` are moved to the left one or two characters *only when they're adjacent to a left parenthesis* and *only when using a `lstlisting` environment with lualatex*. This behavior also occurs around `{` and `[`.

The characters are positioned correctly in a `verbatim` environment in the same document (compare lines 3, 5, 6, 8, or 10). Standard characters like `x` do not have this behavior (see line 7).

![image](https://user-images.githubusercontent.com/1592413/95648255-9b2b4180-0a8a-11eb-965b-fcac4d551dc8.png)

Here's the minimal LaTeX code that generates this, with "JuliaMono-Regular.tff" and "JuliaMono-Bold.tff" in the same directory:
```latex
\documentclass[twoside,11pt]{article}

\usepackage{listings}
\usepackage{xcolor}
\usepackage{fontspec}

\newfontfamily \JuliaMono {JuliaMono-Regular.ttf}[Path = ./, Extension = .ttf]
\newfontface\JuliaMonoMedium{JuliaMono-Regular}
\setmonofont{JuliaMonoMedium}[Contextuals= Alternate]
\newfontfamily\JuliaMonoBold {JuliaMono-Bold.ttf}[Path = ./, Extension = .ttf]

\lstdefinelanguage{Julia}{
    keywords=[3]{thompson_sampling, argmax, rand},
    keywords=[2]{Beta, Distributions},
    keywords=[1]{using, function, for, in, end, return},
    sensitive=true,
    morecomment=[l]{\#},
    morecomment=[n]{\#=}{=\#},
    morestring=[s]{"}{"},
    morestring=[m]{'}{'},
    alsoletter=!?
}

\lstset{
    language         = Julia,
    backgroundcolor  = \color[HTML]{F2F2F2},
    basicstyle       = \JuliaMonoMedium\small\color[HTML]{19177C},
    numberstyle      = \JuliaMono\scriptsize\color[HTML]{7F7F7F},
    keywordstyle     = [1]{\JuliaMonoBold\color[HTML]{1BA1EA}},
    keywordstyle     = [2]{\color[HTML]{0F6FA3}},
    keywordstyle     = [3]{\color[HTML]{0000FF}},
    stringstyle      = \JuliaMonoMe\color[HTML]{F5615C},
    commentstyle     = \color[HTML]{AAAAAA},
    rulecolor        = \color[HTML]{000000},
    frame=lines,
    xleftmargin=5pt,
    framexleftmargin=25pt,
    framextopmargin=4pt,
    framexbottommargin=4pt,
    tabsize=4,
    captionpos=b,
    breaklines=true,
    breakatwhitespace=false,
    showstringspaces=false,
    showspaces=false,
    showtabs=false,
    columns=fullflexible,
    keepspaces=true,
    numbers=left
}

\begin{document}

\begin{lstlisting}[language=Julia]
using Distributions

function thompson_sampling(𝛂, 𝛃, apply; T=100)
    for t in 1:T
        𝛉 = rand.(Beta.(𝛂, 𝛃))
        x = argmax(𝛉)
        r = apply(x)
        𝛂[x], 𝛃[x] = (𝛂[x] + r, 𝛃[x] + 1 - r)
    end
    return Beta.(𝛂, 𝛃)
end
\end{lstlisting}


\begin{verbatim}
using Distributions

function thompson_sampling(𝛂, 𝛃, apply; T=100)
    for t in 1:T
        𝛉 = rand.(Beta.(𝛂, 𝛃))
        x = argmax(𝛉)
        r = apply(x)
        𝛂[x], 𝛃[x] = (𝛂[x] + r, 𝛃[x] + 1 - r)
    end
    return Beta.(𝛂, 𝛃)
end    
\end{verbatim}

\end{document}
```

I tried performing ablation to pin-point the cause within the listing options with no luck. The adjacency makes the think "Contextuals=Alternate" has something to do with it, but playing around there doesn't change things.

Any thoughts? <sup>(by the way, I realized today you made this font—after I gushed over your noisy landscapes)</sup>

---

EDIT: I'm on Windows 10.

**Comment by cormullion** [comment]
How are you typing the alpha and beta? Can you get the Unicodes from Julia? I'm seeing this with `\alpha` etc...:

<img width="728" alt="Screenshot 2020-10-10 at 09 17 08" src="https://user-images.githubusercontent.com/52289/95650125-61355c00-0ad9-11eb-9f71-c01e30741d79.png">

**Comment by mossr** [comment]
I type the boldface alpha and beta using the Julia Sublime Text bindings (\bfalpha and \bfbeta). I just tried to copy \alpha from the REPL with the same repositioning behavior.

In your example, is that in a `lstlisting` LaTeX environment? Because `verbatim` works fine with the identical block of code, but `lstlisting` causes the repositioning.

**Comment by mossr** [comment]
I figured it out!

Long story short, the `listings` package will not handle Unicode nicely without some deliberate character code settings.
- If you're interested in reading further: https://analyzethedatanotthedrivel.org/2011/08/15/typesetting-utf8-apl-code-with-the-latex-lstlisting-package/

I've since created a repo, [julia-mono-listings](), with that packages up the fixes. I also included a [test.pdf](https://github.com/mossr/julia-mono-listings/blob/master/test/test.pdf) of all the Unicode characters listed on [Julia's docs](https://docs.julialang.org/en/v1/manual/unicode-input/) and put them in a `lstlisting` environment to visually inspect that they all work properly.

**Comment by cormullion** [comment]
That's awesome! Thanks. And it wasn't my fault?! 🤣🤣

I'll add a link to that from the readme too...

**Comment by mossr** [comment]
Fixed with [julia-mono-listings](https://github.com/mossr/julia-mono-listings)
