### ISSUE TITLE
Better APL symbols

### ISSUE THREAD

**Issue by suhr** [cormullion/juliamono#57]
Some APL symbols look rather weird (`⌽`), and overall glyph shape is not consistent (`∨∧⍱⍲`, `⍉⌽⊖`).

Take a look at APL385 font as a reference. Also, see a related issue for Pragmata Pro: https://github.com/fabrizioschiavi/pragmatapro/issues/64.

**Comment by suhr** [comment]
-_-

**Comment by cormullion** [comment]
I won't be spending any more time on the APL symbols. I hope you can find another font that has better versions for your APL code.

**Comment by suhr** [comment]
Then feel free to close it with `wontfix` label.
