### ISSUE TITLE
Only 1 small change is needed to support Slovak language

### ISSUE THREAD

**Issue by mirosval** [cormullion/juliamono#58]
Hey, the font looks awesome1 I think I will switch to it from Hasklug.

Slovak is not listed under supported languages, but there is only one small change that's needed for that! 

The letter Ľ [ľ ](https://en.wikipedia.org/wiki/%C4%BD) should be rendered like it is here, but with Julia Mono it is rendered with a caron same as e.g. [č](https://en.wikipedia.org/wiki/%C4%8C). This is not to be confused with [ĺ](https://en.wikipedia.org/w/index.php?title=%C4%B9&redirect=no) which is an L with acute accent (correct)

<img width="269" alt="Screenshot 2020-10-10 at 13 18 21" src="https://user-images.githubusercontent.com/1315417/95653737-352ad280-0afb-11eb-8513-c52fd1a8a166.png">

https://en.wikipedia.org/wiki/Slovak_orthography

**Comment by orr721** [comment]
+1 this is a strange omission in otherwise great font

**Comment by cormullion** [comment]
Yes I did the capital but not the lowercase...  :) 

It's not that strange an omission, I gather - https://www.typotheque.com/articles/lcaron... :)

**Comment by orr721** [comment]
That's a great story. He's a famous slovak typographer and graphic designer, did all the typography for Vienna airport.

I meant strange in the sense that you got lowercase t-caron, d-caron and t-acute right which pose a similar problem. Thank you for all your work. BTW consider an "About" section on the website for some self-promotion, I have not seen any.. 😄
