### ISSUE TITLE
Which is the latest version?

### ISSUE THREAD

**Issue by fabiosirna** [cormullion/juliamono#59]
I've downloaded from the website and there is zip file juliamono-ttf.zip with duplicate files.
So I'm wondering, which is the latest version? The one in the main folder or the ones in the zip file? 
Both are from 2 days ago.

**Comment by cormullion** [comment]
Yes, some people (some platforms...) can't cope with ZIP files, or don't want to install all the fonts, or prefer to keep everything in a single file, or like to move a download first then unzip it, or whatever. Files should be the same... ¯\\\_(ツ)_/¯
