### ISSUE TITLE
more symmetrical < and >

### ISSUE THREAD

**Issue by JeffBezanson** [cormullion/juliamono#6]
![ltgt](https://user-images.githubusercontent.com/744556/89057852-55385b80-d32c-11ea-8d88-48307680bf98.png)
It looks to me like the `<` and `>` are not quite symmetrical around the x axis, and so they are not "aimed" at the center of the colon in these operators, but a bit low.

**Comment by cormullion** [comment]
I think you're right.

<img width="776" alt="Screenshot 2020-07-31 at 18 31 01" src="https://user-images.githubusercontent.com/52289/89061086-ff7ba780-d35b-11ea-96bd-3fab4de104e2.png">

(You're wasted doing this computer lark with eyesight that good!)

**Comment by cormullion** [comment]
Hopefully fixed in 0.004 

<img width="219" alt="Screenshot 2020-08-02 at 18 07 12" src="https://user-images.githubusercontent.com/52289/89128091-071d8680-d4eb-11ea-9580-ccc1ea34c3d3.png">
