### ISSUE TITLE
Brackets should match the height of a vertical bar

### ISSUE THREAD

**Issue by goerz** [cormullion/juliamono#60]
Angled brackets (U+27E8, U+27E8) should match the height of the vertical bar / pipe symbol (U+007C). This is because of their common use in bra-ket notation in quantum mechanics and linear algebra, e.g.

```
|0⟩
⟨Φ|Ψ⟩
```

Other brackets and parentheses also should match the same height.

The standard ascii ones `([{` do, but most other unicode ones like `｟⟨⟪⟦〘⦗⦉⦑` do not (nor are the internally consistent).

This is using the latest homebrew release (0.018) rendering in iTerm at size 12.

**Comment by goerz** [comment]
As a screenshot:

![Screenshot_2020-10-10_09 42 15_kf3Ve3](https://user-images.githubusercontent.com/112306/95656546-187fa200-0add-11eb-9475-330bc22f4f04.png)

**Comment by cormullion** [comment]
Made a few tweaks. Thanks!
