### ISSUE TITLE
Hat accent collides with letters

### ISSUE THREAD

**Issue by goerz** [cormullion/juliamono#63]
For a lot of letters, the hat accent e.g. in `Ĥμ̂` collides with the letter under it:

![image](https://user-images.githubusercontent.com/112306/95679607-fa2faa00-0ba1-11eb-9bf4-f25f2d914c35.png)

Even at small sizes, there should always be visible space between the letter and the hat, or the H could easily be confused with an A, and the μ with a ρ. Narrowing the hat so that its edges are between the two ascenders might also improve readability.

The screenshot is with today's Julia-Mono 0.019 in iTerm at a 12px font size. If I increase the font size, *eventually* a gap will appear under the accent, but only if I go to large sizes >25, and even then the gap is tiny.

**Comment by goerz** [comment]
Looking at some other fonts like Menlo I actually think that narrowing the hat slightly contributes much more to readability than the vertical gap

**Comment by cormullion** [comment]
I think this is fixed (more or less) as of v.020.

<img width="119" alt="Screenshot 2020-10-18 at 16 37 47" src="https://user-images.githubusercontent.com/52289/96372772-74db6500-1160-11eb-91e8-182bc9d02449.png">

**Comment by goerz** [comment]
The latest version is a noticeable improvement. At smaller sizes, I'm still having a little bit of trouble seeing the gap, so it might still be something to experiment with in future iterations. Feel free to close, or keep open if you want to work on this further.

I just wanted to say, though: this is a very nice font! You're doing great work, and I'm very impressed with your responsiveness to issues! Thanks!

**Comment by cormullion** [comment]
Thanks! It's an ongoing war between raising the accents to give them breathing room and lowering them to stop them clipping (eg issue 28)... :) Also you can double-stack them:

<img width="66" alt="Screenshot 2020-10-23 at 18 17 03" src="https://user-images.githubusercontent.com/52289/97033918-fade1e00-155b-11eb-91c4-82dd5841898b.png">

**Comment by goerz** [comment]
Yes, good point! Have you considered the option to narrow the hat?

This is a screenshot of Menlo, which I've been using before trying out Julia Mono:
![Screenshot_2020-10-24_09 41 57_R5V3Yk](https://user-images.githubusercontent.com/112306/97083344-4be22680-15dd-11eb-8e14-158c9c1390a7.png)

This seems to be highly readable at small font sizes, where there's effectively no vertical gap between the letter and the hat.

As for stacked accents, I'm definitely interested in those as well. In iTerm2, I'm not really seeing any clipping, although the accents do collide with descenders from letters in the previous line:

![Screenshot_2020-10-24_09 52 00_KIWojt](https://user-images.githubusercontent.com/112306/97083507-9a43f500-15de-11eb-8d58-52818481a2c3.png)

This seems ok to me: there's a limit to what I would reasonably expect in a command line environment.

Just for context, I'm coming at this as the author of a Python computer algebra system for quantum mechanics ([Qalgebra](https://github.com/QAlgebra/qalgebra)) that [heavily uses unicode output](https://github.com/QAlgebra/qalgebra/blob/master/tests/printing/test_unicode_printing.py) in the terminal to match standard conventions in quantum mechanics.

Hence the above examples:

* `Ĥ`: A Hamiltonian operator

* `μ̂`: A dipole operator

* `L̂̂`: A Liouville super-operator (this is supposed to be a double hat, my browser doesn't seem to render that correctly with whatever font it's using)

* `ℒ̂̂`: Alternative common convention to set Liouville super-operator (script-L with double hat)

* `Ĥ̃`: A transformed Hamiltonian operator (hat plus tilde)

* `Ĥ̇`: time-derivative of a Hamiltonian operator (hat plus dot)

* `|Ψ⟩`: A quantum state ("ket"), cf. #60

Personally, I tend to avoid the double-hats for super-operators (it's a bit much, and rarely renders correctly, see above), but the other letters would definitely be used, that simple hat most commonly.

**Comment by cormullion** [comment]
Your screenshot reminded me that I hadn't set mark anchors for script characters at all (apparently it's not considered usual), so a future release should at least have those set:

<img width="135" alt="Screenshot 2020-10-25 at 08 12 21" src="https://user-images.githubusercontent.com/52289/97102036-f750b100-1699-11eb-8f76-c97f513b6916.png">

**Comment by cormullion** [comment]
The script characters now have their correct anchor marks:

<img width="783" alt="Screenshot 2020-11-01 at 09 09 11" src="https://user-images.githubusercontent.com/52289/97798872-09929800-1c22-11eb-9cc1-ba35b78e4546.png">

although I'm guessing some will be clipped in some environments .... 😃
