### ISSUE TITLE
Problem with \uE0A0 and \uE0B3-\uE0BB symbols

### ISSUE THREAD

**Issue by cpkio** [cormullion/juliamono#64]
v0.019

\uE0A0 is somewhere down below and not seen. Other are vertically misplaced as it seems.

## JuliaMono
![2020-10-11_165506](https://user-images.githubusercontent.com/1917113/95680446-85309480-0be2-11eb-9d62-e9708ce872c6.png)

## Iosevka Term
![2020-10-11_165520](https://user-images.githubusercontent.com/1917113/95680455-937eb080-0be2-11eb-8cf8-b232bc4e3329.png)

**Comment by dwaynebradley** [comment]
I see the same issue on E0A0...

JuliaMono:
![image](https://user-images.githubusercontent.com/14277962/96667025-3b545680-1326-11eb-9271-7ea9b0546f02.png)

JetBrains Mono:
![image](https://user-images.githubusercontent.com/14277962/96667056-4effbd00-1326-11eb-9c7c-7174d2ae28e9.png)

**Comment by cormullion** [comment]
I"m having trouble reproducing this on MacOS. Here's that part of the private use area::

<img width="781" alt="Screenshot 2020-10-21 at 10 39 55" src="https://user-images.githubusercontent.com/52289/96702618-d7fc1000-1389-11eb-8fbb-2c945f3dd9b1.png">

Could be worth checking this on the next release, in case some general adjustments to font parameters have had a beneficial effect on this.

**Comment by cpkio** [comment]
Let's not judge by font previewing programs in general. In some font viewers the glyph is seen, but it still not displaying correctly in editors. In Sublime Text is looks like this:
![2020-10-21_141051](https://user-images.githubusercontent.com/1917113/96712106-413e4c00-13a7-11eb-97b6-499e514f7905.png)

**Comment by cormullion** [comment]
Still can't reproduce here.

SublimeText 3.2, JuliaMono v0.022, MacOS Catatonia:

<img width="501" alt="Screenshot 2020-10-21 at 12 45 09" src="https://user-images.githubusercontent.com/52289/96715300-45646c80-139b-11eb-9350-16da9472dd02.png">

**Comment by dwaynebradley** [comment]
Release v0.024 appears to have fixed this...at least for me.

JuliaMono:
![image](https://user-images.githubusercontent.com/14277962/97456931-a9dd7980-190f-11eb-8671-26d70031044a.png)


JetBrains Mono:
![image](https://user-images.githubusercontent.com/14277962/97456814-93372280-190f-11eb-8011-d306a1682670.png)

**Comment by cormullion** [comment]
Thanks!
