### ISSUE TITLE
Differentiate \phi and \Phi more

### ISSUE THREAD

**Issue by MasonProtter** [cormullion/juliamono#68]
In the spirit of #26, it'd be good if we also gave `\phi` and `\Phi` a bit more differentiation 

![Screen Shot 2020-10-18 at 7 22 10 PM](https://user-images.githubusercontent.com/29157027/96391814-487f1300-1177-11eb-8317-68addfe96453.png)
_______

I realized and acknowledge that you're no longer actively working on this, but I felt it might be a good idea to throw it out there in case someone wants to make a PR. Feel free to close it though if you don't want issues like this clogging up. ❤️

**Comment by cormullion** [comment]
as it's you

<img width="103" alt="Screenshot 2020-10-19 at 15 10 21" src="https://user-images.githubusercontent.com/52289/96462237-44a5cc00-121d-11eb-897b-9d069e94703f.png">

looks like the only way

**Comment by MasonProtter** [comment]
Mhm, I recall you don't like serifs, but for `\Phi` it feels like a canonical part of the character to me.

**Comment by cormullion** [comment]
fixed in v0.023 I hope
