### ISSUE TITLE
JuliaMono is a great font, and it would be nice if it were included in Google Fonts

### ISSUE THREAD

**Issue by bravoecho** [cormullion/juliamono#69]
Hi @cormullion 
I'm using JuliaMono daily and I think it's one of the best fonts for code.
I would like to use it in my Google Docs documents.
Would you consider submitting it to Google Fonts? I'm sure they would be thrilled to include it.

**Comment by cormullion** [comment]
Hi, thanks, I'm happy it's useful.

There's quite a lot of work involved in getting a font into Google fonts (https://github.com/google/fonts/blob/master/CONTRIBUTING.md). They don't just allow you to upload the TTF font files, they require a complete workflow with specific software, scripted build processes, complicated checking programs, and so it would involve some work to get them up there. 

The process can also take a long time - even if the people in charge are in favour. (Here's a glimpse at what happened when FiraCode wanted to be added: https://github.com/google/fonts/issues/1460. The developer and his users had to work quite hard to get it in.)

So while I can see this might be a good idea, I'm not sure whether it will happen in the near future. I'll label this as `enhancement` though... :)

**Comment by cormullion** [comment]
I had another look at the whole Google font requirements, and there are quite a few that are currently problematic:

- "must be of good quality" :) 
- name "JuliaMono" not allowed (don't know why yet)
- version must be >= 1.0 (one day it will be)
- must be built with a scripted build process (I just export)
- must be built with `fontmake` (it isn't)
- all font files within the family must have the same Unicode character set (so the -Latin versions aren't allowed) 
- can't have a ZIP file in the directory
- must pass the Font Bakery checks (currently fails about 10)
 
So I'm still not sure whether it will happen in the near future.

**Comment by bravoecho** [comment]
Oh wow, that is very Google of them! 
Thank you for letting me know @cormullion , very kind of you to explore the idea. 

You are right, it's probably not worth it. JuliaMono is such a good font that I'm sure the word of mouth will be more than enough to popularise it going forward. 

I'm using it full time, not because of the vast collection of glyphs, but because it has excellent readability in general, especially tricky/ambiguous symbols, and it has virtually perfect proportions which allow me to maximise the number of lines and columns like no other font so far. 

So rest assured I won't miss any opportunity to recommend it to anyone looking to improve their monospace life 🙂

**Comment by cormullion** [comment]
Thanks so much, I appreciate your comments a lot.

**Comment by moyogo** [comment]
What source files do you have?

**Comment by cormullion** [comment]
The source is a .glyphs file.

**Comment by moyogo** [comment]
I don't see that file in the repository. If you add it, or if it's there, then it can be used by fontmake to buid TTFs.

These are just my personal observations:

> I had another look at the whole Google font requirements, and there are quite a few that are currently problematic:
> 
>     * "must be of good quality" :)

There are a few major issues in the glyph set, some design is not consistent or some glyphs are take from other fonts without documentation of origin, for example:
- Ɡ /uniA7AC is copied from an undocumented serif font
- /Iacute_J.loclNLD doesn't match /IJ even though, it either is scaled down somehow or from another font

I guess most of the effort for some glyphs was Unicode character support. The most common characters are much better.

>     * name "JuliaMono" not allowed (don't know why yet)

If I recall correctly it should be "Julia Mono".

>     * version must be >= 1.0 (one day it will be)
> 
>     * must be built with a scripted build process (I just export)
> 
>     * must be built with `fontmake` (it isn't)

This should be feasible with fontmake and the glyphs source file.

>     * all font files within the family must have the same Unicode character set (so the -Latin versions aren't allowed)

The Latin subset doesn’t have to be used by Google Fonts.

>     * can't have a ZIP file in the directory

It's a much better practice to have the zip as a Github release.

>     * must pass the Font Bakery checks (currently fails about 10)
> 

Depending on the checks that fail, it may be easy to fix.

> So I'm still not sure whether it will happen in the near future.

**Comment by cormullion** [comment]
Some of the characters I wasn't familiar with were traced over the Unicode illustrations (eg https://www.unicode.org/Public/13.0.0/charts/CodeCharts.pdf).

I won't be putting much more work into this font (lockdown won't last forever!) or into adopting a Google-font-oriented workflow. But thanks for the comments!

**Comment by moyogo** [comment]
> Some of the characters I weren't familiar with were traced over the Unicode illustrations (eg https://www.unicode.org/Public/13.0.0/charts/CodeCharts.pdf).
> 
> I won't be putting much more work into this font (lockdown won't last forever!) or into adopting a Google-font-oriented workflow. But thanks for the comments!

OK. I'd recommend putting the glyphs file in the repository. I understand it may be very large but that would be helpful to anyone who wants to contribute or to fork the fonts.
