### ISSUE TITLE
WIP: TrueType hinting

### ISSUE THREAD

**Issue by cormullion** [cormullion/juliamono#7]
So as from v0.003 I've started adding TrueType hints, which I was hoping not to have to do - in about 20 year's time it shouldn't be needed at all, but as of now it appears to be useful for improving rendering at lower resolutions...

I'm hoping this just improves clarity in all environments with no drawbacks, but please tell me about any regressions.

In case you're wondering what this involves: you have to persuade the relevant pixels on the screen grid to change color since there's not enough resolution to show the real shapes.

<img width="546" alt="Screenshot 2020-08-02 at 18 21 22" src="https://user-images.githubusercontent.com/52289/89128347-0128a500-d4ed-11ea-8fc1-309f4cc7bcbd.png">

I expect this to take some time... :)

**Comment by simeonschaub** [comment]
Wow, awesome! This fixes all rendering issues for me.
