### ISSUE TITLE
Make standard U+002D dash shorter than U+2013 en dash

### ISSUE THREAD

**Issue by sveniu** [cormullion/juliamono#70]
Please consider making U+002D HYPHEN-MINUS shorter than the U+2013 EN DASH, possibly by swapping them.

Current behaviour: Shortest to longest dash is U+2013, U+002D, U+2014.

Desired behaviour: Shortest to longest dash is U+002D, U+2013, U+2014.

Motivation: The current U+002D character can be mistaken for an en or em dash due to its arguably excessive length. This mistake is often substantiated by text processors (Wordpress springs to mind) that automatically reformat a double HYPHEN-MINUS to an en or em character. The double HYPHEN-MINUS is ubiquitous in command line processing, and there are plenty of instances where this has caused trouble for direct copy-pasting of command lines. This "double HYPHEN-MINUS to en or em dash" behaviour has made at least myself sensitive to faulty dashes in monospace fonts, prompting a double take and/or hex dump to verify the dash type.

A quick (partial) survey shows the same behaviour only in the Mononoki typeface, i.e. there's fairly strong precedence for having HYPHEN-MINUS be shorter than EN DASH, but there might be considerations at play that I am not aware of, so please excuse my ignorance if so.

Current JuliaMono output:
![juliamono-dashes-2](https://user-images.githubusercontent.com/487654/96867011-75c80b80-146c-11eb-978f-044678a009b8.png)

**Comment by cormullion** [comment]
Hi, I remember you asking this... 

It's a shame that the hyphen/minus has two different uses, and that programming languages haven't used a proper minus sign and left the hyphens to strings and text. I don't want to make the minus  too small - after all, you don't get hyphens in most code (except in strings).

So the v0.023 design is like this:

<img width="173" alt="Screenshot 2020-10-22 at 16 47 26" src="https://user-images.githubusercontent.com/52289/96897362-6b1a7000-1486-11eb-9f14-fa613d16cfa6.png">

where the en dash and em dash are slightly thinner and slightly tilted over, like an italic. The difference will still be pretty sutle, though  - especially on low-res screens...

**Comment by sveniu** [comment]
I think that design is looking promising. Looking forward to it. Feel free to close this issue.
