### ISSUE TITLE
Where did `/webfonts` go?

### ISSUE THREAD

**Issue by fonsp** [cormullion/juliamono#71]
Pluto and the demo page won't be able to use the fonts I think

**Comment by cormullion** [comment]
Ah, yes, I had problems with Netlify (basically there was too much traffic and I ran out of bandwidth, so the site was taken down...) 

Sorry!

**Comment by fonsp** [comment]
Thanks! Good to hear that you are getting too much traffic!

**Comment by fredrikekre** [comment]
> Ah, yes, I had problems with Netlify (basically there was too much traffic and I ran out of bandwidth, so the site was taken down...)

Perhaps we can host it from `julialang.org` somewhere?
