### ISSUE TITLE
Putty text spacing problem

### ISSUE THREAD

**Issue by tk-nguyen** [cormullion/juliamono#72]
Hi! I've been using this font for a month and loving it so far! But there's a problem with v0.024, when I installed it and used putty this font caused weird text spacing on the terminal, like in the photo below:
![image](https://user-images.githubusercontent.com/39090621/97098669-33900b80-16b2-11eb-85da-6606460936c5.png)
Bear in mind the window size is still 80x24.
I tried to install v0.022, and it worked flawlessly. So I think the problem is caused by your changes in v0.023.

**Comment by cormullion** [comment]
Does putty have any line spacing or line height controls? 

The font's values before v.0.023 were wrong, according to the font validator `fontbakery`, so I adjusted them.( I knew it would break something though.... Every terminal and every editor has it's own idea of how to draw text... :( )

On the plus side, presumably there won't be any clipping of characters with accents...

**Comment by tk-nguyen** [comment]
I don't think so. Searching the internet I found someone with the same problem [here](https://stackoverflow.com/questions/46054645/using-inconsolata-font-in-putty-too-much-line-spacing). I also found an issue on the (Inconsolata repo)[https://github.com/googlefonts/Inconsolata/issues/35]. Hope it helps!

**Comment by cormullion** [comment]
Yes - that's very helpful, especially raphlinus' comments, it's good to know that I'm not the only one struggling to accommodate all the conflicting requirements of the OpenType system.  There are plenty of terminals and plenty of fonts - not surprising they don't all work perfectly together...

**Comment by cormullion** [comment]
Are you tied to putty by hardware limitations? I think some other terminals have line height adjustment, such as kitty.

**Comment by tk-nguyen** [comment]
This is just putty on Windows on my home machine. I'm already using your font with kitty on my work laptop, and it's working really well! I guess I will just use v0.022 on my Windows machine. Thank you for creating this font!

**Comment by cormullion** [comment]
Thanks for using it😂
