### ISSUE TITLE
Backslash looking very funny in comment

### ISSUE THREAD

**Issue by KronosTheLate** [cormullion/juliamono#73]
Code comments are indented by default, at least to me in VSCode. This causes a problem with JuliaMono, which I think is fully described by the screenshot below:
![image](https://user-images.githubusercontent.com/61620837/97602167-4a649400-1a0b-11eb-900d-f741da8b49a0.png)

I like julia mono (a lot. Thank you for it), but I find this behaviour to be sub-optimal :/

Another not really important thing - I think it was fun to have emojis in the font, which they were by default. Would that be hard to implement? I imagine that they can simply be copied, and if one can create a variable with the perfect emoji as name, it is just pure art. I have never done it, but I like the possibility of it happening ^_^

Having read the default text inserted when one opens an issue, I am expecting nothing. Thanks for what you have done so far

**Comment by cormullion** [comment]
Hi there! Thanks for your comments!

As regards the first issue, you're seeing the bad effect of the artificial italicizing of normal text, which is done mechanically with no regard to whether it looks good... So the backslash has been italicized, and that's made it look much straighter.

I remember one of the first things I did when I tested in VSCode was to work out how to disable this pseudo-italic. I found some JSON text which you can paste in to settings.json which disables this nasty slanting...

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": [
                "comment",
                "comment.block",
                "comment.block.documentation",
                "comment.line",
                "constant",
                "constant.character",
                "constant.character.escape",
                "constant.numeric",
                "constant.numeric.integer",
                "constant.numeric.float",
                "constant.numeric.hex",
                "constant.numeric.octal",
                "constant.other",
                "constant.regexp",
                "constant.rgb-value",
                "emphasis",
                "entity",
                "entity.name",
                "entity.name.class",
                "entity.name.function",
                "entity.name.method",
                "entity.name.section",
                "entity.name.selector",
                "entity.name.tag",
                "entity.name.type",
                "entity.other",
                "entity.other.attribute-name",
                "entity.other.inherited-class",
                "invalid",
                "invalid.deprecated",
                "invalid.illegal",
                "keyword",
                "keyword.control",
                "keyword.operator",
                "keyword.operator.new",
                "keyword.operator.assignment",
                "keyword.operator.arithmetic",
                "keyword.operator.logical",
                "keyword.other",
                "markup",
                "markup.bold",
                "markup.changed",
                "markup.deleted",
                "markup.heading",
                "markup.inline.raw",
                "markup.inserted",
                "markup.italic",
                "markup.list",
                "markup.list.numbered",
                "markup.list.unnumbered",
                "markup.other",
                "markup.quote",
                "markup.raw",
                "markup.underline",
                "markup.underline.link",
                "meta",
                "meta.block",
                "meta.cast",
                "meta.class",
                "meta.function",
                "meta.function-call",
                "meta.preprocessor",
                "meta.return-type",
                "meta.selector",
                "meta.tag",
                "meta.type.annotation",
                "meta.type",
                "punctuation.definition.string.begin",
                "punctuation.definition.string.end",
                "punctuation.separator",
                "punctuation.separator.continuation",
                "punctuation.terminator",
                "storage",
                "storage.modifier",
                "storage.type",
                "string",
                "string.interpolated",
                "string.other",
                "string.quoted",
                "string.quoted.double",
                "string.quoted.other",
                "string.quoted.single",
                "string.quoted.triple",
                "string.regexp",
                "string.unquoted",
                "strong",
                "support",
                "support.class",
                "support.constant",
                "support.function",
                "support.other",
                "support.type",
                "support.type.property-name",
                "support.variable",
                "variable",
                "variable.language",
                "variable.name",
                "variable.other",
                "variable.other.readwrite",
                "variable.parameter"
            ],
            "settings": {
                "fontStyle": ""
            }
        }
    ]
},
```

There may be other/better ways, but I didn't look for them. I can't think of another solution at the moment.

As regards emoji, you should be able to see all the emoji and use JuliaMono - the OS should be smart enough to look for the former when the latter doesn't have it.

In this screenshot you can see VSCode (I'm on a Mac) switching rapidly between the Emoji font and JuliaMono (🙏 is followed by some ornaments and ampersands I added to JuliaMono, then it switched back to do 🚀 and the following emoji).

<img width="1329" alt="Screenshot 2020-10-29 at 16 48 41" src="https://user-images.githubusercontent.com/52289/97605508-9e20ae80-1a06-11eb-960a-ef07f162f315.png">

Making all those emojis keeps hundreds of folks in Apple, Microsoft, Google, etc busy full-time drawing pumpkins and dinosaurs and whatever - I'm happy to leave it up to them... ;)

**Comment by KronosTheLate** [comment]
The json code fixed the backslash issue, thanks a lot ^_^

In terms of the emojis, I was thinking about the symbols in the actual code. But as that was a side-thing, I say thank you and concider this issue closed ^_^
