### ISSUE TITLE
VSCode always renders → ligature even if ss08 is disabled

### ISSUE THREAD

**Issue by sveniu** [cormullion/juliamono#74]
In all versions I've tried of VSCode (including the latest 1.50.1), entering `->` will render a `→` ligature.

My configuration is as follows:
```json
{
    "editor.fontFamily": "'JuliaMono Medium'",
    "editor.fontLigatures": "'ss05','ss09'"
}
```

The ligatures I have enabled (lighter asterisk, alternate f) work, and it seems when I toggle all the other ones, they behave as expected.

Enabling or disabling ligature `ss08` has no effect: It renders the `→` ligature in either case.

Is this a problem with VSCode or JuliaMono? I don't know where to start looking, but I'm open to pointers.

**Comment by cormullion** [comment]
you need to disable `calt` - the `ss` ones are stylistic sets... I think... 😀

**Comment by sveniu** [comment]
I'm afraid I don't quite understand your suggestion, or how to translate it into vscode's `editor.fontLigatures` setting. That seems to be the relevant setting, but I'm using a value like `"'ss05','ss08'"`, and have no idea how to encode "disable calt" into it. Any hints would be helpful, but I guess this is not actually a juliamono issue in any case, so the issue can be closed.

**Comment by cormullion** [comment]
The [FAQ](https://cormullion.github.io/pages/2020-07-26-JuliaMono/#vs-code) gives this:

>Or if you just don’t like the contextual alternates, prefer the slashed zero, a simpler g, and a lighter asterisk, use this:

> "editor.fontLigatures": "'calt' off, 'zero', 'ss01', 'ss05'",

which should be close to what you need.

**Comment by sveniu** [comment]
Beautiful – thank you!
