### ISSUE TITLE
Add space between JuliaMono

### ISSUE THREAD

**Issue by musm** [cormullion/juliamono#77]
This always trips me up. Unlike other fonts (e.g. Roboto Mono et al.) JuliaMono is one word, instead of two.

**Comment by cormullion** [comment]
Yes, I didn't want to call the font Julia. I feel that would be getting a bit close to a certain programming language...

**Comment by cormullion** [comment]
With fonts like Roboto and DejaVu, the Mono is just a single flavour of the font - Roboto Slab, DejaVu Sans, etc. I didn't want to get into making Julia Sans and Julia Serif... so in that sense Mono is part of the name, not just one member of a family.

**Comment by musm** [comment]
I see the rationale  (@cormullion  who says we don't want a Julia Sans font 😉 )
