### ISSUE TITLE
Some characters in the Mathematical Alphanumeric Symbols block are too low?

### ISSUE THREAD

**Issue by anderslundstedt** [cormullion/juliamono#79]
Thanks for a great font! I noticed that, for example, U+1D622 Mathematical Sans-Serif Italic Small A, looks a bit too low compared to regular text:

<img width="608" alt="Screen Shot 2020-11-11 at 22 36 18" src="https://user-images.githubusercontent.com/4514101/98867130-59692e80-246e-11eb-9e0c-d01a7b6f6c49.png">

If you ever have time to work on this issue I could take a closer look at the entire block, if that would be of help.

**Comment by cormullion** [comment]
Oh, good catch - those things... 😂 Theyre just a bit smaller, really. It wouldn't take too long to enlarge them...

**Comment by cormullion** [comment]
I hate italics.... :)

**Comment by anderslundstedt** [comment]
Looks good to me in the latest release, thanks! As far as I am concerned, you may close this.
