### ISSUE TITLE
Superscripts l, s and x (ˡ, ˢ, ˣ) differ in size and alignment from other superscripts

### ISSUE THREAD

**Issue by anderslundstedt** [cormullion/juliamono#81]
Thanks again for a great font. Just putting this here if you or someone else ever has time to work on it:

<img width="606" alt="Screen Shot 2020-11-13 at 18 01 50" src="https://user-images.githubusercontent.com/4514101/99099260-7cb0ec80-25da-11eb-970e-d6c7a22ab9ee.png">

Code points:

U+02E1 Modifier Letter Small L
U+02E2 Modifier Letter Small S
U+02E3 Modifier Letter Small X

**Comment by cormullion** [comment]
Good idea, thanks!

**Comment by anderslundstedt** [comment]
On a closer look, it seems that the a-z superscripts all shift a bit in alignment and size. The a-z subscripts or the A-Z superscripts do not:

<img width="1205" alt="Screen Shot 2020-11-13 at 23 58 38" src="https://user-images.githubusercontent.com/4514101/99129211-3a54d300-260d-11eb-8fda-a9d08f344d87.png">

**Comment by cormullion** [comment]
Thanks - you must be a bit bored today to be doing that! :)

**Comment by anderslundstedt** [comment]
Yes … and I am also a heavy users/abuser of Unicode superscripts and subscripts (and of much of rest of Unicode as well) … Anyway, in the latest release everything looks fine to my eyes, so feel free to close this issue. Many thanks!

**Comment by cormullion** [comment]
Thanks again... 

(I like to give the 🤖bot something to do...)
