### ISSUE TITLE
Size of ring over letter 'å' (U+00E5)

### ISSUE THREAD

**Issue by DNF2** [cormullion/juliamono#83]
It seems that issues are unlikely to be worked on, but here's one anyway:

The rings over the letters 'Å' (U+00C5) and 'å' (U+00E5), used in the scandinavian languages, are quite small. In 12pt size it looks more like a dot, and it's sometimes difficult to distinguish 'a' and 'å' at a glance.
JuliaMono<img width="46" alt="JuliaMono-36pt" src="https://user-images.githubusercontent.com/7106412/100440119-acfd8e00-30a4-11eb-814a-9db9eb1771eb.png">      
Fira Code <img width="46" alt="FiraCode-36pt" src="https://user-images.githubusercontent.com/7106412/100440132-b0911500-30a4-11eb-8dee-d803c7639420.png">

Can the ring be made bigger?

**Comment by cormullion** [comment]
This is a simple change, and can go in the next release:

<img width="900" alt="Screenshot 2020-12-03 at 10 18 12" src="https://user-images.githubusercontent.com/52289/100996367-e163c500-3550-11eb-914d-3286a877a7c3.png">

There's apparently some debate (at least in TEX-nerd circles) about whether the ring should touch the top or not, but for legibility reasons it's probably better to have a clear gap.

**Comment by knuesel** [comment]
Either there's an impressive optical illusion here, or the circles on `U` and `u` are smaller than the others 😊. I personally find the proposed circles on `A`, `a`, `w`, `y` a bit large, but the ones on `U` and `u` are very nice...

**Comment by cormullion** [comment]
Oh, do they have to be the same size? 😊🤭

**Comment by cormullion** [comment]
v0.028 is now:

<img width="983" alt="Screenshot 2020-12-05 at 13 17 37" src="https://user-images.githubusercontent.com/52289/101276584-dc4b8380-37a5-11eb-9206-c131734655b3.png">

**Comment by DNF2** [comment]
I see there's a `fixed?` (with a question mark) label on this, and I can confirm that it is much better now, thank you. I'd say it's `fixed` (no question mark.)

> There's apparently some debate (at least in TEX-nerd circles) about whether the ring should touch the top or not

I can also absolutely confirm (as a Scandinavian) that the ring _should indeed_ be clearly separated from the top, and I am very curious where these TeX-nerd discussions are.

**Comment by cormullion** [comment]
Thanks! I think I found [this](https://tug.org/pipermail/texhax/2004-January/001523.html) - could have been another thread, I guess... it looked like a rabbit hole so I scampered away :)
