### ISSUE TITLE
Emacs rendering of combining characters

### ISSUE THREAD

**Issue by sje30** [cormullion/juliamono#87]
First off, thank you for the font, and no worries if you can't comment on this (having read your template text here in the issue.)  I'm  wondering though if you could shed any light on why I can't get characters like a followed by x0305 to render as a with the combining overline in Emacs?  I'm thinking of using this for "the mean of a".

I asked on the Emacs help list, and was told "You need to use a font that has glyphs both for a (every font will fulfill that requirement) and the diacritics.  Emacs can only compose characters if their glyphs come from the same font.

See my message:
https://lists.gnu.org/archive/html/help-gnu-emacs/2020-12/msg01058.html

and my screenshot comparing how the same file renders in Emacs (on the left) and xfce4-terminal (on the right).  Note, this is GUI Emacs, not the version of Emacs that runs within a terminal.

https://damtp.cam.ac.uk/user/sje30/temp/accents.png

**Comment by cormullion** [comment]
“You need to find a better font!” - a commenter on that thread. 😀

It works fine on a better OS (MacOS). 😛

More seriously, I don’t think it’s an issue with the font, since diacritics work OK for me. If you want to investigate, you could search the issues at FiraCode HQ https://github.com/tonsky/FiraCode/issues/ - there are similar issues with fonts and editors.

I’ll ask around for help...

**Comment by sje30** [comment]
Thank you.   Checking the firacode + emacs, I don't see anything relating to combining characters, but I do for ligatures.  It looks like Emacs needs hacking to handle ligatures in firacode.  https://github.com/jming422/fira-code-mode  -- I will investigate.

(And just checking - when you say it works on MacOS, do you mean it works on Emacs GUI on MacOS?  I'm guessing not.)

**Comment by cormullion** [comment]
I don't know about EmacsGui.

```julia
for i in 1:20
      print('a', Char(769 + i))
end

âãāa̅ăȧäảåa̋ǎa̍a̎ȁa̐ȃa̒a̓a̔a̕
```

Obviously OK in Emacs/Terminal.

<img width="801" alt="Screenshot 2020-12-30 at 09 28 34" src="https://user-images.githubusercontent.com/52289/103342500-835bcc00-4a81-11eb-8c78-94c1d128c159.png">

Most of the diacritic characters are defined in the font:

<img width="500" alt="Screenshot 2020-12-30 at 09 34 20" src="https://user-images.githubusercontent.com/52289/103342745-3e846500-4a82-11eb-9628-ad4a2c88df90.png">

I expect you'll have to hack Emacs even more to get it to do the right thing... :)

**Comment by sje30** [comment]
Thanks for this.  Will keep digging.

**Comment by knuesel** [comment]
I just tried with the latest JuliaMono (0.028). I compiled Emacs 27.1 with GTK and HarfBuzz 2.6.4 on Ubuntu 20.04 and I can't reproduce the problem. I don't have any `.emacs` config, Emacs is inheriting the JuliaMono font choice from the gnome-weaks settings.

**Comment by sje30** [comment]
Thanks @knuesel -- good to hear there is some success!

It gets weirder for me (I'm using Emacs 27.1 from manjaro.)

```

;; case 1
(when (member "Monaco" (font-family-list))
   (set-face-attribute 'default nil :font "Monaco-13"))

;; case 2
(when (member "JuliaMono" (font-family-list))
   (set-face-attribute 'default nil :font "JuliaMono"))

```

when asking it to show "gamma bar" and "x bar" Monaco (case 1) gets both right, but in case 2 (JuliaMono) it gets gamma correct, but not x!

case 1:
![case1](https://user-images.githubusercontent.com/1095067/103346285-7e9c1580-4a8b-11eb-8ca0-9ff0d9dc57fa.png)

case 2: 

![case2](https://user-images.githubusercontent.com/1095067/103346305-88be1400-4a8b-11eb-9ad7-b321a3534dcc.png)

**Comment by sje30** [comment]
weirder still... trying the JuliaMono font on Chromium (which I believe uses harfbuzz too for rendering) to view a file, both look fine:

![case3](https://user-images.githubusercontent.com/1095067/103347132-0551f200-4a8e-11eb-8d7b-ff5c190823aa.png)

**Comment by cormullion** [comment]
Vim? 😁

**Comment by sje30** [comment]
vim works in the terminal, right?  If so, I expect that to work ok.   Emacs in the terminal works ok for me too (as it is the terminal doing the composing not the Emacs GUI.)

**Comment by cormullion** [comment]
Oh, yes, true. I'm still using Atom... :)

**Comment by sje30** [comment]
I've posted an issue too on harfbuzz in case anyone else is following this.  

https://github.com/harfbuzz/harfbuzz/discussions/2790

**Comment by cormullion** [comment]
Thanks! I really appreciate your commitment to finding a solution!

**Comment by sje30** [comment]
thank you for your efforts too!

**Comment by sje30** [comment]
not exactly why my solution works, but installing the font to my home directory rather than using the arch package worked.

https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-01/msg00001.html

yay!

**Comment by cormullion** [comment]
Thanks - the Emacs discussion guys said that it was a problem just on your installation? I hate it when that happens... :)

**Comment by sje30** [comment]
yes.  but that's okay.  I'm glad to be looking at nice fonts now... great work, thank you.

**Comment by ScottPJones** [comment]
Cormullion + Emacs = Nice!

**Comment by cormullion** [comment]
@ScottPJones I only used it for a minute - eventually I had to kill the Terminal because I didn't know how to quit Emacs (apparently Ctrl-C isn't good enough... :)).

**Comment by ScottPJones** [comment]
@cormullion Yeah, it's C-X C-C :-) (otherwise, you'd be exiting by mistake all the time!)
