### ISSUE TITLE
Small alignment and shape issues

### ISSUE THREAD

**Issue by knuesel** [cormullion/juliamono#88]
While working on a comparison of math symbols in monospace fonts, I stumbled on the following issues (some might be subjective but I don't think any of this is intended, but of course do of this what you want!). 

`\bfJ` (U+01D409) probably extends too low. Find the intruder here:

![image](https://user-images.githubusercontent.com/2412819/104022888-2e2a6380-51c1-11eb-9716-f7ab642755f3.png)

`\^M` (U+1D39) is thicker than the others:
![image](https://user-images.githubusercontent.com/2412819/104023000-53b76d00-51c1-11eb-8e82-3b91fa761e32.png)

`\overleftrightarrow` (U+20E1) is too close to the letter, and `\underleftrightarrow` (U+034D) probably too small: ![image](https://user-images.githubusercontent.com/2412819/104023147-82354800-51c1-11eb-87e2-e46dbc7bf08a.png)

`\vec` (U+20D7) is slightly lower on D than other capital letters: ![image](https://user-images.githubusercontent.com/2412819/104023234-a4c76100-51c1-11eb-966d-1a89f668cdb7.png)

`\vec` is too close to `\nabla` (U+2207) (the `∇⃗` symbol is common in mathematics).

`\bbP` (U+2119) is missing.

U+1DB2 is positioned too high, and according to https://unicode.org/charts/PDF/U1D80.pdf it should look a bit like the other (non-loopy) variant but with serifs (it's based on \ltphi `ɸ` U+0278). Note that the Julia completions are misleading here: U+1DB2 is currently mapped to `\^Phi` although it's the superscript of a lowercase letter, the latin variant of phi. I've proposed a change in Julia to fix this. In any case, if you add small serifs to U+1DB2 it will also make it look more like `\Phi` 😊.

The integrals ∬ (U+222C), ∭ (U+222D), ∯ (U+222F), ∰ (U+2230), ⨌ (U+2A0C),  ⨗ (U+2A17) look quite thinner and shorter than the other integrals. The alignment and style of the integrals (`∫∬∭∮∯∰∱∲∳⨌⨍⨎⨏⨐⨑⨒⨓⨔⨕⨖⨗⨘⨙⨚⨛⨜`) is also not uniform:
![image](https://user-images.githubusercontent.com/2412819/104025726-55832f80-51c5-11eb-9ba5-848548513f36.png)

(I want to say that these are minor issues and JuliaMono is by far the best of the fonts I tested!)

EDIT: one more:

`\Longrightarrow` (U+27F9) should be symmetrical to `\Longleftarrow`, i.e. without a vertical bar (not like U+27fE).

**Comment by cormullion** [comment]
Thanks! Now that we've started another lockdown, I'm very grateful to you for providing some small things for me to do! 😄😄😄

I think the Phi situation has managed to completely confuse me by now. I hope we're going to converge on some kind of truth soon..

**Comment by knuesel** [comment]
Glad that this doesn't come at a bad time 😄

Indeed the phi situation is terrible, and this "latin" variant makes it even worse. Also I just found out that some REPL completions are wrong in Julia: for example `\varphi` and `\bfvarphi` give the loopy variant as expected, but `\itvarphi` and `\bivarphi` give the other one. Same for the different styles of `\varepsilon`. I initially thought it was a mistake in JuliaMono but no, they're all correct as far as I can tell (except for U+1DB2 as described in this issue). Hopefully this will be fixed soon: https://github.com/JuliaLang/julia/pull/39148.

**Comment by cormullion** [comment]
mostly fixed in v0.030.

**Comment by knuesel** [comment]
Excellent! I made a mistake with `\bbP` (U+2119): it's already in the font actually (I was confused and mislead by Linux Libertine O: that font wrongly includes a character U+1D547 which is reserved).

It all looks good to me, did I miss something?

I've put this new version in the comparison at https://mono-math.netlify.app/. JuliaMono's support of math symbols is outstanding.

**Comment by cormullion** [comment]
It all looks OK. There's always the next release...

Your mono-math page looks amazing - there's a lot of work there (hope you scripted some of it). I'll find it very useful!

What's the box at the very end? Perhaps you could add some alt tags one day...?

Your support has been invaluable - thanks!

You might be interested in [this](https://algorithmsbook.com) - they've gone for the heavier weights of JuliaMono for their listings...

**Comment by knuesel** [comment]
Thanks! Yes it's mostly scripted (see https://github.com/knuesel/mono-math/), the most laborious was to prepare the Unicode samples, and I'm still finding mistakes there (see below). Good point for the alt tags, I'll add them.

That book looks awesome, thanks for the link!

The last box contains Arabic symbols. You can see the Unicode samples at https://mono-math.netlify.app/samples.jl (or on GitHub of course). Not sure anyone would use these symbols in code, it would be a bit weird since their right-to-left I think.

I've added the font Everson Mono to the comparator. It has very good support for math symbols (though some blocks are missing), and it made me realize that I was using some invalid codepoints in my samples. I didn't see it before because JuliaMono defines them. I don't know if that was intentional? If not, you can remove the following:

U+1d49d, U+1d4a0, U+1d4a1, U+1d4a3, U+1d4a4, U+1d4a7, U+1d4a8, U+1d4ad.

**Comment by cormullion** [comment]
Oh yes, those are the script letters which were put into earlier Unicode tables. 

>"Script symbols already encoded in the Letterlike Symbols block are omitted here to avoid duplicate encoding."

Unicode's a bit untidy... 😂 I'll remove them...

**Comment by knuesel** [comment]
OK! In any case I think this can be closed now 😄 Thanks!
