### ISSUE TITLE
Ligature for `::`?

### ISSUE THREAD

**Issue by simeonschaub** [cormullion/juliamono#9]
Might just be personal preference, but I do think `::` would benefit from a ligature putting the two colons just a tad closer and maybe making them the tiniest bit smaller. I think currently, the fact that the space between the two colons is larger than the space after the preceding and before the following character looks a bit odd when looked at closely. FWIW, FiraCode also has this ligature, and I think it makes Julia code a bit more readable.

**Comment by cormullion** [comment]
Making it an Alternative StylisticSet (which are opt-in) works quite well. 

<img width="1490" alt="Screenshot 2020-08-03 at 12 51 25" src="https://user-images.githubusercontent.com/52289/89179695-23bbcc00-d588-11ea-8ac2-5b233d7d68e4.png">

Left: without - Right: with

Perhaps you can think of a better name for it too.

**Comment by simeonschaub** [comment]
Oh, very nice! Perhaps "Type Annotation Ligature" is a better name?

**Comment by cormullion** [comment]
Perhaps `Double colon` would be better, being a little more explicit? "Type" is a little ambiguous in this context... 😄 And I suppose it's not technically a ligature either, being neither a single glyph nor part of the Typography panel's Ligature section...   But `Type annotation` might be OK. `Type assertion`?

I'll welcome more opinions... :)

**Comment by knuesel** [comment]
I like `Double colon`: it describes what it is, it's always correct. On the other hand `Type annotation` and similar describe what it means in a specific context, so it's wrong in other contexts (for example in C++ `::` is used to separate scopes). JuliaMono is a great monospace font, not just a Julia font!

**Comment by cormullion** [comment]
Thanks @knuesel!

As an alternative to making it opt-in Stylistic Set, it can be added to the (usually opt-out, on by default) Contextual Alternates.

The advantage is that it doesn't need a name and is more likely to be available (or selectable) in various apps (on macOS: Atom  (👍), VSCode (👍), Terminal (👍), Kitty (👍), iTerm (👍), Alacritty (👎).

**Comment by cormullion** [comment]
Added in v0.005 as a contextual alternate - see if it works OK -  I can remove it if not and think again...

**Comment by simeonschaub** [comment]
Works great, thanks so much!
