### ISSUE TITLE
Implement infinite arrows

### ISSUE THREAD

**Issue by musm** [cormullion/juliamono#93]
JuliaMono
![image](https://user-images.githubusercontent.com/4319522/107792386-16e01800-6d23-11eb-953e-e3a3e1cc2cca.png)

E.g. Cascadia Code:
![image](https://user-images.githubusercontent.com/4319522/107792298-f7e18600-6d22-11eb-9e27-e333565590ed.png)

Breadcrumbs: https://github.com/microsoft/cascadia-code/issues/276

Many thanks for your work here.

**Comment by cormullion** [comment]
Good idea (and thanks for the support)! I'm currently finding out how to do this, then it will need some testing...😉

**Comment by cormullion** [comment]
The current master version has an attempt at "infinite" arrows (well, it's not infinite, more like 140) if you want to give it a try...

**Comment by musm** [comment]
Looks pretty good. It is missing the infinite connection when doing multiple equal signs
```
=====   # not joined but should be
```

**Comment by cormullion** [comment]
not sure about "should" 😂 This isn't FiraCode 🤣🤣🤣

**Comment by musm** [comment]
Indeed, this is a design decision whether it "should". Although if the infinite arrow is implemented, it's not a stretch that `---` and `===` are also implemented.  I suppose Cascadia adopted Fira Code. Cascadia has two variants, the 'Mono' version has such 'enhanced features' disabled and the 'Code' version with all the bells and whistles.

'Cascadia Code'   --- fancy jazz enabled. 
'Cascadia Mono' --- plain variant.

**Comment by cormullion** [comment]
So my thinking so far:

For decorative purposes, the infinite arrow (this issue) is OK, since it's used in the Julia package manager...

I don't like "===" losing its clarifying spaces. Ligature lovers should use FiraCode and Cascadia.  😄

For drawing lines with "---" and "===" and the like there are already plenty of good Unicode characters:  ─, ━, ┈ ,┉ ,┄ ,┅ ,═ ,╍ ,╌ , ═ ... etc

It's easy to add an optional font feature that combines four or more equals signs:

https://user-images.githubusercontent.com/52289/108096460-e842a400-7078-11eb-8f13-a7c4ebd433e9.mov

This should work in most modern apps but is off by default.

**Comment by anderslundstedt** [comment]
As I am writing a lot of logical formulas, I love the possibility of multiple-width arrows that this allows!

> For drawing lines with "---" and "===" and the like there are already plenty of good Unicode characters: ─, ━, ┈ ,┉ ,┄ ,┅ ,═ ,╍ ,╌ , ═ ... etc

Any chance of having the line-drawing characters line up nicely with the arrows? I guess these would be the combinations:

- 2500+2192: `─→`
- 2190+2500: `←─`
- 21D0+2550: `⇐═`
- 2550+21D0: `═⇒`

**Comment by cormullion** [comment]
Yes, those should be fairly easy - perhaps next week I'll have a look. 😄

**Comment by anderslundstedt** [comment]
I guess the combination 2190+2192 could also be useful: `←→`

**Comment by anderslundstedt** [comment]
And of course, 21D0+21D2: `⇐⇒`

**Comment by anderslundstedt** [comment]
The alignment of line-drawing characters with arrows looks perfect in the latest release. Great job!

**Comment by musm** [comment]
When creating hardlink on Windows I have:
![image](https://user-images.githubusercontent.com/4319522/110152801-2c8baf00-7db0-11eb-8d92-3b5f07111cbc.png)

Any chance we could improve the arrows here by merging the left arrow glyph?
<<===>>

**Comment by waldyrious** [comment]
Not sure if it's appropriate to add this in this thread (happy to move it to a separate issue) — for HTML comments, the closing "arrow" is merged with a ligature, but the opening isn't:

<img alt="Screenshot 2021-03-05 at 19 56 38" src="https://user-images.githubusercontent.com/478237/110167032-118b6000-7ded-11eb-88af-8de0461dcf28.png">

For comparison, here's what Fira Code does:

<img alt="Screenshot 2021-03-05 at 19 59 48" src="https://user-images.githubusercontent.com/478237/110167260-6a5af880-7ded-11eb-9015-8f77689a4222.png">

**Comment by cormullion** [comment]
Fira Code is the font of choice for ligature-lovers. 😂

**Comment by waldyrious** [comment]
Absolutely, and I'd happily use the ligature-less `-->` myself; my only concern is that the font's default behavior makes comments in HTML/XML documents look unbalanced.

**Comment by cormullion** [comment]
@musm 

Is this what you mean?

<img width="184" alt="Screenshot 2021-03-07 at 18 04 51" src="https://user-images.githubusercontent.com/52289/110249777-aae27f80-7f6f-11eb-88a1-60266a2d512e.png">

@waldyrious That `<!--` is a monster, not even a proper arrow... :)

**Comment by musm** [comment]
@cormullion  yep
