### ISSUE TITLE
large contour integral combining characters

### ISSUE THREAD

**Issue by ntessore** [cormullion/juliamono#95]
Thanks for this font, which is the only monospace font that makes writing plain text math notes feasible.

It would be great if it could properly set the three combining glyphs to make large contour integrals:

    U+20D8  Combining Ring Overlay
    U+20D9  Combining Clockwise Ring Overlay
    U+20DA  Combining Anticlockwise Ring Overlay

These are currently available, but too small, and the spacing is off. See the three large integrals

    #############
    # ⌠ # ⌠ # ⌠ #
    # ⎮⃘ # ⎮⃙ # ⎮⃚ #
    # ⌡ # ⌡ # ⌡ #
    #############

which have a central extender that becomes slightly larger than one character (as in the GitHub font):

<img width="171" alt="image" src="https://user-images.githubusercontent.com/3993688/108054532-ab5db980-7046-11eb-8645-91556ef86985.png">

It would be great to have the existing rings from ∮ ∲ ∳ be proportionally scaled to the large integral sign:

<img width="191" alt="image" src="https://user-images.githubusercontent.com/3993688/108054789-0394bb80-7047-11eb-9081-5d6cf3c72594.png">

**Comment by knuesel** [comment]
Could you show an example (screenshot) of the problem with JuliaMono? I cannot reproduce it, it seems to work fine in Gnome Terminal, gedit and Chrome. I see something like this: https://mono-math.netlify.app/samples/14/Linux/ot/svg/JuliaMono/01.svg

I do see one issue with the clockwise and counterclockwise glyphs: the arrows are not very readable. Indeed by zooming in the SVG we see that the arrows heads are shown as straight "dashes" rather than arrows...

Regarding code samples on GitHub as in your example: what you see depends on the fonts installed on your system. Looking in the Chrome devtools, it seems that GitHub requests the font "SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace" (using the first font from the list that is available on the user's system). Note that "monospace" is a generic name that lets the browser choose a suitable fallback font.

A look at https://mono-math.netlify.app shows that:

* SF Mono and Consolas don't have these integral symbols
* Liberation Mono has the top and bottom pieces
* Menlo has the three pieces but not the circular combining characters

I have all these fonts on my system, and my browser is configured to use JuliaMono as fallback `monospace` font. As a result, the GitHub code sample renders as a Frankenstein monster: the integral top and bottom are taken from Liberation Mono, and the middle part with combining character is taken from JuliaMono 😕 Not surprising that the integral parts don't connect properly...

**Comment by ntessore** [comment]
The first image in the post was actually a screenshot of the issue, taken from [here](https://ntessore.github.io/txt/oint.html). Since it looks good for you, could it be an issue with the web font?

**Comment by knuesel** [comment]
I think it's an issue with that web page: it uses the following CSS:

```css
 @font-face {
  font-family: JuliaMono-Regular;
  src: url("font/JuliaMono-Regular.woff2");
  font-weight: normal;
  font-style: normal;
}

pre {
  font-family: 'JuliaMono', monospace;
  font-weight: normal;
  font-style: normal;
  width: 72ch;
  margin: 1em auto;
}
```

The `font-family` in the `pre` styles should use the same name as defined in `@font-face`. But then, it appears that the specified file `font/JuliaMono-Regular.woff2` is not on the server anyway...

**Comment by ntessore** [comment]
Ah sorry, the missing file was because of me trying to figure out what's going on. But of course you are correct that the names should match! Which is a problem with [the instructions](https://cormullion.github.io/pages/2020-07-26-JuliaMono/#how_can_i_use_the_web_fonts_for_my_blog), I suppose, which read:

```
Find the relevant CSS file, and add a link to the WOFF2 stored on the server. For example:

    @font-face {
        font-family: JuliaMono-Regular;
        src: url("https://cdn.jsdelivr.net/gh/cormullion/juliamono/webfonts/JuliaMono-Regular.woff2");
    }

This accesses the current version the Regular font using the jsDelivr CDN (Content Delivery Network).

Then use CSS selectors:

    font-family: "JuliaMono";
```

Anyway apologies for the confusion.

**Comment by cormullion** [comment]
@ntessore Thanks for the report - I rely on your sharp eyes!

@knuesel Thanks as always for your assistance! I was going to publicize that cool webpage but then I noticed that your were on Netlify, and - if my experience is typical - you'll suddenly get a bill for the increased traffic... :)

**Comment by ntessore** [comment]
Ah but I wasn't totally out of it when I first noticed this issue: The misalignment [is there](http://localhost:4000/txt/oint.html).

<img width="171" alt="image" src="https://user-images.githubusercontent.com/3993688/108075371-30a29780-7062-11eb-970d-7a572c1df6ec.png">

So ignore the stuff about the scaling; I managed to not notice I was not looking a JuliaMono anymore after a while (so no sharp eyes). This here is what I actually wanted to report :)

**Comment by cormullion** [comment]
I'm a bit puzzled.

This is what I get in Apple Terminal:

<img width="210" alt="Screenshot 2021-02-16 at 14 31 45" src="https://user-images.githubusercontent.com/52289/108076872-cee32d00-7063-11eb-91a9-dabdc0261a88.png">

and this is Atom:

<img width="522" alt="Screenshot 2021-02-16 at 14 33 37" src="https://user-images.githubusercontent.com/52289/108077033-fe923500-7063-11eb-8984-165dd9362852.png">

I'll definitely change those to arrows though!

**Comment by knuesel** [comment]
Here's how the new version of the Web page renders on my system (Ubuntu 20.04):

![image](https://user-images.githubusercontent.com/2412819/108077357-ba576280-706c-11eb-8f70-d1253dc7b942.png)

(It's the same in Chrome and Firefox, as well as Gnome Terminal, etc.... I think they all use HarfBuzz as font shaper.)

**Comment by cormullion** [comment]
Oh, are we talking about the way the stems overlap where they meet the higher/lower elements? Or the way the combining glyph in https://github.com/cormullion/juliamono/issues/95#issuecomment-779868284 alters the line spacing?

**Comment by cormullion** [comment]
Anyway, I've edited them to look like this (Apple Terminal with linespacing slightly reduced):

<img width="286" alt="Screenshot 2021-02-16 at 14 54 32" src="https://user-images.githubusercontent.com/52289/108079661-f5ef2e00-7066-11eb-9844-5df4ff679112.png">

**Comment by knuesel** [comment]
These look great! Though I wonder if the arrow heads won't be a bit small at normal size?

**Comment by ntessore** [comment]
I am talking about the combining characters pushing the right borders out. But as @knuesel notes, this seems to be something wrong with Safari web font rendering specifically. I will try and hunt it down. The updated rings look great, feel free to close this.

**Comment by cormullion** [comment]
i’ll have a think about alternatives, but you’re right, it’s all very small at the moment. 🔬🔬🔬🔬

**Comment by ntessore** [comment]
I seem to be seeing [this MathJax issue](https://github.com/mathjax/MathJax/issues/1709#issuecomment-305648698), which has a couple of action points [in this comment](https://github.com/mathjax/MathJax/issues/1709#issuecomment-362814675). Just FYI, no idea if any of it is applicable here, and I don't expect any changes.

**Comment by cormullion** [comment]
interesting stuff. I didn’t know that MathJax used any monospaced fonts.

**Comment by ntessore** [comment]
Not sure that they do; for as little as I understand, the issue appears to be more generally of how Safari places combining characters that should come out at zero extra width, such as accents, or this combining ring.
