### ISSUE TITLE
request for JuliaMono SemiBold

### ISSUE THREAD

**Issue by JeffreySarnoff** [cormullion/juliamono#96]
only if the intermediate weights are mostly autogenerated now
and definitely not if each requires a lot of hand tuning
the sweet spot is closer to the Medium than the Bold, ?1/3away?
(I just find most Bold fonts difficult to use to advantage on screens. Occasionally, I use a Medium or SemiBold monospace face with the Regular or the Regular and the Light faces to emphasize parts of an expression and de-emphasize the rest during a presentation)

**Comment by cormullion** [comment]
It's possible to squeeze in a weight:

<img width="1637" alt="Screenshot 2021-02-17 at 09 33 10" src="https://user-images.githubusercontent.com/52289/108184545-3bf9cf80-7103-11eb-8549-9da76deb3637.png">

**Comment by anderslundstedt** [comment]
Any chance for a ExtraLight version also? When using (abusing?) JuliaMono to typeset mathematical notes, I noticed that the PDFs look slightly more readable when viewed in Chrome than when viewed in Preview or when printed. I think this is because most fonts (not only JuliaMono) are thinner in Chrome's PDF viewer for me, for some weird reason.

**Comment by cormullion** [comment]
Thinner than Light would be difficult, because it would be extrapolation rather than interpolation... I'll have a look.

**Comment by JeffreySarnoff** [comment]
or, rename Light as ExtraLight and add a lighter than Regular as Light.

**Comment by anderslundstedt** [comment]
> or, rename Light as ExtraLight and add a lighter than Regular as Light.

I might be misunderstanding something, but what I am wishing for is a version thinner than the current thinnest version (Light).

**Comment by JeffreySarnoff** [comment]
(yes, as I read your request, I felt a little levity would be ok -- apologies for the misread).
