### ISSUE TITLE
Support \bf<char> with Black characters

### ISSUE THREAD

**Issue by msjgriffiths** [cormullion/juliamono#97]
This is perhaps a little crazy, but.

I would like to closely match the visual appearance of mathematical equations in Julia code. I can do that with unicode characters. Take, for example, these equations (neural net module):

<img src="https://user-images.githubusercontent.com/1093821/108539158-9df63880-72ad-11eb-986b-0e69df3d1544.png" width="200" />

I can replicate this model in Flux with this:

```julia
⊙(x, y) = x .* y
function (m::SRUCell)(cₜ₋₁, xₜ)
    jₜ = σ.(m.Wⱼ*xₜ + m.vⱼ ⊙ cₜ₋₁ + m.bⱼ)
    cₜ = jₜ ⊙ cₜ₋₁ + (1 .- jₜ) ⊙ (m.W*xₜ)
    rₜ = σ.(m.Wᵣ*xₜ + m.vᵣ ⊙ cₜ₋₁ + m.bᵣ)
    hₜ = rₜ ⊙ cₜ + (1 .- rₜ) ⊙ (xₜ * m.α)
    return(cₜ, hₜ)
end
```
However, the parameter values (e.g. Wⱼ) don't stick as out much. I'd like to make those bold. In LaTeX or Word, I'd just use the Bold (or Black) version of the font. That's harder to do in code itself. But I _can_ use the unicode bold characters, i.e.

```julia
⊙(x, y) = x .* y
function (m::SRUCell)(𝐜ₜ₋₁, 𝐱ₜ)
    𝐣ₜ = σ.(m.𝐖ⱼ*𝐱ₜ + m.𝐯ⱼ ⊙ 𝐜ₜ₋₁ + m.bⱼ)
    𝐜ₜ = 𝐣ₜ ⊙ 𝐜ₜ₋₁ + (1 .- 𝐣ₜ) ⊙ (m.𝐖*𝐱ₜ)
    𝐫ₜ = σ.(m.𝐖ᵣ*𝐱ₜ + m.𝐯ᵣ ⊙ 𝐜ₜ₋₁ + m.bᵣ)
    𝐡ₜ = 𝐫ₜ ⊙ 𝐜ₜ + (1 .- 𝐫ₜ) ⊙ (𝐱ₜ * m.α)
    return(𝐜ₜ, 𝐡ₜ)
end
```

Apart from the obvious downside of being very hard to maintain (i.e. typing `\bfW` instead of `W`), it also looks strange.

If I *do* put into a text editor and manually format to use `Black` it looks pretty good -- the important parameters really pop out.

<img src="https://user-images.githubusercontent.com/1093821/108539747-60de7600-72ae-11eb-99d4-81459ab3033e.png" width="300" />

I don't know if it's easy to add support for all Unicode bold font elements by using the characters in JuliaMono-Black, but I would love it if worked.

**Comment by cormullion** [comment]
Hi! Thanks for the suggestion! Interesting... These maths characters are a bit of a puzzle - putting bold and italic in a font which is thin and roman was very confusing for me... 😂 

At the moment the `sans` and `bsans` sans and bold sans maths characters are the same for all weights of the font, so your idea is that the sans is the same weight as the font's weight, and the bold is the same weight as the next heavier weight in the font? (So bold sans A in JuliaMono-Light is the same weight as the roman sans A in JuliaMono-Regular....?) Or is it that the bold sans should be the same weight as JuliaMono-Black in all weights? I can see some possibilities amid the confusion... 😀 

I suppose some coding environments would allow you to specify styles of those parameter values using different font weights, like in CSS, if your highlighter could distinguish them easily.

**Comment by msjgriffiths** [comment]
I think the "obvious" thing would be for `bsans` to be the next heaver weight -- however, I'm not sure that's visually distinct enough. If all `bsans` were to be the same weight, I'd suggest Black. Otherwise, perhaps weight+2 or weight +3.

As an example, I took the code snippet and set the main font to `JuliaMono-Light`. I then varied the symbols I wanted to be bold, changing in turn from `Light`, `Regular`, `Medium`, `Bold`, `ExtraBold`, and `Black`. That maximizes the font contrast (as opposed to using `Regular` as the basis).

In my opinion (_not worth very much..._) it's difficult to differentiate the bold characters until you get to Light+2 (e.g. `Medium`) and it only really starts to pop at `Bold`. Even `Black` is not too much.

Ideally, yes, you could set the relative weight of the unicode bold characters in your edit (in my case, VSCode/Sublime). I don't know how to do that however....

![image](https://user-images.githubusercontent.com/1093821/108603735-a6b34100-7377-11eb-8697-2668e7096f51.png)

![image](https://user-images.githubusercontent.com/1093821/108603749-ba5ea780-7377-11eb-953b-4e39f8af1ec0.png)

![image](https://user-images.githubusercontent.com/1093821/108603770-dfebb100-7377-11eb-907c-b24bb555906c.png)

![image](https://user-images.githubusercontent.com/1093821/108603778-ef6afa00-7377-11eb-8709-7eca946909bc.png)

![image](https://user-images.githubusercontent.com/1093821/108603791-014c9d00-7378-11eb-8e27-8e8fa287de3c.png)

![image](https://user-images.githubusercontent.com/1093821/108603809-0d385f00-7378-11eb-9afd-99223547e093.png)

**Comment by cormullion** [comment]
Greatm thanks - that's some quality research there! 

I'd be happy to use Bold as the `\boldsans` - I think the Black is perhaps a tad disruptive visually...? So for Light and Regular the `\sans` uses Regular and the`\boldsans` uses Bold, and for Bold and Black the  `sans` uses Regular and the `\boldsans` uses Black... ? I don't want to make a Vanta Black! (Well I do, really, but that would be more effort.)

I might try it out for the next release - can always re-visit it (version 0.... 😀).

**Comment by msjgriffiths** [comment]
That sounds fabulous to me!
