### ISSUE TITLE
Subscripted commas look like tick marks instead

### ISSUE THREAD

**Issue by pbouffard** [cormullion/juliamono#98]
The subscripted comma, e.g. in this: `J₁ˏ₁` appears as a tick mark:

![image](https://user-images.githubusercontent.com/231346/108616290-ff5afc00-73c0-11eb-8543-6d78e768ba8e.png)
(VS Code, looks identical in Terminal)

Same text in Monaco:
<img width="63" alt="image" src="https://user-images.githubusercontent.com/231346/108616362-a344a780-73c1-11eb-8b75-515428303bea.png">

This is used in the array syntax for the [`@parameters` and `@variables` macros in ModelingToolkit.jl](https://mtk.sciml.ai/stable/highlevel/#ModelingToolkit.@parameters). (Note that the docs page doesn't even render those characters correctly but the images above are from actual output)

MacOS Big Sur.

**Comment by cormullion** [comment]
Hi! What’s the Unicode number?

**Comment by knuesel** [comment]
Looking at that page, it's 0x0312 "COMBINING TURNED COMMA ABOVE". So it seems it is Monaco that is wrong, and it has misled people to write things like `y₂̒₁`.

Reference: https://www.unicode.org/charts/PDF/U0300.pdf

Back to JuliaMono, it renders it like this:

![image](https://user-images.githubusercontent.com/2412819/108618526-5c859a80-741f-11eb-9156-84c79750ba19.png)

which seems fine for normal letters (maybe a bit to close to the letter?), but overlaps with the character if it's a superscript. I don't know if it's wort the trouble setting anchors for combining marks on subscripts/superscripts?

As for the example from ModelingToolkit it renders correctly I think: 
![image](https://user-images.githubusercontent.com/2412819/108618609-c43be580-741f-11eb-969f-f0a5b6cdb70a.png)

**Comment by knuesel** [comment]
Sorry, I just realized @pbouffard's example was using a different character: U+02CF "MODIFIER LETTER LOW ACUTE ACCENT". This should indeed be shown at the bottom (cf https://www.unicode.org/charts/PDF/U02B0.pdf) while JuliaMono shows it at the top...

**Comment by cormullion** [comment]
Hi Jeremie - thanks as usual! So that should appear below the previous glyph, unconnected, right, if it's a modifier?

**Comment by knuesel** [comment]
My pleasure! Looks like it's a "spacing" modifier: https://en.wikipedia.org/wiki/Spacing_Modifier_Letters so it should appear in its own space after the previous glyph (same as the other characters in https://www.unicode.org/charts/PDF/U02B0.pdf ).

**Comment by cormullion** [comment]
Oh, that sort of modifier.. .:) Should be an easy fix. Thanks!

**Comment by cormullion** [comment]
Current status:

<img width="497" alt="Screenshot 2021-02-23 at 14 45 24" src="https://user-images.githubusercontent.com/52289/108860096-c94a9180-75e5-11eb-85cd-62c999e4e824.png">

will hopefully be releasing this later this week.
